build_scripts/build.sh, build_scripts/prep_external_site.sh, package.json
Closes https://github.com/mitodl/ocw-hugo-themes/issues/4
Currently, the `build.sh` script deposits webpack artifacts at `base-theme/assets/dist` relative to `ocw-hugo-themes`, the git hash text file to `dist/static/` relative to `ocw-hugo-themes` which is not ideal.  These artifacts should all be deposited in the `dist` folder of the site being built.  This PR modifies the `build.sh` build script to output all build artifacts to the `dist` folder relative to the `EXTERNAL_SITE_PATH` variable.
There has also been some confusion surrounding linking Hugo sites to a local copy of the `ocw-hugo-themes` repo, so `prep_external_sites.sh` was modified to simplify this by simply backing up the `go.mod` file if it exists and then write one in that links the site to the local copy of your theme …
=> output all build artifacts to external site path's dist folder

package.json, www/assets/js/lib/search.js, www/assets/js/lib/search.test.js, yarn.lock
Fixes https://github.com/mitodl/ocw-www/issues/93
Instead of using `short_url`, this parses `url` which is the legacy url in order to get the section parts. Ideally this would be done in ocw-data-parser but at this point it seems simpler to fix it here.
Search for "water oceans" with the quotes. Click on "resources". Hover over the link in the first result. It should be something like `http://localhost:8063/courses/ec-719-d-lab-water-climate-change-and-health-spring-2019/sections/additional-resources/water-oceans/`, depending on your open-discussions instance
=> Parse URL to fix section handling

base-theme/layouts/partials/site_root_url.html, base-theme/layouts/partials/webpack_url.html, example_configs/example.base.config.toml, example_configs/example.course.config.toml, example_configs/example.www.config.toml
Closes https://github.com/mitodl/ocw-hugo-themes/issues/17
This is related to the recent work we have done to separate "theme" and "content."  A default `baseUrl` of `http://localhost:3000` was inadvertently set in the default config for `ocw-www`, causing all builds with `baseUrl` unset to assume this was the value. 
If you remove this value, links to webpack resources do not render properly at all.  This PR adds some conditional checks to the `webpack_url.html` and `site_root_url.html` to make sure that `site.BaseURL` is set before using it.
- Clone `ocw-www` and check out the `cg/remove-dev-baseurl` branch
- Configure `ocw-hugo-themes` to point at your local copy of `ocw-www` by setting the path to it in `EXTERNAL_SITE_PATH`
- Run `npm run build` and inspect the output (`ocw-www/dist`) …
=> check if site.BaseURL is set before trying to use it

course/layouts/partials/course_info.html, course/layouts/partials/partial_collapse_list.html
Fixes https://github.com/mitodl/ocw-course-hugo-theme/issues/60
Disables collapse for instructors list when viewing course info on course home page
View `8-01sc-classical-mechanics-fall-2016` by setting the course id in `.env` and running `npm run start:course`. Look at the instructors list. It should show 5 instructors without an option to toggle. Click on "Assignments" on the sidebar to go to the assignments page. You should see the course info on the right side, and the instructors list should show an option to expand there.
The changes should look roughly the same on mobile as they do on desktop: no expander for instructors on the course home page, expander for instructors elsewhere.
=> Disable collapse for instructors list

www/assets/js/components/SearchResult.js, www/assets/js/components/SearchResult.test.js
closes https://github.com/mitodl/ocw-hugo-themes/issues/8
This pr removes the default Prof. salutation
Run the search. You should no longer see salutations for instructors.
Checkout `ab/fix-salutation` in open and run
```
from course_catalog.api import *
sync_ocw_courses(course_prefixes=["PROD/8/8.01/Fall_2016/8-01sc-classical-mechanics-fall-2016/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
in open
Go to the search and search for "Classical Mechanics"
Verify that the instructors are
```
Prof. Deepto Chakrabarty, Dr. Peter Dourmashkin, Prof. Anna Frebel, Dr. Michelle Tomasik, Prof. Vladan Vuletic
```
Alternatively if you set `SEARCH_API_URL=https://discussions-rc.odl.mit.edu/api/v0/search/` you should see salutations for only "Classical Mechanics"
=> remove default salutation from search

base-theme/assets/css/header.scss, base-theme/layouts/partials/header.html, course/layouts/partials/extraheader.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/32
In porting over `ocw-www` and `ocw-course-hugo-theme` into this repo, the search icon at the top of course pages was lost.  This PR adds it back in.
- Spin up any course using `npm run start:course` (if you're unsure how to do this, check out the readme)
- Verify that the search icon appears in the header and the link points to `/search` (it will not work when you click it locally)
- Start up the OCW home page using `npm start` and verify that the search icon does not appear on the home page or the search page
=> restore search icon

www/assets/css/home.scss, www/layouts/partials/home_course_cards.html, www/layouts/partials/promo-carousel.html
Fixes https://github.com/mitodl/ocw-www/issues/100
Makes some accessibility changes to the carousel:
- fade in and out instead of scroll
- left and right buttons at the side
- no autoscrolling
Try out the promo carousel on the homepage. You may want to checkout https://github.com/mitodl/ocw-www/pull/115 for ocw-www first to have alt text for the images. 
- Nothing should animate automatically. When you trigger an animation, it should end after a couple seconds and stay inanimate until you trigger it explicitly again. 
- You should see a fade transition effect instead of seeing cards animate to the side.
- You should be able to tab between the left and right buttons and press enter to activate them. You should not be able to activate the carousel indicator buttons at the bottom with a …
=> Accessibility changes for carousel

course/assets/css/tables.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/38
At some point, our responsive table styling was broken. Previously, it had been applied to elements with a class of table using `.table`, which should be applied by bootstrap. This doesn't seem to work anymore, and it makes more sense to apply to all table elements anyway by specifying `table`
- Spin up any course with a table, like `18-s191-introduction-to-computational-thinking-fall-2020`'s course materials section
- View the table and reduce the size of your browser window to mobile size, verify that the mobile style is applied.
=> fix responsive tables

course/assets/css/tables.scss, course/layouts/partials/course_info.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/43
In https://github.com/mitodl/ocw-hugo-themes/pull/24, some CSS / JS was added to force the mobile table style on tables that exceed the width of the main content area.  I mistakenly thought that https://github.com/mitodl/ocw-hugo-themes/issues/43 would be fixed by this because of another bug that was present.  This PR forces the course info table to never have the `mobile-table` class applied to it.
- Spin up any course by reading the readme and using `npm run start:course`
- Visit the course home page and expand the course info drawer, ensure that there are no borders on the table
- Reduce your browser to mobile width and ensure that the course info table does not have any borders on it
=> fix course info table

base-theme/layouts/partials/head.html, course/layouts/course/baseof.html, course/layouts/partials/extrahead.html, course/layouts/partials/title.html, www/layouts/partials/extrahead.html, www/layouts/partials/title.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/40
In the transition to `ocw-hugo-themes`, page titles were broken.  This PR introduces some changes that fix rendering of titles on a number of pages listed in the issue attached to this PR.  The title was being sourced from `title.html` in `base-theme`.  The reason this was happening was because `head.html` directly calls it, which is directly called by `baseof.html` all in the `base-theme`.  When you include a partial of the same name in two themes, the first one found is used.  Instead of calling the partial directly, head.html now has a block called `title` that is implemented in `extrahead.html` in both `www` and `course`.
- Read the readme to learn how to setup this project to run `ocw-www` with the `EXTERNAL_SITE_PATH` …
=> fix title tag generation

course/layouts/course/baseof.html, www/assets/css/search-filter.scss, www/assets/js/components/SearchBox.js, www/assets/js/components/SearchFacetItem.js, www/assets/js/components/SearchPage.js, www/assets/js/components/SearchResult.js, www/layouts/search/section.html
Part of https://github.com/mitodl/ocw-www/issues/107
- Wrap search cards in `article` for `aria-feed` compatibility
- Add `aria-busy` attribute to communicate when loading happens
- Add `label` to facets and handle link clicks there instead of the surrounding div
- Remove incorrect aria roles
Nothing should appear to function differently. In particular you should be able to click the facet labels and also tab between facet checkboxes and trigger them with your spacebar.
I tried these changes using the ScreenReader plugin for Chrome and it didn't appear to make things function better. The aria-feed related changes described in the linked issue might be unimplemented in that screenreader.
=> Accessibility improvements for search

www/layouts/home.html, www/layouts/partials/newsletter_signup.html
Part of https://github.com/mitodl/ocw-www/issues/103
Adds `aria-label` attributes to two input fields so they have a label readable by screenreaders
Verify that there is an `aria-label` attribute on the search and email text fields
=> Add labels for a couple input fields

course/assets/css/course-home.scss, course/layouts/course/course_home.html, course/layouts/partials/course_features.html, course/layouts/partials/other_versions.html, package.json, yarn.lock
Closes https://github.com/mitodl/ocw-to-hugo/issues/273
In https://github.com/mitodl/ocw-data-parser/pull/74 and subsequently https://github.com/mitodl/ocw-to-hugo/pull/283, data relating to other versions of a given OCW course has been collected and organized. This PR adds a new partial to the course home page that uses that data to display other versions of a given OCW course, if they exist.
- Follow the testing instructions in https://github.com/mitodl/ocw-to-hugo/pull/283 to generate markdown for the 3 physics courses listed there
- Follow the readme in this project to get started with it if you have not spun up anything locally before
- Clone `ocw-www` and ensure the following settings are in your .env, replacing paths with your own:
```
EXTERNAL_SITE_PATH=/path/to/Code/ocw-www …
```
=> other versions

course/layouts/partials/other_versions.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/57
Recently, support for "other OCW versions" was added.  Something was missed and a course not having any other versions is resulting in just the title for that section being rendered.  This PR checks the length of the `other_versions` param before rendering the section.
- Clone `ocw-to-hugo` and read the readme if you haven't used it before
- Place the following in `private/courses.json` in `ocw-to-hugo`:
```
{
"courses": [
"8-01sc-classical-mechanics-fall-2016",
"8-01l-physics-i-classical-mechanics-fall-2005",
"8-01x-physics-i-classical-mechanics-with-an-experimental-focus-fall-2002",
"21h-244j-imperial-and-revolutionary-russia-culture-and-politics-1700-1917-fall-2019"
]
}
```
- Back over in `ocw-course-hugo-themes`, make sure you …
=> check length before rendering

www/assets/css/home.scss
Fixes https://github.com/mitodl/ocw-www/issues/102
Adds 12px padding to the left of search box
Look at home page and enter some text in the search textbox
=> Add padding to search textbox

www/assets/js/components/SearchPage.js, www/assets/js/components/SearchResult.js
Part of https://github.com/mitodl/ocw-www/issues/107
Some small tweaks to fix lighthouse warnings:
- Adjust `aria-posinet` to start at `1`, not `0`
- Add `tabIndex={0}` to allow selecting the card
- Simplify id and remove spaces so it can be used in `aria-labelledby`
The keyboard navigation implemented in [this example](https://w3c.github.io/aria-practices/examples/feed/feedDisplay.html) seems to be implemented via javascript so I'm not sure what we can or should do here
=> Tweaks to search accessibility page

www/layouts/home.html
Part of https://github.com/mitodl/ocw-www/issues/103
Fixes a header element accessibility warning I missed in the previous PR. The padding is adjusted a few pixels, similar to the "stay connected with ocw' title.
Look at home page. If you run lighthouse via Chrome (in the inspection tools) and look under "Accessibility" you should not see a warning for header elements. If you do that on `main` you should see one warning for the header element here.
=> Switch to div for subscribe title

course/layouts/course/course_home.html, course/layouts/partials/other_versions.html, package.json, yarn.lock
https://github.com/mitodl/ocw-to-hugo/issues/291
In https://github.com/mitodl/ocw-to-hugo/pull/292, `other_versions` was moved into the course data template, `course.json`.  This PR updates `ocw-hugo-themes` to reflect that change and updates the version of `ocw-to-hugo` used.
- Make sure your `OCW_TO_HUGO_PATH` variable is blank so `ocw-hugo-themes` uses the version from NPM
- Run `yarn install` to install the latest version
- Spin up a course with other versions, like `8-01sc-classical-mechanics-fall-2016`
- Ensure that the site spins up without errors and that the other versions are listed on the course home page.
=> other versions to data template

www/assets/css/home.scss, www/assets/css/learning-resource-card.scss, www/assets/js/components/SearchPage.js, www/assets/js/components/SearchResult.js
Part of https://github.com/mitodl/ocw-www/issues/107
Mark search section as search landmark and set aria-live=polite so screenreaders notice changes to the feed
I'm not sure how to test the accessibility changes since I don't have a screenreader except the plugin for Chrome which seems low quality. When the page refreshes it only reads off the number of search results. Getting to scroll through the search results is also difficult. But you can look at the source and verify that the HTML has been changed, and read the accessibility docs on the aria [search](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role) role and [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) regions.
The color in search result cards has …
=> Add search role and mark search area with aria-live

course/assets/css/course-home.scss, course/layouts/course/course_home.html, course/layouts/partials/open_learning_library_versions.html, package.json, yarn.lock
https://github.com/mitodl/ocw-data-parser/issues/53
In https://github.com/mitodl/ocw-to-hugo/pull/296, we added `open_learning_library_versions` to the course data template.  This PR adds a partial template for rendering them and implements it on the course home page.
- Clone `ocw-to-hugo` and read the readme for it and `ocw-hugo-themes` if you have not used these repos before
- In the `ocw-to-hugo` directory, put the following in `private/courses.json`:
```
{
"courses": [
"8-01sc-classical-mechanics-fall-2016",
"8-01l-physics-i-classical-mechanics-fall-2005",
"8-01x-physics-i-classical-mechanics-with-an-experimental-focus-fall-2002"
]
}
```
- Convert the courses using: `node . -i private/input -o private/output --courses private/courses.json --download --rm`
- Back in `ocw-hugo-themes`, …
=> open learning library

www/content/search/_index.md
Closes https://github.com/mitodl/ocw-hugo-themes/issues/95
In `ocw-www`, we currently have a file at `content/search/_index.md` with the following contents:
```
---
title: Search
type: search
---
```
Its purpose is to tell Hugo to render a page at `/search/index.html` using the layout at `layouts/search/section.html`.  This PR moves this file into the theme, so the search page is rendered at `/search/index.html` by default.
- Read the readme if you've never used this project before
- Clone `ocw-www` on the `cg/remove-search-placeholder` branch and point at it using `EXTERNAL_SITE_PATH`
- Start the site with `npm start`
- View the search page at `http://localhost:3000/search.  You will not see any search results unless you've configured `ocw-studio` to return them, but the goal here is to …
=> add search placeholder

base-theme/assets/webpack/webpack.common.js, base-theme/assets/webpack/webpack.dev.js, base-theme/assets/webpack/webpack.prod.js, base-theme/layouts/partials/head.html, build_scripts/build.sh
Closes https://github.com/mitodl/ocw-hugo-themes/issues/97
This PR cleans up the output of the webpack build and organizes it into folders.  All assets are placed in a `static` folder, and then organized into folders by file type beyond that.  External dependencies like Mathjax still go into their own folder under `static`.
- Read the readme if you have never run a site locally before using `ocw-hugo-themes`
- Clone `ocw-www`
- Point `EXTERNAL_SITE_PATH` to `ocw-www` and run `npm start` to start `ocw-www`
- Open the inspector in your browser and verify that all assets load correctly and there are no 404's
- Verify that the paths to the various assets on the page are prefixed in the manner described above
- Stop the site and run `npm run build:webpack`
- Inspect the contents of …
=> reorganize webpack output

course/layouts/course/course_home.html, course/layouts/partials/archived_versions.html, package.json, yarn.lock
Part of https://github.com/mitodl/ocw-to-hugo/issues/274
Shows archived courses on the home page. You will need to run this using ocw-to-hugo data from https://github.com/mitodl/ocw-to-hugo/pull/301, which itself relies on ocw-data-parser output from https://github.com/mitodl/ocw-data-parser/pull/145 (both have been merged to master).
After generating fresh data via ocw-data-parser and ocw-to-hugo for all courses, view the course home page for `17-40-american-foreign-policy-past-present-and-future-fall-2017`.
=> Show archived versions on course home page

package.json, www/assets/js/components/SearchPage.js, www/assets/js/components/SearchPage.test.js, www/assets/js/lib/search.js, www/assets/js/lib/search.test.js, yarn.lock
Fixes https://github.com/mitodl/course-search-utils/issues/21
Implements sort for courses. There are two options at the moment: "Relevance" and "MIT course nr"
- Make sure you have the course index updated. If you haven't, you will need to rebuild the docker container on open-discussions to get the latest version of `ocw-data-parser`, then run `./manage.py recreate_index --course`. 
- Go to `/search` and click the sort dropdown, then change to "MIT course nr". When you switch to "MIT course nr" you should see a `s=coursenum` parameter appear in the URL. The search results should appear to sort by course number.
- You should be able to switch back and forth between "MIT course nr" and "Relevance" and see expected results. The text and facets should remain when you switch sorting.
- If you …
=> Implement sort

www/assets/js/components/SearchPage.js, www/assets/js/lib/search.js, www/assets/js/lib/search.test.js
Fixes #111
Adds an option to sort by best_start_date, descending
Go to `/search` and switch between different sort options. For `Date` it may or may not be obvious that earlier courses are first but you can see the dates in the network tab in the API response, or hover over the URL and look at the semester in the URL. The dates should be in descending order.
=> Add sorting by date

base-theme/layouts/partials/notification.html, www/archetypes/notifications.md
Closes https://github.com/mitodl/ocw-hugo-themes/issues/121
In an effort to build `ocw-www` content generated by `ocw-studio`, it was noticed that the partial for `notification` in the `www` theme looks for an identifier in the `id` property of the front matter of the notification.  This `id` is currently a Unix timestamp generated at the time of the creation of the file if you are using the `hugo new` syntax as defined in the archetype in the `www` theme for `notification`. `ocw-studio` doesn't use `hugo new` to create content and instead generates content based the `WebsiteStarter` config used to generate the site.  `ocw-studio` however does generate a UUID for each piece of content it creates, and this is deposited in the front matter of any given piece of content under the `uid` key. …
=> use uid instead of id for notifications

course/assets/course.js, course/assets/js/course_expander.js, course/assets/js/course_expander.test.js, course/layouts/course/course_home.html, course/layouts/partials/course_info.html
Fixes #104 
Fixes the course info expander
Start the server on course `6-00sc-introduction-to-computer-science-and-programming-spring-2011`. You should be able to toggle the "Course info >" link and also the "Read More" link. Both links should toggle correctly to expand the course info or course description sections.
=> Fix course info expander

.github/workflows/deploy.yml, www/layouts/partials/home_testimonials.html, www/layouts/partials/promo-carousel.html, www/layouts/partials/resource_url.html, www/layouts/partials/testimonial_card.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/125
In mitodl/ocw-hugo-projects#8, we set up the `ocw-www` studio config to have a collection of resources with uploaded files and metadata. Now that we are moving to source `ocw-www` content from `ocw-studio`, we will need to update the way we source image URLs for promos and testimonials to reflect this change. Currently, in the static version of `ocw-www` at https://github.com/mitodl/ocw-www we simply store the image URL under the image front matter property and the alt text in image_alt.
This PR adds the `resource_url.html` partial to the `www` theme.  It takes two arguments, the first being `filetype` and second being `uid`.  The partial retrieves a resource by first filtering the resources by `filetype` and then matching on …
=> adapt to use ocw-studio generated ocw-www content

course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html, package.json, yarn.lock
Fix error where a course, for example, "1-050-solid-mechanics-fall-2004", has youtube video as an introduction to the course, and using youtube shortcode. 
This PR updates `shortcodes/youtube.html` to pass an extra parameter the captions location.
Set the course id in the env file `OCW_TEST_COURSE=`, and run the course you are testing `npm run start:course`
There should be no errors.
=> Add captions location as an argument to youtube shortcode

package.json, yarn.lock
https://github.com/mitodl/ocw-to-hugo/issues/309 and https://github.com/mitodl/ocw-studio/issues/382
This PR updates the `ocw-to-hugo` version to 1.25.0 and releases code related to the two above issues
- If you've never used `ocw-hugo-themes` before, read the readme about how to start up a course site
- Make sure `OCW_TO_HUGO` path is not set, but configure AWS access and set `OCW_TEST_COURSE` to any course
- Run `yarn install` and then spin up any course using `npm run start:course`
- Ensure there are no errors and the course site spins up at http://localhost:3000
=> update ocw-to-hugo to 1.25.0

course/assets/course.js, course/layouts/partials/youtube_player.html
Fix #142 
There are three ways to pass options to Video.js.  We are using the data-setup attribute to trigger the player setup, so no need to pass it to videojs function.
There should be no errors
=> Don't initialize the video player setup

course/layouts/partials/course_info.html, course/layouts/partials/course_instructor_number.html, course/layouts/partials/other_versions.html, package.json, yarn.lock
Related to:
- https://github.com/mitodl/ocw-to-hugo/issues/317
- https://github.com/mitodl/ocw-hugo-projects/issues/25
In https://github.com/mitodl/ocw-to-hugo/pull/318, we changed the way `ocw-to-hugo` renders course numbers in the data template.  Instead of being in one `course_numbers` array, the numbers were broken out into `primary_course_number` and `extra_course_numbers`.  This PR adjusts the theme templates to account for that change and updates the version of `ocw-to-hugo` to match.
- Read the readme if you have never used `ocw-hugo-themes` to spin up a course site locally before and make sure you have AWS S3 access configured
- Make sure `OCW_TO_HUGO_PATH` is blank in your `.env` file, and set `OCW_TEST_COURSE` to `2-00aj-exploring-sea-space-earth-fundamentals-of-engineering-desi …
=> separate primary course number and extra course numbers

www/layouts/partials/home_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/147
In https://github.com/mitodl/ocw-studio/pull/423, we updated `ocw-studio` to use `primary_course_number` and `extra_course_numbers` instead of `course_numbers`.  The `course_numbers` array was separated out into primary and extra course numbers in https://github.com/mitodl/ocw-to-hugo/pull/318.  This PR adjusts the `home_course_cards.html` partial template to adjust for the `ocw-studio` API returning the new structure.
- Clone https://github.com/mitodl/ocw-www
- Set up `ocw-hugo-themes` to run locally (read the readme) and point `EXTERNAL_SITE_PATH` at your locally cloned `ocw-www`
- Set `OCW_STUDIO_BASE_URL=http://ocw-studio-rc.odl.mit.edu`
- Run the site with `npm start`
- Visit the site at http://localhost:3000 and verify that …
=> use primary_course_number on home_course_cards partial

course/layouts/course/course_home.html, package.json, yarn.lock
Closes https://github.com/mitodl/ocw-hugo-themes/issues/150
In mitodl/ocw-to-hugo#323, we moved the course description from the course home page's markdown body to the course data template under the course_description property. This PR adjusts the course home template to source the course description from the new `course_description` property in the data template, passing it through `markdownify` as it is expected that it will be a markdown string.
- Read the readme if you have never run a course site locally before
- Make sure `OCW_TO_HUGO_PATH` and `OCW_TO_HUGO_OUTPUT_DIR` are blank in your `.env`, and `OCW_TEST_COURSE` is set to any course ID
- Run `yarn install`
- Run `npm run start:course`
- Verify that the course site is available at http://localhost:3000 and that the course …
=> course description from data template

package.json
Releases https://github.com/mitodl/ocw-to-hugo/issues/325
This PR updates `ocw-to-hugo` to 1.27.0, which includes fixes for unrendered shortcodes appearing in the course description after the transition to storing it in the course data template.
- Read the readme if you have never used `ocw-hugo-themes` to spin up a course site locally before and make sure you have AWS S3 access configured
- Make sure `OCW_TO_HUGO_PATH` is blank in your `.env` file, and set `OCW_TEST_COURSE` to `12-000-solving-complex-problems-fall-2003`
- Run `yarn install` to install the latest `ocw-to-hugo`
- Run `npm run start:course` and ensure that the site builds without error
- Visit http://localhost:3000 and ensure that the course site renders and you can click the links in the course description
=> update ocw-to-hugo to 1.27.0

course/layouts/course/baseof.html, course/layouts/course/course_home.html, course/layouts/partials/archived_versions.html, course/layouts/partials/course_banner.html, course/layouts/partials/course_features.html, course/layouts/partials/course_info.html, course/layouts/partials/course_instructor_number.html, course/layouts/partials/open_learning_library_versions.html, course/layouts/partials/other_versions.html, course/layouts/partials/topics.html, course/layouts/partials/topics_oneline.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/154
In our move to building sites with content generated by `ocw-studio`, `course_id` will no longer be set on the front matter of every page or in the course data template.  Since it is no longer necessary to build a course site, references it it have been removed in this PR.
- Read the readme if you've never spun up a course locally before
- Spin up any course and ensure it does so without error
- Browse to the course and ensure that you can click around to the different sections
=> remove references to course_id in front matter and the data template

www/layouts/partials/home_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/161
In https://github.com/mitodl/ocw-to-hugo/pull/244, the `level` property was changed to an object containing the text of a level as well as a search URL.  The `home_course_cards.html` template was never adjusted to match this, and instead of displaying the level, it's displaying a string representation of the level object.  This PR adjusts the template to generate a link to the search URL using the data contained in the object.
- Read the readme if you've never spun up `ocw-wvw` before using `ocw-hugo-themes`, you'll need to clone https://github.com/mitodl/ocw-www and point to it using `EXTERNAL_SITE_PATH`
- Spin up `ocw-www` using `npm start`
- Verify that the `level` links on the course home cards are clickable links that take …
=> use level text and search url

base-theme/layouts/_default/baseof.json.json, base-theme/layouts/_default/single.json.json, www/layouts/instructor/item.json.json
https://github.com/mitodl/ocw-hugo-themes/issues/166
In https://github.com/mitodl/ocw-studio/pull/518, we set up `ocw-studio` to publish instructors imported from `ocw-to-hugo` output so markdown files are created for each one when publishing `ocw-www`.  This PR adds JSON templates to the base and www themes that will tell Hugo to render JSON files for content with `type: instructor`.  In the resulting site, you will have a static API that can be queried for instructor information.
- Read the readme if you've never worked with `ocw-hugo-themes` before
- Spin up the webpack dev server locally by running `npm run start:site:webpack`
- Clone https://github.com/mitodl/ocw-hugo-projects on the `cg/json-media-types` branch
- Clone https://github.mit.edu/ocw-content-rc/ocw-www/ and open a …
=> add templates to render instructor static JSON API responses

course/layouts/partials/youtube_player.html
Fixes #163 
Removes the autoplay attribute from the video element to disable autoplay
I don't have access to a Safari browser but if you do you can view /courses/5-112-principles-of-chemical-science-fall-2005/sections/video-lectures/lecture-2-discovery-of-nucleus/ for example and see if the video autoplays
=> Disable autoplay

www/layouts/partials/home_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/175
In https://github.com/mitodl/ocw-to-hugo/pull/331, we made some adjustments to the `ocw-to-hugo` output to more closely match published content from `ocw-studio`.  One of these changes was removing the `course_id` property that was deposited in the course data template and all pages' front matter.  Since `ocw-studio` imports legacy OCW courses by consuming `ocw-to-hugo` output, this change was imported into `ocw-studio` and `course_id` is now not present in the API results.  This PR changes calls to `course_id` in the `home_course_cards.html` layout to instead get this value from `name`, where the same value is stored as the slug of the `Website` object in `ocw-studio`
- Read the readme before if you have never spun up `ocw-www` …
=> fix home course card links

build_scripts/build.sh, build_scripts/build_all_courses.sh, build_scripts/common.sh, build_scripts/import_courses.sh, build_scripts/prep_external_site.sh, build_scripts/start_course.sh, build_scripts/start_site.sh
closes #178 
two things:
- allow use of `#` to comment out lines in a `.env` file
- write a single function for sourcing `.env` which can be called in all of our bash scripts in this repo
I think try a few things:
- ensure all functionality works as normal with your standard `.env` file
- add a commented line to it and ensure it still works as well
- delete `.env` and ensure that build scripts still fail on `env file not found` NOT on trying to access a variable. i.e. if you want add an `echo` statement just after the line where we call `source_env` in one of the build scripts and ensure that that line doesn't execute.
those are the main things I think.
=> allow comments in .env, put .env sourcing in one place

course/layouts/partials/course_feature.html
Fixes #182 
Adjusts the template code for course feature links to handle joining the baseurl to links without prefix slashes 
Convert a course with feature links using https://github.com/mitodl/ocw-to-hugo/pull/342 and run `npm run build:course` using that course. The links should work properly, on the course home page or any other page. 
This PR should also work with courses not converted by https://github.com/mitodl/ocw-to-hugo/pull/342 so that it can be merged without blocking anything
=> Add joining slash if none exists to course feature urls

course/layouts/partials/course_info.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/195
In https://github.com/mitodl/ocw-hugo-themes/pull/186 we altered how instructors are sourced, pulling their data from a static JSON API.  Unfortunately, the array of UUID's being empty was not considered and breaks the build.  This PR adds a check to make sure the array is not empty.
- Read the readme if you've never spun up a course site locally before and make sure you have S3 access to RC set up
- Set `OCW_TEST_COURSE` to `iit-jee`
- Run `npm run start:course`
- The course site should spin up without errors, although there will be missing data and the "course" will have no sections
=> check instructors before use

course/layouts/partials/course_info.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/199
In https://github.com/mitodl/ocw-hugo-themes/pull/196, we utilized the `with` statement to only process instructors if they exist.  An issue with this was missed where since the context is being rebound with in the `with` statement, `.inPanel` is invalid because it doesn't exist in the redefined context.  This PR sets the partial call to use the locally defined `$inPanel` variable within the course info partial.
- Read the readme if you've never spun up a course site locally before, and make sure you have S3 access to RC set up
- Make sure `OCW_TEST_COURSE` is set to a valid course (I used `18-06-linear-algebra-spring-2010`) and make sure `OCW_TO_HUGO_PATH` is blank
- Run `yarn install` to make sure you have the latest …
=> fix inpanel

course/layouts/partials/topic.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/201
In https://github.com/mitodl/ocw-hugo-themes/pull/193, we updated the topics partial to be compatible with the updated structure in the latest version of `ocw-to-hugo` that was set up to match the published output of `ocw-studio`.  This PR fixes a bug introduced there where if subtopics are not set, there will be an error caused by calling `len` on them.  It's fixed by defaulting the local variable to an empty slice.
- Read the readme if you've never spun up a course site locally before, and make sure you have S3 access to RC set up
- Make sure `OCW_TEST_COURSE` is set to `10-01-ethics-for-engineers-spring-2020` and make sure `OCW_TO_HUGO_PATH` is blank
- Overwrite `course/layouts/partials/course_info.html` with …
=> default subtopics to an empty slice

www/layouts/partials/topics_summary.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/206
In https://github.com/mitodl/ocw-to-hugo/pull/370, we changed the way `ocw-to-hugo` outputs topics to match the way `ocw-studio` publishes them using the `ocw-course` starter configuration.  This PR adjusts the rendering of `topics_summary.html` to reflect these changes.
- Read the readme if you've never used `ocw-hugo-themes` to spin up `ocw-www` locally before
- Clone https://github.com/mitodl/ocw-www and point to it in your `.env` with `EXTERNAL_SITE_PATH`
- Make sure you have `OCW_STUDIO_BASE_URL=http://ocw-studio-rc.odl.mit.edu/` in your `.env` as well
- Run `npm start`
- Verify that the OCW home page is available at http://localhost:3000, noting that course images on the cards will not be available.  Verify that topics are …
=> fix home course cards topics

package.json, yarn.lock
Related to https://github.com/mitodl/ocw-to-hugo/pull/375
Upgrades ocw-to-hugo to fix a typo bug
I don't think you would see any changes here regarding this bug. It only affects ocw-studio's import at the moment
=> Update ocw-to-hugo to fix typo bug

README.md, base-theme/layouts/partials/resource_url.html, course/layouts/home.html, package.json, www/layouts/partials/resource_url.html, yarn.lock
Closes https://github.com/mitodl/ocw-hugo-themes/issues/211
In https://github.com/mitodl/ocw-to-hugo/pull/378, we altered the rendering of `course.json` to produce an `ocw-studio`-like reference to the course image resource content by UUID.  This PR updates the version of `ocw-to-hugo` in `package.json` and adjusts the theme to source images from the content in this manner:
- `resource_url.html` was moved to `base-theme`
- `resource_url.html` was set up to look for a URL in `.Params.file` first, but fall back to `.Params.file_location` because this is where `ocw-to-hugo` currently puts this property in converted legacy resources
- An optional `RESOURCE_BASE_URL` env variable was added that will prefix resource URLs rendered in this partial with the value supplied. This way, when you are …
=> course images from resources

base-theme/assets/css/main.scss, course/assets/css/resource-page.scss, course/layouts/partials/video.html, course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/209
This pr adds a download button for the pdf transcript for videos
run `node . -i private/input -o private/output -c course_json_examples/example_courses.json --download` in ocw-to-hugo branch https://github.com/mitodl/ocw-to-hugo/pull/382
Run `npm run start:course` in this PR with `OCW_TEST_COURSE=15-401-finance-theory-i-fall-2008` (or another course with video lecture pages). Go to a video page. Verify that you see a transcript download button under the video and you can download the transcript. Also verify that you can turn on captions for the video.
Run `npm run start:course` in this PR with `OCW_TEST_COURSE=15-071-the-analytics-edge-spring-2017` (or another course with embedded youtube videos). Go to a page with an embedded …
=> download transcript theme

course/layouts/home.html, package.json, yarn.lock
Closes https://github.com/mitodl/ocw-hugo-themes/issues/217
In https://github.com/mitodl/ocw-to-hugo/pull/386, we fixed a bug where `ocw-to-hugo` would render the course image content as a list with a single UUID, rather than just a single string.  Since `ocw-studio` defines this as a 1 to 1 relationship, it isn't rendered as a list.  This PR updates the version of `ocw-to-hugo` to point at 1.32.0 and makes the necessary changes to the template to source the image URLs properly.
- Read the readme if you've never spun up a course site locally before and make sure you're set up to download content from S3
- Ensure that in your `.env`, `OCW_TO_HUGO_PATH` is omitted or set to blank, `RESOURCE_BASE_URL` is set to https://open-learning-course-data-rc.s3.amazonaws.com/ and `OCW_TEST_COURSE` is …
=> fix course image

base-theme/assets/css/main.scss, course/assets/css/resource-page.scss, course/layouts/partials/video.html, course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/209
This pr adds a download button for the pdf transcript for videos
run `node . -i private/input -o private/output -c course_json_examples/example_courses.json --download` in ocw-to-hugo branch https://github.com/mitodl/ocw-to-hugo/pull/382
Run `npm run start:course` in this PR with `OCW_TEST_COURSE=15-401-finance-theory-i-fall-2008` (or another course with video lecture pages). Go to a video page. Verify that you see a transcript download button under the video and you can download the transcript. Also verify that you can turn on captions for the video.
Run `npm run start:course` in this PR with `OCW_TEST_COURSE=15-071-the-analytics-edge-spring-2017` (or another course with embedded youtube videos). Go to a page with an embedded …
=> download transcript theme (unrevert)

base-theme/layouts/partials/resource_url.html, course/layouts/partials/video_embed.html, course/layouts/shortcodes/resource.html
Fixes #221 
Implements simple resource embeds
- Go to RC and publish two courses to staging. I chose `18-06-linear-algebra-spring-2010` for the video embed and `1-011-project-evaluation-spring-2011` for the PDF and image resources, but feel free to pick any course that's applicable. I already added resource embeds in these two courses, but feel free to make modifications.
- Go to github.mit.edu/ocw-course-rc and download the courses, and unzip them in a temporary directory
- Point ocw-hugo-themes to the temporary directory, and delete `Title` from the `menu.yaml` file to workaround a bug
- Point to `18-06-linear-algebra-spring-2010` and go to `/pages/test-page-2`. You should see the image and PDF resource embeds. Verify that the markdown contains two `resource` markdown elements. The …
=> Implement simple resource embed

course/assets/course.js, course/assets/css/course.scss, course/assets/css/video-transcript.scss, course/assets/js/navigation.js, course/assets/js/video_transcript_track.js, course/layouts/partials/video.html, course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html, package.json, yarn.lock
https://github.com/mitodl/ocw-hugo-themes/issues/210
This pr adds a div with caption text under videos. The caption corresponding to the current point in the video should be highlighted. Also, the user should be able to select a caption and have the video update to that point.
Run `npm run start:course` with a course that has (non-inline) lecture videos for example set `OCW_TEST_COURSE=15-401-finance-theory-i-fall-2008` in your .env file.
Go to a lecture video. Verify that you see a box with captions and the captions look good
=> show transcripts under video

www/assets/js/lib/search.js, www/assets/js/lib/search.test.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/233
In https://github.com/mitodl/ocw-to-hugo/pull/331, we altered the output of `ocw-to-hugo` to write the different sections of a course to the `content/pages` folder to match how `ocw-studio` publishes content.  Moving forward, content published to OCW sites will follow the patterns described in the starter configurations (`ocw-studio.yaml`) in https://github.com/mitodl/ocw-hugo-projects.  This PR adjusts the search app to prefix pages with `/pages` instead of `/sections` to match this in search results.
- Clone https://github.com/mitodl/ocw-www
- In your `.env` file, make sure `EXTERNAL_SITE_PATH` is set to the path to `ocw-www`
- Also in your `.env`, make sure `SEARCH_API_URL` is set to …
=> replace "sections" with "pages"

course/assets/css/video.scss, course/layouts/partials/video.html, course/layouts/partials/video_embed.html, course/layouts/partials/youtube_player.html, package.json, yarn.lock
https://github.com/mitodl/ocw-hugo-themes/issues/145
This PR adds links to download videos. For legacy courses these links go to internet archive. For ocw-studio courses they go to s3.
run node . -i private/input -o private/output -c course_json_examples/example_courses.json --download in https://github.com/mitodl/ocw-to-hugo/pull/397
Set  OCW_TEST_COURSE=15-071-the-analytics-edge-spring-2017
Set COURSE_CONTENT_PATH= the path to /private/output from ocw-to-hugo
Run `npm run start:course`
Go to a page with an embedded youtube video. Verify that you see a video download button under the video and the link takes you to the video file on the internet archive. Click through to a video resource page. Again, verify that you see a video download button under the video and the link takes you to …
=> Video Downloads

course/layouts/partials/course_info.html
Related to https://github.com/mitodl/ocw-to-hugo/pull/398
`level` was changed to an array so this PR changes it to output one level link per item in the array. Additionally, `term` was changed to not include a year anymore, and `year` was added with the corresponding year. 
Convert a course with the latest ocw-to-hugo and view a course with this PR. The level in the course info on the course home page should look the same as before, with a link to the search page. The text next to "As Taught In" should be a semester and a year, looking exactly like it did before
=> Adjust level, term to new ocw-to-hugo format

course/layouts/partials/video-gallery.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/252
In https://github.com/mitodl/ocw-hugo-projects/pull/93, we added a markdown description field to video galleries.  This PR adds the necessary template changes to display this content above the video gallery, if present.
- Follow the testing instructions in https://github.com/mitodl/ocw-hugo-projects/pull/93
- Confirm the changes work with an [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo) converted course with a video gallery such as `ec-711-d-lab-energy-spring-2011` from the example courses, adjusting `COURSE_CONTENT_PATH` and `OCW_TEST_COURSE` as necessary
=> render the video gallery description if set

www/layouts/partials/home_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/261
In https://github.com/mitodl/ocw-hugo-themes/pull/257, we updated the `home_course_cards.html` template to be compatible to recent changes in the structure of the `level` metadata property.  This PR missed the fact that this is now stored as an array with potentially multiple items in it.  This PR adjusts the rendering to iterate the times if it is indeed an array.
- Set `OCW_STUDIO_BASE_URL=http://ocw-studio-rc.odl.mit.edu/` in your `.env`
- Verify that the level display on the home course cards is not surrounded in square braces
=> conditionally iterate level as a map in home_course_cards

www/layouts/partials/home_course_cards.html
N/A
In https://github.com/mitodl/ol-infrastructure/pull/440, we added a pipeline definition to run `ocw-to-hugo` on its own and upload the output to the `ocw-to-hugo-output` S3 buckets for consumption by `ocw-studio`.  Since `ocw-studio` is responsible for delivering the API that renders the "new courses" section of the home page, the course image URLs have changed.  The current EC2 based build servers that deploy https://ocwnext-rc.odl.mit.edu and https://ocwnext.odl.mit.edu have a custom fastly redirect mounted at `/coursemedia` to source static material directly from the `open-learning-course-data` buckets.  Since this won't be the case when it comes to the `ocw-studio` published courses, the new `ocw-to-hugo` pipeline uses a `staticPrefix` of `/courses`.  This had the effect of …
=> add in a hack for /coursemedia

www/layouts/partials/home_course_cards.html, www/layouts/partials/home_course_cards_instructors.html, www/layouts/partials/home_course_cards_level.html, www/layouts/partials/home_course_cards_topics.html, www/layouts/partials/topics_summary.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/267
Closes https://github.com/mitodl/ocw-hugo-themes/issues/268
In https://github.com/mitodl/ocw-studio/pull/449, we modified the `ocw-studio` REST API that the `home_course_cards.html` partial uses to get new courses to serialize instructor information alongside the UUID's of the instructors.  This changed the API schema to deliver objects for instructors instead of strings, which broke their display in the partial.  This PR creates a new partial called `home_course_cards_instructors.html` that is responsible for pulling these instructors out of the response and creating clickable search links for them to go in the card.  The same was done with topics as well as level, for better organization of the different parts of the cards that …
=> update home course cards instructors, topics and level

base-theme/layouts/partials/resource_metadata.html, base-theme/layouts/partials/resource_url.html, course/layouts/home.html, course/layouts/partials/image_page.html, course/layouts/partials/pdf_viewer.html, course/layouts/partials/video-gallery-item.html, course/layouts/partials/video.html, course/layouts/partials/video_embed.html, course/layouts/resources/single.html, course/layouts/shortcodes/resource.html, package.json, www/assets/js/components/SearchResult.js, www/layouts/partials/promo-carousel.html, www/layouts/partials/testimonial_card.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html, yarn.lock
Fixes #260 
Fixes https://github.com/mitodl/ocw-hugo-projects/issues/47
Fixes #271 
Fixes the alt text and caption for the course home page, and updates some handling of resource URLs to be consistent
- First, convert `1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012` using this PR from ocw-to-hugo: https://github.com/mitodl/ocw-to-hugo/pull/409
- View the course home page for that course. You should see a caption containing "This phidget kit features one of the many tools taught in this course" under the image. 
- If you inspect the image you should see alt text like "One big and one small circuit board..."
=> Use alt-text for course image

www/layouts/partials/home_course_cards.html
None
This fixes an edge case where the number of course cards on the home page carousel is less than 10. In that case the home page breaks because of a missing div tag
Make sure the home page works as normal by running `npm run start:www`. You should see 10 carousel cards in the "new courses" section.
In `home_course_cards.html` edit `{{ $typeQuery := querify "type" $courseStarterSlug }}` to be `{{ $typeQuery := querify "search" "computational mech" }}`. On main you should see a broken home page, but on this PR you should see a single carousel card.
=> Fix calculation for course home page cards

course/layouts/shortcodes/resource_file.html
Related to https://github.com/mitodl/ocw-to-hugo/issues/352
This PR adds a new shortcode to the course theme; `resource_file`.  It allows you to get just the `file` property of a resource on its own for use in `img` `src` attributes and possibly other applications.
This PR should be tested in conjuction with https://github.com/mitodl/ocw-to-hugo/pull/412.  Follow the steps there to test both of these PR's together.
=> add the resource_file shortcode to the course theme

base-theme/layouts/partials/resource_metadata.html, base-theme/layouts/partials/resource_url.html, course/layouts/home.html, course/layouts/partials/image_page.html, course/layouts/partials/pdf_viewer.html, course/layouts/partials/video-gallery-item.html, course/layouts/partials/video.html, course/layouts/partials/video_embed.html, course/layouts/resources/single.html, course/layouts/shortcodes/resource.html, package.json, www/assets/js/components/SearchResult.js, www/layouts/partials/promo-carousel.html, www/layouts/partials/testimonial_card.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html, yarn.lock
Related to #270, #282
This adds back the work from #270, but with an updated ocw-to-hugo version which should fix issues with finding the right course image for certain courses.
See instructions in #270, but test with `11-521-spatial-database-management-and-advanced-geographic-information-systems-spring-2003` instead.
=> Revert "Revert "Use alt-text for course image (#270)""

course/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/291
In https://github.com/mitodl/ocw-hugo-themes/pull/284, we added back in some template code that pulls out the `image-alt` and `caption` properties on the course image in the course home page.  If the course image on a site isn't set, a hard error will be thrown when building the course.  This PR sets up a default value for `$courseImageMetadata` so that the build does not fail if the course image is not set.  It will simply be missing in the rendered site.
- Clone [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo) and read the readme if you've never used it before, making sure you are set up to download courses from S3
- In `ocw-to-hugo`, create a file at `private/courses.json` and place the following in it:
```
{
"courses": …
```
=> set up some defaults for the course image metadata

course/assets/css/video-transcript.scss, course/assets/js/video_transcript_track.js, course/layouts/partials/video.html, course/layouts/partials/youtube_player.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/285
Videos don't play correctly when there is more then one on a page because we have duplicate ids, which is not valid html and breaks videojs.
In  ocw-to-hugo set example_courses.json to
```
{
"courses": [
"6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016",
]
}
```
and run
```
node . -i private/input -o private/output -c course_json_examples/example_courses.json --download
```
In ocw-hugo-themes,
Set your .env to
```
OCW_TEST_COURSE=6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016
COURSE_CONTENT_PATH=/ocw-to-hugo/private/output
DOWNLOAD=0
```
Run
```
npm run start:course
```
Go to
http://localhost:3000/pages/in-class-questions-and-video-solutions/lecture-1/
Verify that you can …
=> ensure unique video id

course/layouts/_default/baseof.html, course/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/250
In https://github.com/mitodl/hugo-course-publisher/pull/155 we added support for rendering equations from legacy OCW courses containing MathML using the MathJax library.  When we created the `ocw-hugo-course` and `ocw-www` repos, then subsequently created `ocw-hugo-themes`, we broke the loading of this library.  In https://github.com/mitodl/ocw-hugo-themes/pull/98, we made sure that all static resources built by webpack are placed in the `static` folder.  This PR simply changes the call to the MathJax `tex-svg.js` file to be properly sourced from this folder.
- Clone [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo) and ensure that you are set up to download courses from AWS
- Place the following in …
=> Fix MathJax Javascript URL

course/layouts/index.coursedata.json
https://github.com/mitodl/ocw-hugo-themes/issues/300
This pr generates a new course_data.json file for each course in ocw-hugo-themes. This data is available at /course_data.json
checkout https://github.com/mitodl/ocw-hugo-projects/pull/107 in ocw-hugo-projects
Set your .env to 
COURSE_HUGO_CONFIG_PATH=<path>/ocw-hugo-projects/ocw-course/config.yaml
Run ocw-to-hugo for any legacy course and set COURSE_CONTENT_PATH and OCW_TEST_COURSE to point to the data.
Run `npm run start:course`, verify that you can go to http://localhost:3000/course_data.json and the data looks good
Create a course through ocw-studio. Clone the git directory of the studio course from https://github.mit.edu/ocw-content-rc.
Set COURSE_CONTENT_PATH and OCW_TEST_COURSE to point to the course data from github.
Run `npm run …
=> add course_data.json

course/layouts/index.coursedata.json
None
We saw the following error when deploying to RC
```
Running hugo on courses in /opt/ocw/ocw-to-hugo/private/output...
Error: Error building site: failed to render pages: render of "home" failed: "/opt/ocw/ocw-hugo-themes/course/layouts/index.coursedata.json:4:19": execute of template failed: template: index.coursedata.json:4:19: executing "index.coursedata.json" at <partial "get_instructors.html" $courseData.instructors.content>: error calling partial: partial that returns a value needs a non-zero argument.
```
this fixes the issue
Run `npm run start:course` for any course. You will need to set COURSE_CONTENT_PATH and OCW_TEST_COURSE in your .env file. You should be able to go to http://localhost:3000/course_data.json and see the course data.
Go to the source in COURSE_CONTENT_PATH. …
=> fix instructors

course/layouts/index.coursedata.json
We saw the following error when deploying to RC
```
Running hugo on courses in /opt/ocw/ocw-to-hugo/private/output...
Error: Error building site: failed to render pages: render of "home" failed: "/opt/ocw/ocw-hugo-themes/course/layouts/index.coursedata.json:4:19": execute of template failed: template: index.coursedata.json:4:19: executing "index.coursedata.json" at <partial "get_instructors.html" $courseData.instructors.content>: error calling partial: partial that returns a value needs a non-zero argument.
```
We still saw the error after yesterday's fix. This hopefully fixes the issue
Run `npm run start:course` for any course. You will need to set COURSE_CONTENT_PATH and OCW_TEST_COURSE in your .env file. You should be able to go to http://localhost:3000/course_data.json and see the …
=> fix instructors error take 2

base-theme/assets/css/header.scss, base-theme/layouts/partials/header.html, course/layouts/partials/extraheader.html
https://github.com/mitodl/ocw-hugo-themes/issues/26
Adds sandwich menu for mobile devices with appropriate links.
- This PR is deployed [here](https://ocw-hugo-themes-pr-310--ocw-next.netlify.app)
- Verify that sandwich icon shows up for tablets and mobiles devices (devices having width 991 px or less)
- Verify that sandwich icon shows menu when clicked.
- Verify that all the links shown are working.
- search box (in ocw-course only)
-  Give link
- about link
- help & faq link
- contact us link
- Repeat the above steps with multiple browsers.
- Mobile navbar - closed (for both, ocw-www and ocw-course)
---------------------------------------------
- ocw-www: 
- Navbar for Desktop/laptop: 
- ocw-www: 
- Navbar for Mobile: 
---------------------------------------------
- ocw-course:
- Navbar …
=> feat: menu (sandwich) for mobile devices

www/assets/js/subnav.js
None
For mobile, When user clicks any subnav item, on about page or educator page, the smooth scroll do not stop at the start of the section, instead it goes a bit down. This PR fixes this issue.
- Go to about us or educator page on mobile 
- Open the on-page sub navbar and click on any menu item.
- Verify that smooth scroll stops at the beginning of the section
Before: 
After:
=> fix: subnav scroll going a bit down

www/assets/css/home.scss, www/layouts/home.html
Closes #89 
- Replaces span with h1 tag for accessibility reasons.
- Changed color of arrow icons to resolve light house issues.
Running lighthouse tests and verifying the score should be enough.
=> Fixed lighthouse accessibility issues

base-theme/assets/css/header.scss, www/assets/css/home.scss
Closes #321 
Updated header size and spacing to insure `Unlocking...` box does not overflow
- Verify that on multiple screen widths the `Unlocking...` box does not overflow hero image
=> fixed issue regarding box overflow

course/layouts/_default/baseof.coursedata.json, course/layouts/_default/section.coursedata.json, course/layouts/pages/single.coursedata.json, course/layouts/partials/course_content.json, course/layouts/partials/video-gallery-page.json, course/layouts/resources/single.coursedata.json, course/layouts/video_galleries/single.coursedata.json
https://github.com/mitodl/ocw-hugo-themes/issues/300
This pr generates a new data.json file for each course page or resource. This data is available by appending /data.json to any course url
https://github.com/mitodl/ocw-hugo-projects/pull/110 in ocw-hugo-projects
Set your .env to 
COURSE_HUGO_CONFIG_PATH=<path>/ocw-hugo-projects/ocw-course/config.yaml
Run ocw-to-hugo for any legacy course and set COURSE_CONTENT_PATH and OCW_TEST_COURSE to point to the data.
Run `npm run start:course`, verify that you can append ``/data.json`` to course urls to get the json representation and the data looks good
Create a course through ocw-studio. Clone the git directory of the studio course from https://github.mit.edu/ocw-content-rc.
Set COURSE_CONTENT_PATH and OCW_TEST_COURSE to point to the course data …
=> json data pages

base-theme/assets/css/main.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/90
Removes font-size for h2 tag in **article.content h2** so that default font-size of h2, defined in **main.scss**, which is 28px (for laptop) and 24px (for mobile) can be applied.  
- Open course homepage
- Go to different pages from sidenavbar
- Verify that heading (h2) is bigger than sub-heading (h3)
- Verify that color of heading (h2) is red (a31f34) and color sub-heading (h3) is black.
- Repeat the above steps for different pages and different courses.
=> fix: removing extra font-size for h2 tag

course/layouts/home.html, course/layouts/index.coursedata.json, course/layouts/partials/course-image-url.html
closes #338
This adds the course image to `coursedata.json` under the `image_src` key (which is what we're using in the search index currently).
We already had code to pull the image out for displaying it on the course home page, so I just wrapped that up in a partial so we can have that logic live in one place.
Run a course build (`start:course` should do I think) and confirm that a correct looking `image_src` property shows up in `coursedata.json` and that the image works on the course home page.
=> add course image to coursedata.json

course/assets/css/course-home.scss, course/assets/css/course-info.scss, course/layouts/home.html, course/layouts/partials/course_info.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/329
New enhanced design for expanding and collapsing course description, course meta-data and image description.
- Verify that image description, course description and course info (meta-data) expands and collapse correctly when arrow icon is clicked/toggled.
- Change the size of the content or test them on different courses having different sizes/lengths of content.
- Test the above on multiple browsers and multiple screen sizes.
Video link: https://drive.google.com/file/d/1R8yhyXMAMVmjZn9dphS0kjAjpxwbkwm2/view?usp=sharing
=> feat: expand/collapse enhancement

base-theme/assets/css/main.scss, base-theme/layouts/shortcodes/tdopen.html, base-theme/layouts/shortcodes/thopen.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/347
The last remaining task on https://github.com/mitodl/ocw-studio/issues/569 has to do with being able to edit tables imported from legacy courses generated by `ocw-to-hugo`.  This PR adds support for the `colspan` and `rowspan` attributes if they are included on the `tdopen` or `thopen` shortcodes.
Follow the testing instructions in https://github.com/mitodl/ocw-to-hugo/pull/429 and https://github.com/mitodl/ocw-studio/pull/899
=> add optional colspan and rowspan attributes to tdopen / thopen shortcodes

course/assets/js/navigation.js
Closes #345 
Matches the window pathname and href in anchor tag irrespective of path name.
On Course Page
- Click `SYLLABUS` and verify that it becomes active
- Click any assignment and after reload verify it becomes active
=> Match window pathname and href in anchor tag irrespective of trailing slash

course/layouts/partials/learning_resource_types.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/86
**Note:** Ticket was created for **course features**, but I was unable to find course features, maybe it has been fixed or renamed, I'm not sure. Since the issue was also for **learning resource types**, so I fixed that instead.
For reference, please view [this comment](https://github.com/mitodl/ocw-hugo-themes/issues/86#issuecomment-1018337756)
Does not render learning resource types when it's count is 0
- Go to any course which has learning resource types:
- Verify that the section is shown in home page and other pages.
- Go to any course which has **no** learning resource types:
- Verify that the section is **not** shown in home page and other pages.    
Before: 
After:
=> fix: hide resource types when count is 0

base-theme/assets/css/main.scss, course/assets/css/course-info.scss, course/layouts/home.html, course/layouts/partials/course_info.html, course/layouts/partials/topics.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/255
- Hides horizontal scroll on course info for screens where content fits in/is adjusted.
- Makes border same for course home page and course info on other pages, to maintain consistency, which got different due to a merged PR.
- Adjusts little padding and margins
- Visit any course ( [e.g](https://ocw-draft-qa.global.ssl.fastly.net/courses/peters-test-2021-09-29-1/pages/asdf/) )
- Using responsive mode, set the browser width to "Laptop with MDPI screen" ( [width: 1280, height: 800](https://gist.github.com/TrevorJTClarke/27896c197a34e597a8a6) )
- Verify that there is no horizontal scroll.
Before:
After:
=> fix: horizontal scroll bar on topics in drawer

base-theme/assets/css/main.scss, www/layouts/about/section.html, www/layouts/educator/section.html
Closes #360
Add's aspect ratio property to iframe
Verify Iframe is not cut off in mobile form.
=> added aspect ratio to match youtubes video iframe

www/layouts/partials/home_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/85
- Adds data attributes to course carousel on home page so it can be swiped on mobile screens. 
- Go home page (www) on mobile
- Verify that the course cards are scrollable by thumb first time, without clicking any `Next` or `Previous` button.
(Note: If you're opening mobile view from laptop, do refresh the page once mobile view is opened)
=> fix: adding data attributes to carousel

base-theme/assets/index.ts, course/assets/css/course-content.scss, course/assets/css/course.scss, course/layouts/partials/course_content.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/361
**Note:** Initially this PR was opened to fix the `issue of title being overflown: title was not wrapped in it's div, it flowed to right outside it's section` but as per discussion in this [thread](https://github.com/mitodl/ocw-hugo-themes/pull/364#discussion_r791214738), this issue should be addressed upstream hence now this PR only adds expand/collapse in document title 
- Expand/collapse shows up if title covers more than 3 lines. 
- Verify that document title remains in it's section regardless of it's length/size. It is not flowed outside like shown in the issue.
- Verify that on increasing title length, expand/collapse shows up which correctly works with a smooth transition.
- Please repeat the above step for:
1. all …
=> feat: expand/collapse in document title

www/assets/css/home.scss, www/layouts/partials/promo-carousel.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/69
- Fixes the moving section of promo carousel when sliding on mobile screen.
- Enable sliding by thumb on mobile screen first time, without clicking any previous or next button. 
- Go to home page via mobile screen or change laptop's width to mobile (small devices)
- Verify that while sliding the carousel, its position is fixed and it does not move.
- Please test this:
- on multiple screen dimensions (few common dimensions can be taken from [here](https://gist.github.com/TrevorJTClarke/27896c197a34e597a8a6))
- on multiple browsers 
Position of arrow buttons and whole section remains fixed/same, however, height increase/decrease depending upon the size of content.
=> fix: carousel height and thumb swipe fixed

course/layouts/partials/learning_resource_types.html
Did not create an issue for it but we have a relevant [comment](https://github.com/mitodl/ocw-hugo-themes/pull/364#issuecomment-1022257547)
- Adds a check for Learning Resource Types as we have a `len` function on it so if `Learning Resource Types` does not exist, code will not break 
- Open any course and go to it's home page 
- Remove the attribute: `learning resource types` and verify that the page loads without any error
=> fix: sanity check for Learning Resource Types

course/layouts/resources/single.coursedata.json
None
The data.json files for resources are missing the title. This fixes the issue
Run `npm run start:course` for any course
Go to the resource page for any course resource
Append /data.json to the resource page url
Verify that you see a title
=> populate resource title

www/assets/js/components/SearchFacetItem.tsx, www/assets/js/lib/util.test.ts, www/assets/js/lib/util.ts
closes #370 
This just sort of slugifies some text before we use it as an element ID. This should help us meet accessibility guidelines.
Check out the `id` on the checkbox `input` and the `htmlFor` on the `label` which are rendered by `SearchFacetItem`. They shouldn't have spaces!
=> slugify text before using it as an ID

www/assets/js/components/SearchPage.test.tsx, www/assets/js/components/SearchPage.tsx
closes #378 
The issue has a bit of information, but basically we had mis-used `aria-live` in a way that made the search page pretty terrible for using a screenreader. In short, all of the changes within a div marked `aria-live="polite"` are read out when they change, and we were wrapping both the search facets and the search results with that, so every time the results changed the screenreader would read out all that stuff.
Instead, a recommendation for dynamic search UIs like ours is to only wrap the result count with `aria-live="polite"`, so that when the search results update there is a notification to the user but they aren't deluged with a ton of stuff.
Optimally, try out the search page using a screenreader and confirm that the setup is better now (i.e. when you run a search you …
=> fix aria-live situation

www/assets/js/components/SearchBox.test.tsx, www/assets/js/components/SearchBox.tsx
closes #379 
- sets `role="search"` on the `form` tag which wraps the search input
- sets `type="search"` on the `input` tag itself
these two changes should signal to a screenreader user that the search box is, well, a search box, and not just a random text field. setting `role="search"` on the form should also allow that to be recognized as a functional region by screenreaders.
You can just confirm that the change makes sense, and possibly try out in a screenreader if you want.
Note that I removed the existing (erroneous) `role="search"` in #380
=> fix up role="search" situation

package.json
when switching over to building w/ typescript (#335) I switched over the `fmt` package.json script but neglected to make the same edit to `fmt:check`. This changes `fmt:check` so it also checks `.ts` and `.tsx` files.
CI should pass!
=> fix small oversight on typescript change

course/assets/css/instructor-insights.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/65
- Gives 100% width to all the images in instructor insights only. 
- Open any course
- Go to instructor insights and verify that the images are scaled and takes 100% width of the section.
- Verify that **no** other image in other sections/modules is scaled.
- Repeat the above step for: 
- Multiple screen dimensions
- Multiple browsers
=> fix: instructor insights images scaled up

course/layouts/partials/video-gallery-item.html
- Closes https://github.com/mitodl/ocw-hugo-themes/issues/399
- Sets `alt=""` for video gallery page.
- Styling was being disturbed so top and bottom padding has been added so the content is adjusted in the section and does not overflow.
- Go to course(s) which has/have video lectures and missing images. [(example)](https://ocwnext-rc.odl.mit.edu/courses/cms-611j-creating-video-games-fall-2014/video_galleries/lecture-videos/) 
- Open video gallery page: `video_galleries/lecture-videos/`
- Verify that no alt text is being shown for missing images and the content/title is not overflowing, it is smoothly adjusted in the section. 
- Please test this
-  for multiple courses having different title sizes
- on multiplee screen dimensions
=> fix: alt text removed for lecture videos

course/layouts/index.contentmap.json
this is part of #279
This PR adds a new json template which renders a map from UUID to relative link for all pages. We need this because for the resource collections we're storing the site name and the UUID for pieces of content. With this map we'll be able to get complete URLs to request the `data.json` file for each piece of content.
Check out the rendered course. There should be a json file at `/content_map.json` that looks like what I described.
Note that you'll need to check out this PR for ocw-hugo-projects for it to work correctly (for the course theme Hugo config) https://github.com/mitodl/ocw-hugo-projects/pull/119
=> add a data template for creating a course content map

base-theme/layouts/partials/footer.html, www/assets/css/home.scss, www/layouts/contact/section.html, www/layouts/home.html, www/layouts/partials/home_course_cards.html, www/layouts/partials/home_testimonials.html, www/layouts/partials/newsletter_signup.html, www/layouts/partials/ocw_news.html, www/layouts/partials/promo-carousel.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/413
See <img width="159" alt="image" src="https://user-images.githubusercontent.com/430126/152714747-172a104b-a1ea-4e13-b0f6-9f35eaff9a1f.png">
- Go to www homepage.
- Verify all the above-mentioned points.
=> accessibility: home page

base-theme/layouts/partials/footer.html
I missed a typo which causes the link to be broken on some pages this PR fixes those issues.
=> Fixed  typo which is causing link to be broken

course/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/396
- Increases length value for course caption comparison
- Adds some bottom margin when the expand widget is not showing so the caption does not stick/or come too close with the border
- Go to any course homepage
- Ensure that expand/collapse is only shown and working when the course image caption is **not** adjusted in the available area.
- Please repeat this for maximum courses or change the caption in course content
=> fix: increased value for expand widget for course image description

course/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/426
- Adds some margin-bottom below course description only when there is no expand/collapse widget
- Go to course home page for that course whose description doesn't have expand/collapse widget.
- Verify that there is some sufficient space b/w `course description` bottom-border and `course info` heading.
Before: 
After:
=> fix: some margin bottom added below course description

base-theme/assets/webpack/webpack.common.js
Closes #424 
Fixes second level imports for MathJax
- Verify MathJax is rendering properly in 18.065
The main reason MathJax was not rendering properly was it was trying to load boldsymbol from mathjax/input/tex/extensions/  which gave a 404  we had flatten the folder structure while bundling.
=> fixed bug with boldsymbol not rendering

course/layouts/shortcodes/resource_file.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/433
This PR takes the `file` attribute that `resource_file.html` returns and passes the value through `resource_url.html` before returning it.  This ensures that even if a fully qualified S3 URL is stored in `file`, by default a root relative URL will be returned. `If RESOURCE_BASE_URL` is set, then the URL will be returned prefixed with this value.
- Clone https://github.mit.edu/ocw-content-rc/wgs.s10-fall-2017
- Configure your environment to point at the course and spin it up with `npm run start:course`
- Go to http://localhost:3000/pages/instructor-insights/ and you should see a missing image at the top of the page.  Inspect it and you should see a root relative URL.
- Stop the site and set `RESOURCE_BASE_URL` to …
=> properly format urls passed into `resource_file.html`

course/layouts/shortcodes/resource_link.html
Closes #429 
Adds an optional anchor_id parameter to link to document fragments
- Verify resource_links work as it is
- Add HUGO anchor_ids to resource_links and verify they link to the proper page
So I did some RnD on Hugo and HUGO automatically generates anchor id's for heading and we can link to them using relref or rel shortcodes [as explained here](https://gohugobrasil.netlify.app/content-management/cross-references/#:~:text=When%20using%20Markdown%20document%20types,and%20across%20the%20entire%20site.) I have added an option for these anchors in resource_links but we will not be able to extract the unique identifier in this case.
(Optional)
https://user-images.githubusercontent.com/87968618/154076786-d7acb3eb-8183-4aa3-8ccc-af081cb3f971.mov
=> added optional anchor id to resource link

www/assets/js/components/SearchPage.tsx
Closes #105 
Adds and immediate return in `toggleResourceSearch` on clicking an already active facet.
Go to `/search` and verify the following 
- On clicking `Resource` it switches to resource search .
- On clicking again nothing happens and it stays on Resource Search
- On clicking to `Course` it switches to Course search
- On clicking again nothing happens and it stays on Course search
=> fixed resource toggling issue

base-theme/layouts/partials/resource_url.html, course/layouts/partials/video.html, course/layouts/partials/video_embed.html
Closes #443 
Adds conditional in resource_link partial to skip processing links to archive.org. 
- Open video lectures for course `22.01-fall-2016`
- Click `Download Video` and verify they it opens archive.org download page.
- Verify videos from s3 bucket behave as it is
=> fixed video urls not linking to archive.org

course/assets/css/course-content.scss, course/assets/css/instructor-insights.scss, course/layouts/partials/course_content.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/448
- Gives some css style of `h3` inside `td`
- Rename an html entity id to something more relevant
- Build/run any course which has `h3` tags inside `td` of `table` tag
- Verify the following CSS is applied to it
```
font-weight: normal;
font-style: italic;
font-family: arial, helvetica, sans-serif;
``` 
- Also verify that this CSS has NO side-effects (It is not applied anywhere else)
=> fix: style of h3 in td, name of an id changed

base-theme/assets/css/main.scss
Closes #460 
Fixes css to images expands to original width
Clone Course with embedded image
- Verify image is rendered correctly
=> Fixed CSS for image rendering small

www/layouts/pages/single.html
Closes #458 
Adds variant of page-title partial based on title of current page
This PR can be tested by the following way
- Start ocw-www
- Visit '/pages/privacy-and-terms-of-use/' and verify title is `Privacy and Terms of Use`
- Visit `/pages/welcome-to-the-nextgen-ocw-beta-site/` and verify title is `Welcome to the NextGen OCW beta site!`
=> Fixed page_title partial caching the Title

base-theme/layouts/shortcodes/sub.html, base-theme/layouts/shortcodes/sup.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/461
- Following is done for `sub` and `sup` shortcodes: 
- Adds `-` with `{{` and `}}` to remove the extra white space, if any, surrounding the variable. ([reference](https://gohugo.io/templates/introduction/#whitespace))
- Adds `{{- "" -}}` to remove the whitespace caused by `sub` and `sup` html elements. ([reference](https://discourse.gohugo.io/t/solved-extra-space-after-shortcode-output/6736/4))
- Go to any course which has `sub` or `sup` shortcode. 
- Verify that there is no extra whitespace.
Before: 
After:
=> fix: removing extra whitespace in sub and sup shortcodes

course/assets/css/video-transcript.scss, course/layouts/partials/video.html
Closes #454 
Adds a `related resources` and `optional tab` in video page.
Verify the following
- When there is content, add a "related resources" section below the Transcript, with a similar UX and with the label "Related Resources". It should default to closed, but can be opened to view the content.
- When there is content, add an optional section below the video, using the label specified in the page markdown. It should default to closed, but can be opened to view the content.
- All tabs remain close on page load
(Optional)
=> added optional and related resources tab

base-theme/assets/css/main.scss
Closes #479
Adds margin top to headings immediately followed by an anchor tag.
Verify spacing around h3 is consistent
=> fixed spacing issue with h3

base-theme/layouts/shortcodes/resource_link.html
Related to https://github.com/mitodl/ocw-studio/issues/1066
This PR changes the `resource_link.html` to return a markdown link instead of an HTML link.
This should be tested as part of [this PR](https://github.com/mitodl/ocw-studio/pull/1067)
=> change resource_link to be a markdown based shortcode

course/layouts/index.coursedata.json
https://github.com/mitodl/open-discussions/issues/3513
Course images are broken in search because they point to an s3 folder that has changed. This changes the image_src for the course to point to a relative url.
run `npm run start:course` for any course
Go to http://localhost:3000/data.json
Verify that the image_src is a relative url, for example "/7-01sc-fundamentals-of-biology-fall-2011/533499c2943939be949d7aed93782793_7-01scf11.jpg"
=> return relative url for course images

course/assets/css/course-content.scss
see https://github.com/mitodl/ocw-studio/issues/1074
I just merged a chance in studio which will result in some empty paragraph tags when content is rendered in Hugo. This just sets some CSS to put `display: none` on those tags.
Use Studio to create a table w/ some content w/ line breaks inside of table cells. Then render that content as course content over here and make sure that
1. there are some empty `<p>` tags inside of the table cells (just ensuring that things are working as I expect)
2. they all have `display: none` set on them and therefore don't cause any layout issues
If you like you can also confirm that on the main branch they currently _do_ cause some spacing issues.
=> CSS fix for errant empty paragraphs in table cells

www/content/_index.md, www/layouts/partials/home_course_collections.html
Closes #486 
Adds relevant filter in course collection partial
Verify the following
- All course collection available in ocw-www content are filtered based on `homePageCourseCollections`  param
- If a collection exists in ocw-www content but the title is not in `homePageCourseCollections` it is not rendered
=> Added course collection filter based on Title

base-theme/layouts/partials/footer.html, base-theme/layouts/partials/head.html, base-theme/layouts/partials/seo.html, www/content/_index.md, www/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/351
- Creates a block in `head`
- Creates a partial (`seo.html`) in base-theme.
- Defines the block in this partial and the following are added:
- Metadata description and keywords added.
- Google structured data added.
- Default value of description and keywords is defined in the partial in case they are not found in page params
- `metadataDescription` and `metadataKeywords` can be defined in content of different pages so metadata is different for different pages
- Adds alt text for some images
Verify the following:
=> feat: Home SEO

base-theme/assets/css/variables.scss, course/assets/css/course.scss
closes #500 
Just set things up so we can lean on Hugo's built in syntax highlighting support. I basically removed our stuff setting background colors and whatnot, and adding a simple border w/ even padding around `pre` tags. I think it makes it super clear where a code block starts and ends.
This needs to be paired with a config change, over here: https://github.com/mitodl/ocw-hugo-projects/pull/136
You can try rendering some markdown that you create manually, or you can try with CKEditor's output by checking out htis PR: https://github.com/mitodl/ocw-studio/pull/1088 
Here are examples for a few different programming languages:
_**note**: the actually display for the text inside the `<code>` tags will depend on what fonts are available on your environment - the screenshot above is …
=> update code block style to work w/ hugo's syntax highlighting support

www/assets/js/lib/search.test.tsx, www/assets/js/lib/search.ts
Closes #506 
Closes #507 
Modifies the elasticsearch query parameters to give better results when the query text is a course number.
- Set  `SEARCH_API_URL=https://discussions-rc.odl.mit.edu/api/v0/search/` in your .env file and then `source .env`
- [Start Chrome with CORS disabled](https://alfilatov.com/posts/run-chrome-without-cors/).
- All these queries should return three 6.042J courses as the top results:
- http://localhost:3000/search/?q=6.042
- http://localhost:3000/search/?q=6.042j
- http://localhost:3000/search/?q=6.042J
- These queries should return courses starting with `WGS.<x>` as the top results: 
- http://localhost:3000/search/?q=wgs.1
- http://localhost:3000/search/?q=WGS.1
- http://localhost:3000/search/?q=wgs.6
- Other queries that don't …
=> Better search results for course numbers

course/layouts/partials/video-gallery.html
We use the markdown body for descriptions, not the description field. This is safe to remove:
- there were 9 video galleries with descriptions on RC, all in test courses... I moved them all markdown body via admin panel.
- there are 0 video galleries with descriptions on prod (of 218 video galleries)
Open a video gallery and check that it still works.
For example, http://localhost:3000/video_galleries/derivatives/ in `res.18-005-spring-2010`. But any video gallery would do.
=> remove description from video-gallery partial

base-theme/layouts/shortcodes/quote.html
closes https://github.com/mitodl/ocw-studio/issues/1106
This pr displays &nsbp in the quote shortcodes as a space. This is needed because the ocw-studio editor saves leading spaces in the quote shortcode as `&nsbp` when the page is saved
Update the course_json_examples/example_courses.json file in ocw-to-hugo with
```
"courses": [
"15-es718-global-health-innovation-delivering-targeted-advice-to-an-organization-in-the-field-spring-2015"
]
```
Run
`node . -i private/input -o private/output -c course_json_examples/example_courses.json --download`
Go to private/output/15-es718-global-health-innovation-delivering-targeted-advice-to-an-organization-in-the-field-spring-2015/content/pages/instructor-insights/teaching-in-real-world-contexts.md
and replace "`  —Dr. Anjali Sastry`" with "`&nbsp;—Dr. …
=> display &nbsp in quotes correctly

www/assets/js/components/SearchPage.test.tsx, www/assets/js/components/SearchPage.tsx
closes https://github.com/mitodl/ocw-hugo-themes/issues/515
This PR adds topics as a facet to resource search.
Run `npm run start:www` verify that you see topics as a filter for resources and it works correctly
=> add topic to resource search

base-theme/assets/css/footer.scss, base-theme/assets/css/header.scss, base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss, course/assets/css/course-home.scss, course/assets/css/course-info.scss, course/assets/css/course-nav.scss, course/assets/css/instructor-insights.scss, course/assets/css/video-transcript.scss, course/assets/css/video.scss, course/layouts/partials/video_embed.html, www/assets/css/about.scss, www/assets/css/card.scss, www/assets/css/carousel.scss, www/assets/css/common.scss, www/assets/css/course-collection.scss, www/assets/css/educator.scss, www/assets/css/home.scss, www/assets/css/learning-resource-card.scss, www/assets/css/learning-resource-icon.scss, www/assets/css/newsletter.scss, www/assets/css/search-filter.scss, www/assets/css/search.scss, www/assets/css/testimonials.scss, www/layouts/about/section.html, www/layouts/home.html, www/layouts/newsletter/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/472
- Cleans up almost all font sizes.
- Root `font size` set to `16px`
- Font sizes variables created (`font-lg`, `font-md`) with `REM` values.
- Above created variables are used/re-used wherever required.
- Few font-sizes with `16px` value have been removed as they will inherit root's font size which is already `16px`.
- Few other tweaks in CSS to maintain font-sizes uniformity across the app (though there are still places which can be improved too)
- This might not sound good for the tester :) but all the **sections** on all the **pages** of **www** and **courses** need to be tested and verified that `font-size` content is clean, smooth, and consistent. 
- Verify that all the content of **www** and **courses** is looking fine and …
=> fix: cleaning font-sizes, replacing px with rem

course/assets/css/instructor-insights.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/525
- Go to instructor insights pages of courses which have images
- Compare the images size with RC or PROD and verify that now images are not scaled (not taking 100% width of section)
=> revert PR 388: instructor insights images scaling

www/assets/css/home.scss, www/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/533
- Fixes the CSS inner text of give (donation) button 
- Go to www landing page
- Scroll to give (donation) button
- Verify that inner text is properly aligned/centered.
- Please repeat this for multiple screen dimensions.
=> fix: give (donation) button css

course/layouts/partials/image_resource.html, course/layouts/shortcodes/resource.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/523
- Since we have to pass `href` or `href_uuid` to resource shortcode so now our resource shortcodes will have `named` parameters unlike before (having only 1 positional parameter i.e: UUID).
- So this PR checks and get named parameters which are/can be:
- UUID (required)
- href (optional)
- href_uuid (optional) 
But since all the previous resource shortcodes have 1 positional parameter (UUID) so its support is also there hence if UUID is not found as a named parameter then it is assumed that it will be a positional parameter and it is fetched as a positional parameter.
- Default values (empty) values are set for named parameters.
- Images resource partial is created which does the following:
- For all the image resources, a check …
=> feat: support links in resource (image) short codes

course/layouts/partials/video.html, course/layouts/partials/video_embed.html, course/layouts/partials/youtube_player.html
https://github.com/mitodl/ocw-hugo-themes/issues/520
This pr passes the start and end times to the video js player
Run ocw-to-hugo for `18-01sc-single-variable-calculus-fall-2010` with AWS_BUCKET_NAME=open-learning-course-data-rc in your .env file
In ocw-hugo-themes set COURSE_CONTENT_PATH=<path to your ocw-to-hugo output> and OCW_TEST_COURSE=18-01sc-single-variable-calculus-fall-2010
Run `npm run start:course` go to http://localhost:3000/resources/clip-3-limit-of-secants/. Verify that the video starts at 8:46
=> add start and end to videos

base-theme/assets/css/header.scss, www/assets/js/components/CourseListRow.test.tsx, www/layouts/collections/single.html, www/layouts/partials/collection_cover_image.html
Closes #547
Displays the cover image for a course collection if there is one.
Fixes a flaky test
In your own local studio instance of the ocw-www site, or on RC's, create a collection and assign a cover image to it.
Git clone the above ocw-www repo and point to it with `WWW_CONTENT_PATH` in your ocw-hugo-themes .env
Run `npm run start:www` and go to the collection page.  You should see the cover image at [100% width and 300px height](https://projects.invisionapp.com/share/DN12GXJ28MXA#/screens/464971999_Course_Collection_B), it should scale appropriately as you change the browser width.
Go to a collection page without a cover image, it should render fine without it.
Narrow:
============
Wide:
=> Add cover image to collection page

base-theme/assets/css/main.scss, course/layouts/partials/course_content.html
Closes #564 
Fixes styling issues for Appzi feedback button
Verify the following
- `Hide course info` button does not overlap with `feedback` button
-  `feedback` button does not overlap with content
- `feedback` button possition on ocw-www and ocw-course  is consistant
=> fixed styling issues for appzi feedback button

www/layouts/partials/home_testimonials.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/568
In https://github.com/mitodl/ocw-hugo-themes/commit/554ef4bfcc56b8b6c627f4f4cc9a95fae940136e, in the transition to `ocw-hugo-themes` from `ocw-course-hugo-theme` we updated the version of bootstrap used by the project which changed the way carousels work.  Since the example testimonial data has only ever included 4 testimonials, it wasn't clear that the testimonials are also supposed to use a carousel if there are more than 4 of them.  This PR sets up testimonials to render in a carousel in the same way the new course cards at the top of the homepage do, showing only the amount of testimonial cards that can be displayed based on the screen width.  This PR also changes the labeling of testimonials to refer to them as "stories."  A …
=> Fix testimonial carousel

www/assets/css/course-collection.scss, www/layouts/collections/single.html, www/layouts/partials/course_list.html
Course collection desktop:
Course collection mobile:
Course list desktop:
Course list mobile:
None
This pr improves the styling for course collections and lists
Pull down the latest ocw-www repo.
Set WWW_CONTENT_PATH=<your path>/ocw-www 
Run npm run start:www
View a course collection. One is http://localhost:3000/collections/energy/
Course collections should look like the following design:
https://invis.io/DN12GXJ28MXA#/464971999_Course_Collection_B
There isn't a mobile design or a design for the course list page but both of those should look good.
The cover image doesn't load locally but will work on RC.
=> styling for course collections and lists

www/layouts/about/section.html
No ticket :) 
Fixes this button redirection on about us page:
- Go to about us page and verify that this button works fine
=> fix: open learning button redirection

www/assets/css/testimonials.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/574
Fix testimonials images squish by `object-fit: cover;`
- Go to testimonials page and verify that the images does not squish
**Before:**
**After:**
=> fix: testimonials images should squish

www/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/597
- Checks if page: `/pages/get-started` exists then `Get Started` link on www homepage is redirected to `/pages/get-started`
- If `/pages/get-started` does **not** exist/found then it redirects to [zendesk get started page](https://mitocw.zendesk.com/hc/en-us/categories/4414679122971-Get-Started-with-MIT-OpenCourseWare)
- Create and publish a `get-started` page or clone/pull `ocw-www` as it already has a `get-started` page.
- Go to www homepage and verify that this link:
redirects to `/pages/get-started`
- Remove `get-started` page and now verify that get started link redirects to zendesk get started page.
- Test on all other use-case(s) which is/are not mentioned above.
=> get started link conditionally updated

base-theme/assets/css/main.scss, course/layouts/partials/video-expandable-tab.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/605
- Previously href in anchor tag was used for bootstrap expand/collapse and in result the class/ID in href became bad/broken link.
- This PR replaces `anchor tag` with `div` and `href` with `data-target` hence now we don't have any href hence no bad/broken links.
- Build course(s) which has/have video tabs (`transcript`, `related-resource`, `optional-tab`) in video lectures.
- Verify that for all the tabs, expand/collapse works accurately and smoothly.
- Using a link-checking tool, verify that there is no broken/bad/dead link (Not sure if this is required as href has been completely removed)
=> anchor tag in video tab toggle/collapse replaced with div

base-theme/assets/css/main.scss, course/layouts/home.html, course/layouts/partials/mobile_nav_toggle.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/606
- Changes the style of `browse course material` button according to issue ticket and invision design
- Removes the borderline for medium and below screens making the button a separator, but on large or above screens, borderline will be shown.
- Adds some space around the button on course home page 
- Build any course(s) locally
- Go to a smaller screen size (tablet or less)
- Verify that the style `browse course material` button is correct.
=> fix: browse course material button styling

www/layouts/educator/section.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/615
This pr makes updates to the educator page
Run ocw-www locally.
Go to http://localhost:3000/educator/
Make sure everything looks good and the link/wording changes from https://docs.google.com/document/d/1nYyuW1VAdh5cWvmtSMlV8d0KVoZcd2b0842pBcjC_YA/edit are made
We're waiting to hear whether
"Share my adaptation or open education story on the [Chalk Radio podcast](https://chalk-radio.simplecast.com/) by emailing [chalkradio@mit.edu](mailto:chalkradio@mit.edu)" should link to the email or a voicemail number, so ignore the voicemail bullet in the issue
=> educator page updates

www/layouts/partials/new_course_cards.html
none
A bug in https://github.com/mitodl/ocw-hugo-themes/pull/630 breaks course links
run npm run start:www
Go to http://localhost:3000/
Verify that when you click on a new course it goes to the correct url for the course. You will still see "404 page not found" locally
Also the previous/next buttons arn't broken ocw-studio-rc just currently returns exactly four new courses because a bunch of courses were accidently deleted from rc
=> new course carousel fix

base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/633
- Override font size of `h4` and makes it smaller than `h3`
**`Large Screen:`** 
- h3 = 24px
- h4 = 20px
**`Small Screen:`** 
- h3 = 20px
- h4 = 16px
- Go to any www or course page, where `h3` and `h4` tags have been used
- Verify that `h4` is smaller than `h3` (make sure that any of the tags is NOT specifically overridden for any section on that page.)
- Repeat the above for multiple screen sizes
Laptop Screen:
Mobile Screen:
=> fix: h4 fontsize overridden and made smaller than h3

www/layouts/instructors/item.json.json
Closes https://github.com/mitodl/ocw-studio/issues/1150
- `Jsonify` instructor title, first_name, last_name, middle_initial and salutation so it escapes `"` when built 
- Either in studio RC, or local setup of Studio, edit ocw-www, wrap any instructor title with `""`. e.g: `Dr. "Chengzhao" Zhang`. 
- Publish it and clone.
- Build ocw-www. i.e: `npm run start:www`
- Check the JSON file generated in your content: `public/instructors/*uuid*/index.json`
- Note that `""` are not escaped in title 
- <img width="305" alt="image" src="https://user-images.githubusercontent.com/93309234/163779224-49e5a95a-47ed-4f49-a9db-72dd0ead7f73.png">
- Now checkout this branch
- Repeat the above steps
- Verify that now `""` are escaped in title
- <img width="313" alt="image" …
=> fix: jsonifying instructor fields in layout

.github/workflows/deploy.yml, course/layouts/sitemap.xml
Completes one of the tasks in https://github.com/mitodl/ocw-hugo-themes/issues/673
This PR uses the newly added `SITEMAP_DOMAIN` env variable to construct fully qualified URLs in the `course` theme's sitemap.  This is being done to improve Google search results.
- If you've never spun up a course locally before, read the readme to learn how to do so and make sure you have your `.env` configured with a course to run
- Clone the branch of `ocw-hugo-projects` from [this](https://github.com/mitodl/ocw-hugo-projects/pull/171) PR and make sure you point to it using `COURSE_HUGO_CONFIG_PATH`
- Set `SITEMAP_DOMAIN` in your `.env` file to `ocw.mit.edu`, or anything you want to test with
- Make a temporary edit to `start_course.sh`, setting the Hugo command at the end to:
```
hugo server \
-p 3000 …
```
=> write fully qualified urls into course sitemap

fields/layouts/subfields/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/676
In https://github.com/mitodl/ocw-hugo-themes/pull/670, we added a new theme called `fields` to the repo that can be used for creating a standalone page for a field of study.  A template was left out for displaying a single subfield, and this PR adds that in.
- Go to https://ocw-studio-rc.odl.mit.edu and create a site using the `mit-fields` starter, making sure you add subfields and associate them with your field and publish your site.
- Make sure you have `ocw-hugo-projects` cloned locally
- Find your repo at https://github.mit.edu/ocw-content-rc and clone it locally
- Set the following env variables in your `.env`:
- `FIELDS_HUGO_CONFIG_PATH=/path/to/ocw-hugo-projects/mit-fields/config.yaml`
- `FIELDS_CONTENT_PATH=/path/to/<your …
=> add single template for subfields

www/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/661
- Removes `Give Now` text/heading from donation section in www home page
- Go to www homepage -> donation/give now section.
- Verify that there is no "Give now" text/heading.
=> removes give now heading from www homepage

base-theme/assets/index.ts, base-theme/assets/js/utils.ts, www/assets/js/notification.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/645
- Add utils for setting and getting data from local storage with checks and error handling so in case an exception is thrown, that exception is caught silently and a message is shown in the console.
- Some more info:
- I think this type of error can occur when the user has blocked cookies and we try to access cookies either via local storage or any other way. 
- We are accessing local storage in `notifications.js` and this PR fixes it by using the util in which we are catching all exceptions.
- But I think cookies are also being accessed in third-party libraries like `pdfjs` and `youtube.js` and this error can occur there too if a user has blocked cookies. So for this, I think we'll have to figure out a good approach to handle …
=> feat: error handling for localstorage

www/layouts/sitemap.xml
Closes https://github.com/mitodl/ocw-hugo-themes/issues/686
In https://github.com/mitodl/ocw-hugo-themes/pull/679 we added a sitemap to the `www` theme that writes a `sitemapindex` including all of the sites returned by a call to the `ocw-studio` API.  This PR adds a check in the `www` sitemap index template that makes sure the `base_url` property on the site returned by the `ocw-studio` API is not blank before including it in the index.
- Set the following in your `.env`:
- `API_BEARER_TOKEN=<get value from Heroku production ocw-studio`
- `OCW_STUDIO_BASE_URL=https://ocw-studio.odl.mit.edu/`
- `SITEMAP_DOMAIN=ocw.mit.edu`
- Visit http://localhost:3000/sitemap.xml and verify that you don't see:
```
<sitemap>
<loc>https://ocw.mit.edu//sitemap.xml</loc>
</sitemap> …
```
=> make sure base_url is not blank before writing a sitemap into the index

base-theme/layouts/partials/course_carousel_card.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/265
In https://github.com/mitodl/ocw-hugo-themes/pull/264, we added in a hack to rewrite the course carousel URLs and replace instances of `coursemedia` with `courses` in the image URL.  This was necessary due to the way we were deploying the site with a custom EC2 server directly from `ocw-to-hugo` output, but is no longer necessary now that the EC2 servers have been deprecated.
- Set the following env variables:
```
OCW_STUDIO_BASE_URL=https://ocw-studio.odl.mit.edu/
STATIC_API_BASE_URL=https://ocw.mit.edu/
RESOURCE_BASE_URL=https://ocw.mit.edu/
OCW_IMPORT_STARTER_SLUG=ocw-course
```
- Visit http://localhost:3000
- You should see the featured courses carousel and the images should load.  If you inspect the …
=> remove the old coursemedia hack

base-theme/layouts/partials/course_carousel_card.html, base-theme/layouts/partials/featured_course_cards.html, fields/layouts/home.html, fields/layouts/subfields/single.html, www/assets/js/LearningResources.ts, www/assets/js/components/SearchResult.tsx, www/assets/js/lib/search.test.tsx, www/assets/js/lib/search.ts, www/layouts/collections/single.html, www/layouts/course-lists/single.html, www/layouts/partials/new_course_cards.html, www/layouts/resource_collections/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/699
In https://github.com/mitodl/ocw-studio/pull/1316 and subsequently https://github.com/mitodl/ocw-studio/pull/1371, we added the ability for content authors to customize the URL of their site.  This PR changes the theme so that `url_path` is used where it's available, assuming the `url_path` is already prefixed with `root-url-path`.  It's also assumed that `id` in some relation data is filled with the value of `url_path`.
- Clone `ocw-www` from `ocw-content-rc`
- In your `.env`, set the following:
```
OCW_STUDIO_BASE_URL=https://ocw-studio-rc.odl.mit.edu/
RESOURCE_BASE_URL=https://ocwnext-rc.odl.mit.edu
STATIC_API_BASE_URL=https://ocwnext-rc.odl.mit.edu/
WWW_CONTENT_PATH=/path/to/ocw-content-rc/ocw-www/
```
- Run `npm run …
=> update theme to use url_path

course/layouts/partials/content_header.html, course/layouts/partials/course_content.html, course/layouts/partials/resource_title.html, course/layouts/partials/video.html, course/layouts/resources/single.html
Related to https://github.com/mitodl/ocw-hugo-projects/issues/185
In https://github.com/mitodl/ocw-hugo-projects/pull/187 we are setting resources so that in `ocw-studio` the description will be written into the markdown body, allowing linking to pages / resources using our shortcode / uuid system.  In https://github.com/mitodl/ocw-studio/pull/1382, we are migrating all existing values for resources in `metadata["description"]` to the markdown body, concatenating with the existing value if necessary.  This PR adjusts the theme to source resource descriptions from the markdown body of resource pages.
- Follow the testing instructions for https://github.com/mitodl/ocw-studio/pull/1382, making sure you are set up to publish courses to a test Gtihub org
- In your `ocw-studio`, run the …
=> source resource descriptions from markdown body

base-theme/layouts/_default/sitemap.xml
Hotfix for https://github.com/mitodl/ocw-hugo-themes/pull/698
In https://github.com/mitodl/ocw-hugo-themes/pull/698, we added a list of "disallowed urls" that we don't want ending up in the sitemaps.  This PR failed to take into account the `--baseUrl` argument being used in RC and production.  This PR adjusts the course sitemap template to take that into account when comparing against the disallowed urls.
- Clone any course repo from `ocw-content-rc` or create one yourself and clone the course content repo locally
- Set the following in your `.env`:
```
COURSE_CONTENT_PATH=/path/to/ocw-content-rc/
OCW_TEST_COURSE=<your course id>
SITEMAP_DOMAIN=ocwnext-rc.odl.mit.edu
```
- Modify the `hugo server` line in `start_course.sh` to look something like this, replacing the course ID with your …
=> fix for base url in course sitemap

base-theme/layouts/_default/sitemap.xml
Hotfix for https://github.com/mitodl/ocw-hugo-themes/pull/710
In https://github.com/mitodl/ocw-hugo-themes/pull/710, we fixed an issue with the course sitemap construction not taking the `--baseUrl` setting into account.  Something that I failed to notice was that our `--baseUrl` setting in RC and production doesn't have a trailing slash.  This causes the check to fail, because there will be a preceeding slash on `$path` after stripping the `baseUrl`.  This PR does just that, strips the preceeding slash.
Follow the same testing instructions in https://github.com/mitodl/ocw-hugo-themes/pull/710.  Beyond that, further validation will be needed in RC
=> fix slash prefix issue with course sitemap disallowed url check

base-theme/layouts/_default/sitemap.xml
Hotfix following up https://github.com/mitodl/ocw-hugo-themes/pull/712
If you read the history in https://github.com/mitodl/ocw-hugo-themes/pull/712, you'll see that 2 other PR's have been merged attempting to fix this issue that have been unsuccessful.  This is because of a discrepancy between running the site locally using `hugo server` vs how the site is simply built by running `hugo` in Concourse.  This PR actually fixes the issue and removes the invalid URLs from the sitemap.
The main issue with testing the fixes to this issue previously was the use of `hugo server` to fully run the site locally when testing.  Instead, we should just build the site using `hugo` manually with the same arguments used in Concourse.
- Clone any course repo, such as …
=> actually fix invalid entries in course sitemap

fields/layouts/home.html, fields/layouts/subfields/single.html, www/assets/js/LearningResources.ts, www/assets/js/hooks/hugo_data.test.ts, www/assets/js/hooks/hugo_data.ts, www/assets/js/lib/util.ts, www/layouts/collections/single.html, www/layouts/course-lists/single.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/705
- Changes the approach of storing course list data from nested objects to array of object so original list order can be maintained.
- Makes appropriate changes in React component and tests
- Checkout this branch.
- Open any course list (e.g: http://localhost:3000/course-lists/open-learning-library/ OR `netlify-link`/course-lists/open-learning-library/)
- Verify that the order of courses in all the course lists is exactly the same as their order in studio.
- Test any other use case that needs to be tested.
=> fix: course list order maintained

base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss, base-theme/layouts/partials/video.html, base-theme/layouts/partials/video_embed.html, base-theme/layouts/partials/youtube_player.html, course/assets/course.js, course/assets/css/video-transcript.scss, course/assets/css/video.scss, course/assets/css/videojs_player.scss, course/assets/js/video_fullscreen_toggle.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/658
- Updates the styling according to the new [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/461529499/comments?scrollOffset=576).
- Moves player controls below the video player and make them permanently visible, instead of displaying on hover
- Attaches the transcript widget to the video player
- Link the youtube button to the youtube page for the current video
- **Note:** A separate [issue](https://github.com/mitodl/ocw-hugo-themes/issues/731) has been created for moving download buttons to in video control bar. 
- Verify the points mentioned above.
- Test any use-case that needs to be tested.
Embedded video player:
When the page loads and the video has not started yet:
=> video player design update

base-theme/layouts/partials/video.html
None
For local development, RESOURCE_BASE_URL currently isn't applied to video transcripts so the caption file and transcript download doesn't work locally. This fixes the issue
Download a course with videos from https://github.mit.edu/mitocwcontent. One option is
https://github.mit.edu/mitocwcontent/15.071-spring-2017
Set
RESOURCE_BASE_URL=https://ocw-content-live-production.s3.amazonaws.com/
Run the course locally. You should see text in the automated transcript track
=> Fix video transcripts RESOURCE_BASE_URL

base-theme/layouts/partials/seo.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/725
This PR changes the default source for the `meta` `description` and `keywords` tags to `.Params.metadata_description` and `.Params.metadata_keywords`.  This is based on the new fields being added to `ocw-studio` in https://github.com/mitodl/ocw-hugo-projects/pull/190.  The fields have been named to conform with the standard of front matter parameters being in snake case.
- Clone a course repo from `ocw-content-rc`
- Set the following in your `.env`:
```
COURSE_CONTENT_PATH=/path/to/ocw-content-rc/
OCW_TEST_COURSE=<folder name of course you cloned>
```
- Run the course with `npm run start:course`
- Visit http://localhost:3000 and visit any page, then inspect the source.  Look for the `meta` tag with `name="description"` and ensure …
=> use new search metadata fields

base-theme/layouts/partials/course_cards_level.html, base-theme/layouts/partials/course_carousel_card.html, www/assets/js/LearningResources.ts, www/assets/js/components/CourseListRow.test.tsx, www/assets/js/components/CourseListRow.tsx, www/assets/js/components/SearchResult.test.tsx, www/assets/js/components/SearchResult.tsx, www/assets/js/factories/search.ts
https://github.com/mitodl/ocw-hugo-themes/issues/738
While testing the compact view we noticed that level was not being rendered correctly when there were multiple levels. Turns out ocw-hugo-themes expects level to be a string but it is actually an array both in the data coming from search and the data coming from /course/json.data 
Clone ocw-www from git@github.mit.edu:ocw-content-rc/ocw-www.git
Set EXTERNAL_SITE_PATH=<your path>/ocw-www
STATIC_API_BASE_URL=https://live-qa.ocw.mit.edu/
SITEMAP_DOMAIN=https://live-qa.ocw.mit.edu/
Run `start:www`
In the new course carusel RES.6-013  will have multiple levels and TEST101 has null level. Both should look good and the links should work correctly
In your local search, either find or create courses with no level or multiple levels. If you don't …
=> make level array

base-theme/assets/js/pdf_viewer.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/723
- Adds `try-catch` in fetching PDF in `pdf_viewer.js` 
- **Note:** The error, `TypeError: Failed to fetch` can occur due to various reasons, and I'm unable to find that out in this case, so this is an attempt to quiet the issue
- Reproduce the issue, either by giving an incorrect PDF URL [here](https://github.com/mitodl/ocw-hugo-themes/blob/34c8d845206be69db959704b74c488b7cea6647b/base-theme/assets/js/pdf_viewer.js#L7) or via any other way. (e.g: If you try to hit any `HTTPS` endpoint from your `localhost`, you will end up in a CORS issue along with `TypeError: Failed to fetch`. The error should also be logged in sentry.
- Checkout this branch.
- Repeat the above steps to reproduce the issue.
- Verify that now the issue/exception …
=> fix: catching exception while fetching PDF

base-theme/assets/types/videojs-youtube.d.ts, course/assets/course.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/701 (Not sure if this PR will close it or not as this PR is more of a hit-and-trial. Please see some points below)
- **Note:** I was unable to reproduce this issue locally, but most likely, this issue is occurring from a third party, i.e: `videojs-youtube` and if this is the case, then I think loading this lib inside `document.ready` function can do the job. Still, I'm not very sure that this will fix the issue so this PR can be considered a hit-and-trial PR. Not sure if this is a good approach/practice.
- Replaces `import` with `require` for `videojs-youtube`
- Moves `require("videojs-youtube")` inside `document.ready` function.
- Declare module `videojs-youtube`
- Try to reproduce the issue (if you succeed in that, then I owe you a …
=> fix: videojs-youtube lib included inside document.ready function

course/assets/css/video.scss
Closes #739
- Adds css to dynamically reduce font size on screen decrease.
- Verify title for the video gallery does not overlap on mobile screens.
=> added styles to fix title overlap

base-theme/layouts/partials/seo.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/755
In https://github.com/mitodl/ocw-hugo-themes/pull/726, we set the `seo.html` partial to use the metadata `description` property of pages to render a `meta` tag with `name="description"` for parsing by Google and other search engines.  This didn't handle the case of course home pages, which store their description in `.Site.Data.course.course_description`.  This PR detects if the home page is being rendered and attempts to fetch the description from there instead.
- Clone any course repo from `ocw-content-rc`
- Set the following in your `.env`:
```
COURSE_CONTENT_PATH=/path/to/ocw-content-rc/
OCW_TEST_COURSE=<test course folder name>
RESOURCE_BASE_URL=https://live-qa.ocw.mit.edu/
```
- Run the course site with `npm run …
=> render course home page description

base-theme/layouts/partials/seo.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/766
This PR makes it so that every page generated when using a theme that uses `base-theme` will deposit a `link` element with `rel="canonical"` and an `href` equal to the permalink of the current page.  This instructs search engines like Google that the page we are generating here in the Hugo build should be the user selected canonical URL for the content generated in that page as detailed here: https://developers.google.com/search/blog/2013/04/5-common-mistakes-with-relcanonical
Render a course or `ocw-www`, visit http://localhost:3000/ and bring up the page source.  If you search the source for "canonical" you should come up with the `link` element described above, and the URL there should be the URL for the current page.  Note …
=> user selected canonical URL

www/assets/js/lib/api.ts, www/assets/js/lib/util.ts
Closes https://github.com/mitodl/ocw-hugo-themes/issues/736
- Sends additional data for better debugging when search API fails.
- Tags added: 
1. API response status
2. API response status text
3. Current URL with query params
- Level set to "Error"
- Extras: Search Query Params
- **Note:** I spent some time but was unable to debug the actual cause of why the issue is occurring in the first place. Hence the error message has been improved by which I think we will be in a better position to debug the issue.
- Go to the search page. (If having CORs issue then [run chrome without cors](https://alfilatov.com/posts/run-chrome-without-cors/))
- Test and verify that everything is working as expected.
- Now we want the API to fail, this can be done by any method (give an invalid URL, let the code …
=> search API error handling improved

course/layouts/lists/single.html
Closes #757 
Adds theme for resource lists.
This PR can be tested in the following manner
- Clone the following course https://github.com/OCW-LOCAL-COURSES/resource-list-test
- OR use the the following configuration to create a resource list https://github.com/mitodl/ocw-hugo-projects/blob/wassaf/196-add-resource-bundlet-to-ocw-course/ocw-course/ocw-studio.yaml
- Visit list/{title-of-resource-list}/
- Verify design is as required
This PR is a duplicate of https://github.com/mitodl/ocw-hugo-themes/pull/760 since recent changes in master are breaking the older PR.
=> Added theme for resource list

course/assets/course.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/770
- Moves `require("videojs-youtube")` outside the load function 
- Open any course which has videos and open any video page.
- Check if you have this error `No compatible source was found for this media.`
- If not, then you can reproduce this error by delaying the loading of `videojs-youtube` (maybe call the require in a [settimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) after 1 second or so)
- Now the issue is reproduced, I think (but not very sure) it is occurring intermittently due to the requiring of package here in this load function along with the calling of all those functions which uses this as a dependency.
- Verify that the error does not occur again.
- Verify that all the …
=> fix: import order of videojs-youtube sorted

course/layouts/lists/single.html, course/layouts/partials/resource_list.html
No ticket
Adds feature to maintain resource list order
- Clone the following [course](https://github.mit.edu/ocw-content-rc/3.21-spring-2006)
- Verify resource list is rendered in the order it was added in the course
In the following [PR](https://github.com/mitodl/ocw-hugo-themes/pull/775), we added support for `resource-list`. Which are essentially a curated list for resources created by the author. This PR adds a feature to maintain their order (as they were added by the author in the resource-list tab in ocw-studio).
=> added code to maintain order of list

course/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/796
This PR fixes an issue with an incorrect URL to the Mathjax `tex-svg.js` file.  The `/static` prefix was missing, and this PR simply adds it.
- Clone any course from `mitocwcontent`
- Configure your `.env` to point to the course:
```
COURSE_CONTENT_PATH=/path/to/mitocwcontent
OCW_TEST_COURSE=<test course folder name>
```
- Start the course with `npm run start:course
- Visit http://localhost:3000 and pull up your browser's developer tools, verify that there are no 404 errors in the console
=> fix mathjax url on course home pages

course-v2/layouts/partials/course_description.html, course/layouts/home.html
Closes #815 
Adds check to home.html and course description partial to verify if description is available.
- Start ocw-hugo-themes course
- Remove course description in course.json
- Verify hugo doesn't crash
=> added safeguard for course description

.github/workflows/deploy.yml
- None
- A flag `overwrites-pull-request-comment` was set to `true` in this PR https://github.com/mitodl/ocw-hugo-themes/pull/809/ to avoid/stop the bot from posting new comments on every commit. As ideally, there should be only initial netlify comments which should be overridden on every commit instead of new comments. But it turns out that the bot is posting only 1 comment and overriding/edititing it for `www`, `course`, and `course-v2`. [Example](https://github.com/mitodl/ocw-hugo-themes/pull/820#issuecomment-1211902434). Hence that change is being reverted.
- As suggested [here](https://github.com/mitodl/ocw-hugo-themes/pull/824#discussion_r946099853), we can combine and show all the deployment links in 1 comment instead of having 3 separate comments. This has been achieved by …
=> Netlify deployment: www, course, course-v2 comment

course-v2/assets/css/course-home.scss, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/811
- Makes the height of all 3 sections on CHP the same.
- Makes the height of the sidebar section and the content section on interior pages the same.
- Increases the width of the course image section on the home page.
- Replaces bootstrap classes on sections of CHP and interior page with custom CSS to achieve more precision in section's widths.
- Build any v2 course locally or view [netlify course v2](https://ocw-hugo-themes-course-v2-pr-814--ocw-next.netlify.app)
- Verify the above-mentioned points on multiple browsers and screen dimensions. Also compare it with the [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467361595/preview)
=> sidebar and image section height and width styling

course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html, course/layouts/_default/baseof.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/840
In https://github.com/mitodl/ocw-hugo-themes/pull/832 we added the `course-offline` theme with the goal of rendering a site using the `course` or `course-v2` theme that can be browsed from a local filesystem on any computer, even without an internet connection. Relative URLs are used as part of this, because when a user opens a course site on their local machine, the base URL will be prefixed with whatever the path is to the files on their local machine. Therefore, links need to be relative to work. The course banner is currently rendered using `partialCached` to save a small amount of rendering time, but this creates a situation where a cached link to the home page is rendered on sub-pages and ends up pointing to the wrong …
=> fix course banner link in course-offline theme

www/assets/js/LearningResources.ts, www/assets/js/components/Facet.tsx, www/assets/js/components/FacetDisplay.test.tsx, www/assets/js/components/FacetDisplay.tsx, www/assets/js/components/FilterableFacet.tsx, www/assets/js/components/SearchPage.test.tsx, www/assets/js/components/SearchPage.tsx
closes https://github.com/mitodl/ocw-hugo-themes/issues/845
Moves department to the top in the course search
Makes facets collapsed by default 
run ocw-www and go to the search page. Check that this PR does the above and doesn't break anything
=> collapse facets and move department to top

course-v2/assets/js/navigation.js, course-v2/layouts/partials/nav_item.html, course/assets/js/navigation.js, course/layouts/partials/nav_item.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/849
This PR expands on the functionality in `navigation.js` that's responsible for maintaining the "selected" state on nav items as well as expanding collapsed sections of the nav on page load if you are viewing a page that is in a collapsible nav section. Previously, if you selected a parent in the nav menu, the children would remain collapsed. This PR fixes that so that when you select a parent in the nav menu, the children are expanded.
- Clone a course with nested menu items, such as https://github.mit.edu/mitocwcontent/18.01sc-fall-2010
- Point to the course using your env:
```
COURSE_CONTENT_PATH=/ptah/to/mitocwcontent`
OCW_TEST_COURSE=18.01sc-fall-2010
```
- Spin up the course with `npm run start:course`
- Click one of the nav …
=> expand parent nav item when selected

base-theme/layouts/_default/_markup/render-link.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/848
- Removes trailing newline from `render-link.html`
- View any course which has either comma, period after a link (as shown in the issue ticket) or visit `/pages/get-started/` on www.
- See these unnecessary spaces: 
- <img width="363" alt="image" src="https://user-images.githubusercontent.com/93309234/191737050-69d1fd56-9177-4825-8245-0440ecab0d33.png">
- <img width="152" alt="image" src="https://user-images.githubusercontent.com/93309234/191737084-556675bd-cded-4ca7-9a64-f50e9c92c04c.png">
- Checkout this branch.
- Now verify that the unnecessary spaces are no more.
=> fix: new line removed

base-theme/layouts/partials/page_url.html, base-theme/layouts/partials/video_embed.html, base-theme/layouts/shortcodes/resource.html, course-offline/layouts/partials/page_url.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/852
The "view video page" links on embedded videos currently use `.Permalink` to form the link to the video page. The offline theme needs to use a relative link. Since this link is generated in the context of a shortcode, `.RelPermalink` doesn't work properly because the shortcode doesn't have a template rendering context. This PR reworks how the URL is generated in the offline theme to use a method consistent with the way the rest of the offline theme works, using `path_to_root.html` and appending the URL onto that.
- Clone `ocw-hugo-themes` on this PR branch, `ocw-hugo-projects`, and https://github.mit.edu/mitocwcontent/18.01sc-fall-2010
- Set the following `.env` variables:
```
STATIC_API_BASE_URL=https://ocw.mit.edu/ …
```
=> rework video_embed to properly generate links to video pages offline

README.md, base-theme/assets/webpack/webpack.common.js, package.json, yarn.lock
First step toward #856 
This adds [`webpack-bundle-analyzer`](https://www.npmjs.com/package/webpack-bundle-analyzer).
1. Run `yarn run build:webpack`. The project should build. Nothing new.
2. Run `WEBPACK_ANALYZE=true yarn run build:webpack`. The project should build and an analysis of the build should open in your browser. Cool. The analysis shows dependencies and looks like this:
=> add webpack bundle analyzer

course-v2/assets/css/course-home.scss, course-v2/assets/css/course-image-section.scss, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/853
- Removes custom CSS for the sections/cols in CHP and restores bootstrap cols
- Go to course home page
- Verify that everything, including the 3 sections, looks fine.
- Go to interior page
- Verify that everything looks fine.
- Repeat the above step for multiple screen sizes and browsers.
=> bootstrap col restored

base-theme/layouts/partials/header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/870
In https://github.com/mitodl/ocw-hugo-themes/pull/850, we added some functionality that detects if you are online or offline when displaying an offline course site locally. This included some refactoring on the header partial, and the wrong link was accidentally put onto the give now button. This PR corrects that.
- Click the Give Now button and make sure it goes to the right place
=> fix give now link

base-theme/layouts/shortcodes/resource.html
https://github.com/mitodl/ocw-hugo-themes/issues/882
Reverts a change to the resource shortcode introduced in #859 
This PR can be tested with any course that has an image `{{< resource >}}`. The descript uses 1.74-fall-2020, but any course will do.
1. Clone https://github.mit.edu/mitocwcontent/1.74-fall-2020 into your ocw-content directory and set `OCW_TEST_COURSE="1.74-fall-2010`
2. On hugo-themes **main** branch:
1. `npm run start:course` 
2.  view http://localhost:3000/pages/instructor-insights/teaching-the-uncertainty/
3. Check that the image above "An anti-GMO mural." (see below) has src just equal to `RESOURCE_BASE_URL`
3. Repeat on this branch. The image src should now be correct:
I'm not sure if this change was introduced in #859 intentionally or not. If it was, it had to do with …
=> revert image context change

base-theme/layouts/_default/_markup/render-link.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/848
- Removes leading spaces/newlines for links
- Trailing space/newlines were removed in https://github.com/mitodl/ocw-hugo-themes/pull/858
- Go to any course ([example](https://github.mit.edu/mitocwcontent/17.810-spring-2001)) which has links wrapped up in `""`, `()`, `,`, `.` etc OR edit markdown of any course and manually add/wrap links to reproduce this issue.
- Verify that there is no leading and trailing space around the link.
On main branch: 
On this branch:
=> fix: leading new lines removed from link

base-theme/assets/css/button.scss, course-v2/assets/course-v2.ts, course-v2/assets/css/course-description.scss, course-v2/assets/css/course-v2.scss, course-v2/assets/js/course_expander.ts, course-v2/layouts/partials/course_description.html, course-v2/layouts/partials/link_button.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/864
In https://github.com/mitodl/ocw-hugo-themes/pull/330 we added some functionality to add a collapse / expand arrow to the course description using a JS / CSS based solution. This ended up being confusing for users, and a new approach (invision design link in the issue above) to use an inline link with the text "Show more" at the end of truncated text. This PR implements that using Hugo's [`truncate`](https://gohugo.io/functions/truncate/) function to truncate the description if it's over 320 characters long. This was the character threshold determining whether the expand / collapse should be initialized on the description in the CSS based method, so I stuck with that. Both the truncated and full description (with expand / …
=> show more / show less for course description

course-v2/assets/css/course-v2.scss
closes https://github.com/mitodl/ocw-hugo-themes/issues/873
- Removes some CSS for specific screen sizes which makes the course content expand fully. 
- Verify that course content remains in a max-width container regardless of the screen size.
- Verify this change has no side-effects.
- This media query CSS was added in [Compact Design PR](https://github.com/mitodl/ocw-hugo-themes/pull/784) and I remember I received a word document consisting of some CSS to be added for the `course-v2` theme, it also included this media query CSS which was added back then. I have no idea what was the thought process/agenda for adding this media query and allowing content to expand fully on some screen sizes. 
But now it seems like a bug hence removing it.
=> fix: wrapping content in a max width

base-theme/assets/css/variables.scss, base-theme/static/images/expand.svg, course-v2/assets/css/course-nav.scss, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html, course-v2/layouts/partials/course_info_toggle.html, course-v2/layouts/partials/mobile_nav_toggle.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/877
- Updates buttons for mobile design for course-v2.
- Set screen size of tablet or mobile.
- Verify that `Menu` button and `More Info` link are according to the design provided in issue ticket.
- Verify that both work as expected.
- Verify that they are hidden on large screens.
- Verify that they are completely responsive.
- Verify that there is no change/affect/impact on course-v1 theme.
- Any other use-case that needs to be tested.
=> style: menu button & more info link mobile design

course-v2/assets/js/responsive_tables.ts, course-v2/layouts/partials/responsive_tables_js.html, course/assets/js/responsive_tables.ts
- #875 
- #835 
This PR makes v2 tables sensitive to resizing. We did something similar for v1 tables in https://github.com/mitodl/ocw-hugo-themes/pull/844. Additionally, this settles the "cannot read property of XYZ of null" issue noted in #875
Running the v2 theme:
1. Visit any page. Replace its markdown content with Replace it with https://gist.github.com/ChristopherChudzicki/dd0d177987b2baf219dfb9b2f351a097
2. View the hugo build for that page. Resize the window and toggle course info (upper right). The tables should resize appropriately.
**Note:** The jumping in content width is fixed in #889  
https://user-images.githubusercontent.com/9010790/194137152-8d15d3bf-0fea-4ee0-badb-27cd14858594.mov
=> Responsive tables for course-v2

base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss, base-theme/static/images/left_arrow.svg, course-v2/assets/css/course-info.scss, course-v2/assets/css/course-nav.scss, course-v2/layouts/_default/baseof.html, course-v2/layouts/partials/course_info.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/863
- Removes the old `show course info` button.
- Adds a new icon (left arrow) button. 
- Verify that when you close the course info drawer, a left arrow icon is shown instead of text button.
- Verify that this icon works as expected and open the course info drawer on clicking.
- Verify that this change is only applied on large screens and mobile view and functionality is unaffected.
- Test this on multiple screens sizes and on multiple browsers. 
- Verify that all the points mentioned in the acceptance criteria of issue ticket are fullfilled.
https://user-images.githubusercontent.com/93309234/193028305-0d18aff5-796c-44fb-9f73-5c6c823c1f95.mov
=> style: "show course info" button replaced with an icon

base-theme/assets/css/variables.scss, base-theme/layouts/partials/video_embed.html, course-v2/assets/css/video.scss
closes https://github.com/mitodl/ocw-hugo-themes/issues/865
- Sets max-width for video player (for both, embedded videos and video page)
- Checkout this branch or view netlify deployed version
- Build any course locally which has videos
- Verify that the video player section is not too big and fitted in your screen size with the transcript widget being visible.
- Verify that the video player section width remains same/does not change when you toggle (open/close) course info drawer.
- Verify these points for both, embedded videos and video pages.
Uploading video player section max width.mov…
=> style: max width for video player section

base-theme/layouts/partials/mathjax_if_necessary.html, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html, course/layouts/_default/baseof.html, course/layouts/home.html, www/layouts/_default/baseof.html
https://github.com/mitodl/ocw-hugo-themes/issues/905
This PR switches us to including Mathjax only on pages that use it.
First, load https://ocw.mit.edu/courses/11-382-water-diplomacy-spring-2021/ and view network tab. Observe that a file called `tex-svg.js` is downloaded.
Now on this branch:
1. Load any course page without math. No `tex-svg.js` should be downloaded.
2. Edit the markdown to include `\\(E=mc^2\\)` OR `\\[E=mc^2\\]`. `tex-svg.js` should now be downloaded.
3. Repeat (2) for site pages, site homepage, on v1, v2, and www theme.
=> only load mathjax if necessary

.eslintrc, base-theme/assets/js/sentry.ts, base-theme/assets/types/global.d.ts, base-theme/assets/webpack/webpack.common.js
#875 
This PR sets the release tag on our sentry configuration to match the release tag in package.json.
1. `yarn run start:course` (or www)
2. in the developer console, manually `throw new Error("<yournamehere> is testing chris's PR")
3. Check the sentry logs at https://sentry.io/organizations/mit-office-of-digital-learning/issues/?project=5304953&statsPeriod=1h ... you should see your error show up within a few minutes (I think?).
4. In the "tags" section near the top (or on right hand side) there should be a "release" tag with a number matching our package.json.
_I believe we log all errors...if your error doesn't show up, maybe try a few more times._
We recently fixed the sentry error in #875 , but a few of them are showing up. (Dozens per day rather than hundreds of thousands.) I'm …
=> Log release version in sentry errors

course-v2/assets/css/drawer.scss, course-v2/layouts/partials/mobile_course_info.html, course-v2/layouts/partials/mobile_course_nav.html, course/assets/css/drawer.scss, course/layouts/partials/mobile_course_info.html, course/layouts/partials/mobile_course_nav.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/896
- Sets max-width for course menu and info drawers, in both course (v1, v2) themes.
- Please follow the steps mentioned in the issue ticket to reproduce the issue and verify the fix on this branch.
=> fix: max-width for drawers

base-theme/layouts/partials/header.html
closes https://github.com/mitodl/ocw-hugo-projects/issues/217
- Fixes a type in mobile navbar: `Contact us` changed to `About OCW`
- Build any course or www OR view netlify deployed version
- Set screen size to mobile
- Click the hamburger and verify that the 2nd link is `About OCW` which redirects to the correct about page
=> fix: typo in mobile navbar

course-v2/assets/css/course-info.scss, course-v2/layouts/partials/course_info_toggle.html, course-v2/layouts/partials/mobile_course_info.html, course-v2/layouts/partials/mobile_course_nav.html
part of https://github.com/mitodl/ocw-hugo-themes/issues/895
- Adds close (x) button to course menu drawer which closes the drawer when clicked.
- Adds close (x) button to course info drawer which closes the drawer when clicked.
- Note: This change is only done on `course-v2` theme.
- Build any course on `course-v2` theme or view netlify deployed version
- Make the size of screen small so that course menu and info buttons show up. 
- Verify that both, the course menu and info drawers, when opened, have a close button, which closes the drawer when clicked.
https://user-images.githubusercontent.com/93309234/196175954-be19e0fa-005f-411c-98e9-9add14f11457.mov
=> feat: close course menu & info drawers with x button

course-v2/layouts/partials/get_instructors.html, course/layouts/partials/get_instructors.html
#924 
Fixes the instructor search link on OCW course home pages
I wrote the instructions as if for [8.06-spring-2018](https://github.mit.edu/mitocwcontent/8.06-spring-2018), but any course with at least one instructor will work.
1. Visit https://ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/. Right-click the instructor link and inspect the link URL. It is https://ocw.mit.edu/search?t=Prof.+Barton+Zwiebach. Note the `t=` in search parameters. "t" is for topic. Martin Zwiebach is not a topic. The search param should be "q=...".
2. **Test for course theme**: Set your env var for `COURSE_HUGO_CONFIG_PATH` to point to `/ocw-hugo-projects/ocw-course/config.yaml`
3. `yarn start:course` and visit the course homepage
4. Right-click the instructor link and note that the search param is …
=> fix instructors search link on course home page

course-v2/assets/course-v2.ts, course-v2/assets/js/mobile_course_drawers.ts
closes https://github.com/mitodl/ocw-hugo-themes/issues/895
- Makes the course menu drawer swipe-able such that it can be closed by swiping
- Makes the course info drawer swipe-able such that it can be closed by swiping
- Does it by adding `touchstart` and `touchend` event listeners
- Build any course on v2 theme or view [netlify deployed version](https://ocw-hugo-themes-course-v2-pr-928--ocw-next.netlify.app/)
- Go to mobile screen on any course page.
- open course menu drawer, swipe it to left, and verify that it is closed smoothly by swiping
- open course info drawer, swipe it to right, and verify that it is closed smoothly by swiping
- Ideally: Open the netlify deployed version on your mobile, and test it there. …
=> feat: close mobile course drawers via swiping

base-theme/layouts/partials/mathjax_if_necessary.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/932
In https://github.com/mitodl/ocw-hugo-themes/pull/906, we introduced a change that conditionally loads MathJax. This new partial, `mathjax_if_necessary.html`, calls `webpack_url.html`. The Hugo `.` object is passed as the `context` parameter, when the context being passed to `mathjax_if_necessary.html` itself is stored in `.context`. This same object should be passed on as the context object, not the parameter dict itself.
- Clone https://github.mit.edu/mitocwcontent/res.8-004-january-iap-2015
- Clone [`ocw-hugo-projects`](https://github.com/mitodl/ocw-hugo-projects)
- Run `npm run build /path/to/mitocwcontent/res.8-004-january-iap-2015 /path/to/ocw-hugo-projects/ocw-course-v2/config-offline.yaml
- Verify the build completes …
=> pass .context to webpack_url in mathjax_if_necessary

base-theme/assets/css/variables.scss, course-v2/assets/css/course-resources.scss, course-v2/layouts/learning_resource_types/taxonomy.html, course-v2/layouts/partials/resource_list_collapsible.html, course-v2/layouts/partials/resource_list_item.html, course-v2/layouts/partials/resources_header.html, course-v2/layouts/partials/see_all.html, course-v2/layouts/partials/show_no_resources_found.html, course/layouts/partials/nav_item.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/929
This PR does the following:
- Adds a "download course" button to the `/resources` page on every course with the URL being the base URL plus the course short id as the ZIP filename
- Turns the resource lists into collapsible lists
- Makes sure that the Lecture Videos are always on the top and expanded by default
- Make sure other resource lists are collapsed by default
This PR is best tested by running `ocw-studio` locally and mocking out the publishing environment, so you can generate the ZIP files and the live course sites the same way they would be in RC and production:
- Clone `ocw-studio` on the `cg/offline-build-short-id-zip-filename` branch
- Make sure you've taken care of the following prerequisites:
- Minio support …
=> course download button desktop

yarn.lock
This updates the `caniuse-lite` version.
Closes https://github.com/mitodl/ocw-hugo-themes/issues/936.
Check that `npm run start:course`, `npm run start:www`, and `npm run build:webpack` all run without warnings about the `caniuse-lite` version.
=> Updating caniuse-lite version

course-v2/content/learning_resource_types/_index.md, course-v2/content/resources/_index.md
Part of https://github.com/mitodl/ocw-hugo-themes/issues/938
In [this](https://github.com/mitodl/hq/discussions/92) discussion, it was decided that the resource index page would be generated via a taxonomy based on `learning_resource_types`. As part of that work, the root taxonomy page was mounted at `/resources` so it had the same root as the rest of the resource pages. As part of https://github.com/mitodl/ocw-hugo-themes/issues/938, it is expected that this page will be available at `/download` instead. This PR changes the `url` property of the `learning_resource_types` taxonomy so it is rendered at `/download` instead of `/resources` and adds a markdown file at `course-v2/content/resources/_index.md` with some front matter that prevents Hugo from automatically trying to render an index …
=> rename /resources to /download

course-v2/assets/css/course-resources.scss, course-v2/layouts/partials/resources_header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/943.
Modifies the mobile layout of the download button and related text, so that there is no overlap between the button and the text.
Start the course with `yarn start:course` and verify that the layout looks as expected in both desktop (unchanged by this PR) and mobile views. It may be necessary to first delete the `public` subfolder in the course content, to make sure that no prior layouts are cached.
=> Resizing download button layout for mobile

.github/workflows/deploy.yml
None
Changes the `deploy.yaml` ci workflow to build webpack once, then copy it to the appropriate places, rather than building it three times.
View the netlify builds below. The webpack assets (css styles, etc) should load.
=> build webpack once, not thrice

package.json, www/assets/css/learning-resource-card.scss, www/assets/css/search.scss, www/assets/js/components/SearchFilterDrawer.tsx, www/assets/js/components/SearchPage.test.tsx, www/assets/js/components/SearchPage.tsx, www/assets/js/lib/constants.ts, yarn.lock
https://github.com/mitodl/hq/issues/79
This pr unhides the toggle for the compact search view to enable the feature. This pr is currently up to test https://github.com/mitodl/course-search-utils/pull/45 which needs to be merged first. The test failure should be fixed by updating course-search-utils.
=> Ab/set compact UI live

course-v2/layouts/partials/resources_header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/937
In https://github.com/mitodl/ocw-hugo-themes/pull/931, we added a "course download" button to the resources download page with a URL based off the work done in `ocw-studio` to create Concourse pipelines that build offline versions of each course and ZIP them up. This PR makes the visibility of that download conditional on Hugo being able to make a `HEAD` request against the ZIP URL to confirm its existence.
- Clone any course you want from https://github.mit.edu/mitocwcontent/ and point to it in your env using `COURSE_CONTENT_PATH` and `OCW_TEST_COURSE`
- Clone `ocw-hugo-projects` on the `cg/allow-head-zip` branch
- In `ocw-hugo-projects/course-v2/config.yaml`, we need to temporarily set the `baseUrl` setting to …
=> only show download button if zip exists

.env.example, .github/workflows/deploy.yml, README.md, www/layouts/partials/new_course_cards.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/956
In https://github.com/mitodl/ocw-studio/pull/1560, we deprecated the `OCW_IMPORT_STARTER_SLUG` environment variable's use as a filtering mechanism, which will be finalized in this PR. Going forward, `OCW_COURSE_STARTER_SLUG` will be used to denote the slug of the `WebsiteStarter` object in `ocw-studio` used to create sites to be rendered with the course theme. Currently this is used when querying the `ocw-studio` API for new courses.
- Clone `ocw-hugo-themes` on the `cg/ocw-course-starter-slug` branch
- Point at `ocw-hugo-projects` on the branch of the same name using the `WWW_HUGO_CONFIG_PATH` and `COURSE_HUGO_CONFIG_PATH` env variables
- Replace `OCW_IMPORT_STARTER_SLUG` with `OCW_COURSE_STARTER_SLUG` in your env and make sure …
=> rename OCW_IMPORT_STARTER_SLUG to OCW_COURSE_STARTER_SLUG

course-v2/layouts/partials/resources_header.html
Reverts mitodl/ocw-hugo-themes#960
During testing I found that this solution doesn't quite work in our deployed environments because `baseUrl` is root-relative. `resources.GetRemote` doesn't have the context to make the request to the file, so the link will never be shown.
=> Revert "only show download button if zip exists"

course-v2/layouts/partials/resources_header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/937
This PR revises the code in https://github.com/mitodl/ocw-hugo-themes/pull/960. Instead of manually constructing the `short_id` from info already in the course metadata, the `short_id` was explicitly added to JSON files published by `ocw-studio` (https://github.com/mitodl/ocw-studio/pull/1566) and that is being used instead. This was done because `short_id` is customizable upon site creation and the OCW team has changed their format, and may do so again in the future. This is the most foolproof way to ensure that the link to the ZIP archive of a given course is correct.
Testing this is a little bit tricky, since `hugo server` overrides any `baseUrl` setting to be prefixed with `//localhost:3000/`. We need to make a tiny edit for …
=> hide download button if zip doesn't exist v2

base-theme/layouts/partials/content_header_v2.html, course-v2/layouts/partials/course_content.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/955
ref: https://github.com/mitodl/ocw-hugo-themes/issues/955#issuecomment-1301280575
- Removes expand/collapse arrow
- Full content title shown
- Checkout this branch or view netlify deployed version
- Go to resources/courses page which have long titles
- Verify that full title is being shown
=> fix: expand/collapse arrow removed and full title shown

www/layouts/educator/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/989.
Updates text on the Educator page, as requested in the issue description.
Run `yarn start www`, and then navigate to `http://localhost:3000/educator/`. Verify that the text in the `Share Your OER Adaptations` section has been updated.
=> Updating text on Educator page

course-v2/layouts/partials/contains_videos.html, course-v2/layouts/partials/resources_header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/999
In https://github.com/mitodl/ocw-hugo-themes/pull/979, we added the "download course" link button to the course home page and course info drawer. Some courses either do not have videos or do not have the videos tagged with `learning_resource_type` taxonomy tags, causing no videos to appear on the download page. The messaging next to the download button indicates that videos can be downloaded below, when on these courses that is not the case. This PR removes this messaging if no videos are detected in the course.
- Make a temporary edit to `resources_header.html` and change `{{- $zipExists := partial "file_exists_at_url.html" (dict "context" . "url" $downloadCourseUrl ) -}}` to `{{- $zipExists := true -}}`. This is necessary …
=> hide text about video / audio materials if they aren't detected

course-v2/assets/css/videojs_player.scss, course/assets/css/videojs_player.scss
Removes defined width so that the timestamp will always display on a single line in the video player.  Also removes the padding specified which made the volume slider and time elapsed hit each other.
https://github.com/mitodl/ocw-hugo-themes/issues/982
Ensures that the video duration is completely displayed when the time is X:XX:XX.
1. Pull this branch.
2. gh repo clone github.mit.edu/ocw-content-rc/18.s096-fall-2013.
3. Set `OCW_TEST_COURSE=18.s096-fall-2013` in your .env file for `ocw-hugo-themes`.
4. Run `yarn start course` from the root directory of `ocw-hugo-themes`.
5. Navigate to http://localhost:3000/resources/lecture-1-introduction-financial-terms-and-concepts/ and ensure that the video duration is correctly displayed.
6. Activate the volume slider and ensure it does not overlap …
=> Display time on single line, don't clash with vol

.gitignore, env.ts, package.json, package_scripts/start.ts, package_scripts/util.ts, test-sites/__fixtures__/README.md, test-sites/__fixtures__/courses/ocw-ci-test-course/data.json, test-sites/__fixtures__/ocw-ci-test-www/instructors/3caa0884-4fdd-4f3c-ba39-67a64c27d877/index.json, test-sites/__fixtures__/ocw-ci-test-www/instructors/588e4e64-823f-4e8e-a29e-0e695e2297ae/index.json, test-sites/__fixtures__/ocw-ci-test-www/instructors/d3c64374-bb1c-46bb-a1a1-827c336e4d8e/index.json, test-sites/ocw-ci-test-course/data/course.json, test-sites/ocw-ci-test-www/content/course-lists/featured-courses-homepage.md, test-sites/ocw-ci-test-www/content/instructors/3caa0884-4fdd-4f3c-ba39-67a64c27d877.md, test-sites/ocw-ci-test-www/content/instructors/588e4e64-823f-4e8e-a29e-0e695e2297ae.md, test-sites/ocw-ci-test-www/content/instructors/d3c64374-bb1c-46bb-a1a1-827c336e4d8e.md, tests-e2e/fixtures.spec.ts, tests-e2e/global-setup.ts, tests-e2e/ocw-ci-test-course/homepage.spec.ts, tests-e2e/ocw-ci-test-course/shortcodes.spec.ts, tests-e2e/ocw-ci-test-www/featured_courses.spec.ts, tests-e2e/util/SimpleServer.ts, tests-e2e/util/WwwPage.ts, tests-e2e/util/index.ts, tests-e2e/util/locators.ts, tests-e2e/util/test_sites.ts, yarn.lock
#980 
Previously the e2e tests were pulling in a fair amount of data from RC (e.g., featured courses, instructors, images, new courses). Now we set `STATIC_API_BASE_URL` to a local value, so the e2e test sites are built more in isolation.
Some data is still being pulled from RC (e.g., "New Courses" and images). The infrastructure in this PR should also be helpful for dealing with that. _Although, using RC images may be desirable._
I also changed a bit how the `global-setup.ts` file serves the sites. Previously each site was served by a separate http server. Now all sites are served by one server, so behaves much more like rc/prod.
`yarn test:e2e` should pass locally and on its github action.
Start with [test-sites/__fixtures__/README.md](https://github.com/mitodl/ocw-hugo-themes/blob/a92d4 …
=> Better isolate e2e sites from RC + add featured courses

base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss, course-v2/assets/css/course-v2.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/991
- Updates titles/headings font-sizes according to the updated [style guide](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/468374061/preview?scrollOffset=63.5)
- Note: rem values in this PR and style guide are different, because: in style guide, it's assumed that the root font size is 16px so rem values are calculated accordingly, but in actuality, the root font size for course theme is 14px and for www theme is 16px (px values should be the same)
- Build any course or view the netlify deployed version
- Visit several pages where and verify that all headings are according to the style guide.
=> style: titles style updated

package_scripts/start.ts
None
- Removes absolute cache directory path since Hugo already defaults it to `$TMPDIR/hugo_cache/` 
- Go to main branch
- Build www (yarn start www)
- See that the build fails since this path is hardcoded and absolute
- Build www 
- Verify that the build is successful
=> fix: removing absolute cache directory path

base-theme/assets/index.ts, base-theme/assets/js/polyfill.ts, package.json, www/assets/js/lib/search.ts, yarn.lock
might or might not close https://github.com/mitodl/ocw-hugo-themes/issues/901
- Uses `array-flat-polyfill` for `flat()`
- I'm having a hard time testing this change since we need to reproduce and test this locally on older browser [versions](https://caniuse.com/array-flat) that do not support flat and then verify that this change fixes that
=> fix: array-flat-polyfill added

course-v2/layouts/partials/get_instructors.html
*I should make a ticket, but toward discussion https://github.com/mitodl/hq/discussions/366*
This PR changes / fixes how we handle errors that occur during `get_instructors.html` getRemote call. See comments for details.
On this branch:
1. `yarn start course`. The course should build successfully.
2. **Simulate an error other than 'not found':** (not an error in response) Edit https://github.com/mitodl/ocw-hugo-themes/blob/ccacdd1d4d6969b490481fc2277f58b8d6a0dfbb/course-v2/layouts/partials/get_instructors.html#L5  Change $url to "meow" or some other invalid url. Your course should now fail to build, and you should get a meaningful error. (You might get one per instructor.) *Alternatively, cause an http error any other way you can think of.*
3. Revert the change from step (2).
4. **Now …
=> fail build on get_instructor errors

package_scripts/with-env.test.ts, package_scripts/with-env.ts, tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
#1012 
in #964 we added a `with-env` command that was supposed to behave like [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) but with some improvements. That command should exit with the same exit code as its subcommand, but instead it was always exiting with code 0. Oops.
1. Run the command below... the echo should be "0"
```sh
yarn with-env --dev -- exit 0
echo $?
```
2. Run the command below... the echo should be "1"
```sh
yarn with-env --dev -- exit 1
echo $?
```
3. If you want, introduce an artificial error into some e2e test, like `expect(1).toBe(2)`, and check that `CI=true yarn test:e2e` exits with code 1. (Again, use `echo $?` to check the exit code). *Note: it seems that without CI=true, Playwright will open a browser with a failed test report and never actually exit. …
=> make failing e2e tests fail on ci

base-theme/layouts/partials/featured_course_cards.html, base-theme/layouts/partials/sentry_capture_message.html, fields/layouts/home.html, fields/layouts/subfields/single.html, www/layouts/collections/single.html, www/layouts/course-lists/single.html, www/layouts/partials/new_course_cards.html, www/layouts/partials/ocw_news.html, www/layouts/resource_collections/single.html
#1014 
This PR fixes errors in our error handling and raises the severity of sentry messages.
I don't think it's worth testing all 11 error handlers locally. One thing you could do to test them is:
1.  set your STATIC_API_BASE_URL to some bogus value like "moooooo",
2. Run `yarn start www`, and Hugo should tell you that the URL scheme is not recognized. *Previously, Hugo would tell you something useless like "cannot read property .Err of Error"*.
3. Re sentry, see screenshot below. If you want to test sentry error severity, change our Sentry.init call (sentry.js) to something like:
```js
Sentry.init({
release:     RELEASE_VERSION,
// dsn is not secret
dsn:         "https://eee58f41dda54d2b814296e12dced4b7@o48788.ingest.sentry.io/5304953",
environment: "YOUR NAME HERE"  })
```
and check …
=> Fix .Err errors, elevate sentry severity

www/layouts/partials/new_course_cards.html
#1025 
Changes "New Courses" carousel to have 12 items, which divides nicely into 1/2/3/4 items per page at various widths.
Run `yarn start www` and verify that the New Courses carousel has 12 items and looks good at various widths.
**Note:** The Featured Courses carousel has a number of items determined by OCW authors, via Studio.
=> display 12 new courses, not 10

base-theme/assets/webpack/webpack.prod.ts, tsconfig.json
#1036 
This PR changes our ts+webpack configs to generate sourcemaps during the production builds.
**First:** Verify that this does not noticeably affect the size of the production webpack build.
1. Generate an env file if you don't have one. You can do this with `yarn with-env --dev --print-env '' > .env`. *Most of our commands, e.g., `yarn start course`, run with default environment variables, but **only in development**, and we want to run some production-like commands.
2. Clear your webpack dist folder: `rm -rf base-theme/dist`
3. On `main` branch: run production webpack build `yarn build:webpack`
4. On this branch, run production webpack build: `yarn build:webpack`
5. view the file sizes, `ls -lh base-theme/dist/static/js`. The `.js` file sizes should not be noticeably different. …
=> produce source-maps in prod build

base-theme/assets/css/main.scss, base-theme/assets/index.ts, course-v2/layouts/partials/partial_collapse_list.html, package.json, www/assets/www.tsx, yarn.lock
#1045 
Removes unused dependency + code. The tippy stuff was all removed in #524 and #530 
1. There should be no observable change: Run a course or www and it should behave the same.
2. If you want to double check that we got them all, search for `"tippy"` or `"coming-soon"`. *There is one remaining instance of `"coming-soon"` as a default class in the old course(-v1) theme, which I decided not to touch*.
=> remove unused "Coming Soon" code

tsconfig.json
Related to #1033, #1034
This PR changes the way we compile TS *before* being bundled by webpack: In our tsconfig, we had `module` set to CommonJS, whereas it should be set to ES6 As the Webpack Typescript docs say,
> **Warning**
> `ts-loader` uses `tsc`, the TypeScript compiler, and relies on your `tsconfig.json` configuration. Make sure to avoid setting [module](https://www.typescriptlang.org/tsconfig#module) to "CommonJS", or webpack won't be able to [tree-shake your code](https://webpack.js.org/guides/tree-shaking).
There should be no noticeable changes, other than that the output of `yarn build:webpack` should be a bit smaller.
You could...
1. Check the site still looks ok at on the [netlify builds](https://github.com/mitodl/ocw-hugo-themes/pull/1044#issuecomment-1398735619)
2. If you …
=> better tree-shaking... compile ts to ESM (before bundling)

.pre-commit-config.yaml, .secrets.baseline
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1047
This PR adds a standard pre-commit config to this repo, as it is currently missing one and if you have pre-commit installed you will get an error trying to make commits.
- Clone `ocw-hugo-themes` on this branch
- Add any file and make a test commit
- Verify that you do not get an error message
- Revert the commit (or at least don't push it)
=> add pre-commit config

base-theme/assets/index.ts, base-theme/assets/webpack/webpack.common.ts, base-theme/layouts/partials/head.html, base-theme/layouts/partials/include_css.html, base-theme/layouts/partials/include_js.html, course-v2/assets/course-v2.ts, course-v2/assets/css/course-v2.scss, course-v2/assets/instructor-insights.js, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html, course-v2/layouts/partials/extrahead.html, fields/layouts/_default/baseof.html, fields/layouts/partials/extrahead.html, fields/layouts/partials/extrajs.html, playwright.config.ts, www/layouts/_default/baseof.html, www/layouts/partials/extrahead.html, www/layouts/partials/extrajs.html
https://github.com/mitodl/ocw-hugo-themes/issues/1033
This PR changes how we share common resources between different pages on OCW. The overall approach is to make it less manual and have webpack do more code splitting automatically. See file comments for more, and comments in https://github.com/mitodl/ocw-hugo-themes/issues/1033 for some background.
There should be no noticeable change in behavior, other than smaller bundles. Some things you might do:
- run `yarn start www` and make sure things look ok
- run `yarn start course` and make sure things look ok
- check that videos work!
- run `rm -rf base-theme/dist && WEBPACK_ANALYZE=true  NODE_ENV=production yarn build:webpack` and check out the production bundles
The files that were loaded before/after on sites are (before gzip):
``` …
```
=> Deduplicate webpack assets

course-v2/layouts/partials/video-gallery-item.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1063
This PR sets the `video-gallery-item.html` partial to use the `page_url.html` partial when generating a link to the video page for the video gallery item in question. This was missed in the original work pertaining to the offline theme. Calling the URL through this partial allows the proper URL to be rendered both when building the site using the normal online config as well as the offline config.
- Download the course content repo at https://github.mit.edu/mitocwcontent/9.40-spring-2018
- In `ocw-hugo-themes`, on this branch, run `yarn build /path/to/mitocwcontent/9.40-spring-2018 /path/to/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`, replacing the paths with your own
- In the course content repo folder, browse to the …
=> fix offline video gallery item url

course-offline/layouts/partials/download_course_link_button.html, course-offline/layouts/partials/resources_header.html, course-v2/layouts/partials/course_image_section.html, course-v2/layouts/partials/desktop_course_info.html, course-v2/layouts/partials/mobile_course_info.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1083
This PR changes how the "Download Course" button is rendered in the `course-offline` theme. It doesn't make any sense to render a button that says "Download Course" in an offline course that you have already downloaded. However, the `/download` page is still useful if a course has been tagged with `learning_resource_type` taxonomy tags, as a helpful list of categorized resources will be there. If a course has these tags, a link will still be generated in the course info drawer but it will now say "Browse Resources."
The "Download Course" button and banner that shows up at the top of online courses has been overridden and removed in `course-offline`, because it obviously doesn't make any sense to download a full zipped version of …
=> remove download button from offline site

base-theme/assets/webpack/webpack.common.ts
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1057
This PR changes two webpack rules.
1. Excludes nanogallery fonts from being "unexported".
2. Updates fonts file-loader rule to place nanogallery fonts under `static_shared/css/fonts`. 
1. Clear your browser's cache and disable AdBlock (if any).
2. Open your local clone of [cw-hugo-themes](https://github.com/mitodl/ocw-hugo-themes)
3. Checkout `hussaintaj/1057-gallery-controls`
4. Copy [2.672-spring-2009](https://github.mit.edu/ocw-content-rc/2.672-spring-2009) into your content folder.
5. Set `OCW_TEST_COURSE=2.672-spring-2009` in your .env file. (This should be your course content directory name)
6. Run `yarn start course`
7. Visit `http://localhost:3000/pages/labs/#nanogallery/fd614745-fc1f-6cb1-a422-ffc6befbbdd1_nanogallery2/0 …
=> Fix: Image Gallery Controls Not Rendering

course-v2/assets/js/video_transcript_track.js
Closes https://github.com/mitodl/ocw-hugo-themes/issues/948
This PR updates the video transcript initialization code. The script will now check for text tracks (captions) before it creates the transcript. In case there are no captions, no transcript is created.
To test this change locally, follow these steps.
1. Clone and setup [3.091-fall-2018](https://github.mit.edu/ocw-content-rc/3.091-fall-2018) course.
2. On your local ocw-hugo-themes repo, checkout `hussaintaj/948-type-error`.
3. At https://github.com/mitodl/ocw-hugo-themes/blob/bfdf78acff2583e13585f98bb8e08399ad3a3b73/base-theme/layouts/partials/youtube_player.html#L22
temporarily change `"type": "video/youtube"` to `"type": "video"`.
**Rationale**: Locally, video.js throws an origin error. The exact cause is unknown to me. This …
=> Fix: TypeError on missing transcripts

course-offline/layouts/partials/resource_list_item_title.html, course-v2/layouts/partials/resource_list_item.html, course-v2/layouts/partials/resource_list_item_title.html
Closes #1095 
This PR appends "index.html" to downloaded course resource files to open correctly
- Download the course content repo at https://github.mit.edu/mitocwcontent/18.06-spring-2010
- In ocw-hugo-themes, on this branch, run yarn build /path/to/mitocwcontent/18.06-spring-2010 /path/to/ocw-hugo-projects/ocw-course-v2/config-offline.yaml, replacing the paths with your own
- In the course content repo folder, browse to the dist/download folder and double click on index.html
- Try to click on any link and you should be redirected to the correct path ending in index.html
=> Fix: Bad links on offline Download page

www/assets/css/search.scss
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1093
This PR updates the CSS rules to hide the mobile buttons by default and shows them on mobile view.
1. Navigate to your directory where [ocw-hugo-themes](https://github.com/mitodl/ocw-hugo-themes) is set up.
2. Run `yarn start www`
3. Open `http://localhost:3000/search`
4. Open brower's Developer Tools and open device toolbar. Change the website's size gradually and observe the change. See the video attached below for reference. You should always see only one set of layout buttons.
https://user-images.githubusercontent.com/71316217/222415712-be7b1d3a-645d-41dd-9190-4cf0ebb0f5a4.mov
=> Fix: Search page has double thumbnail/compact buttons on mobile

base-theme/assets/webpack/webpack.common.ts, base-theme/layouts/shortcodes/image-gallery.html, course-v2/assets/course-v2.ts, course-v2/assets/nanogallery2-imports.js
#648 
This PR implements lazy loading for nanogallery2 using dynamic import. It also uses promise-polyfill for IE11 support.
This PR requires testing both i) videoJS ii) nanogallery2
Since the issue number is same for videoJS (and the nature of work too), therefore I just made the changes here instead of opening a new PR.
The testing for videoJS:
1. Checkout this branch.
2. Clear your cache
3. Get this course: [9.40-spring-2018](https://github.mit.edu/ocw-content-rc/9.40-spring-2018)
4. In your .env file, `OCW_TEST_COURSE=9.40-spring-2018`
5. `yarn start course`
6. Go to "[Lecture Videos](http://localhost:3000/video_galleries/lecture-videos/)"
7. Play any video. Make sure it plays.
**To test for Internet Explorer 11:**
1. Login to browserstack live.
2. Select Internet Explorer 11
3. Use …
=> feat: lazyloading for nanogallery2 using dynamic import

tsconfig.json
Closes #1114
This PR sets an output directory (`outDir`) in `compilerOptions` with exclude path so that the compiled Javascript files will not attempt to overwrite the input files which were previously placed right next to the input files with the same names.
2. Run `npx tsc --build`
3. Observe that there are no errors reported.
=> fix: tsconfig.json errors for Overwriting Input File

base-theme/layouts/shortcodes/image-gallery.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1109
This PR takes the `baseUrl` property of image gallery shortcodes and passes it through `resource_url.html` before sending it along to nanogallery. This has the effect of prefixing images with `RESOURCE_BASE_URL` if it is set, and allows image galleries to function when testing sites locally by requesting images that don't exist locally from the live OCW site instead.
- Get this course: [2.672-spring-2009](https://github.mit.edu/ocw-content-rc/2.672-spring-2009)
- In your .env file, set:
```
OCW_TEST_COURSE=2.672-spring-2009
RESOURCE_BASE_URL=https://ocw.mit.edu/
```
- Run `yarn start course`
- Go to [labs](http://localhost:3000/pages/labs/) and from there open any image gallery.
`base-theme/layouts/shortcodes/image-gallery.html`
=> run image gallery base urls through resource_url.html

base-theme/layouts/partials/video_embed.html, base-theme/layouts/partials/video_expandable_tab.html, base-theme/layouts/partials/youtube_player.html, course-v2/assets/css/video.scss, course-v2/assets/css/videojs_player.scss
Closes #1103 and https://github.com/mitodl/hq/issues/1196
This PR updates design layout for embed videos. It also fixes the bug issued in https://github.com/mitodl/hq/issues/1196 by updating youtubeParams.
For any of these changes (start time, end time, or general layout related changes), sometimes they can take a little time even after clearing cache and using incognito window. If it still does not work, try clearing cache a couple of times, give it a minute or two, and then try again.
Firstly, follow the testing steps on [this PR](https://github.com/mitodl/ocw-hugo-themes/pull/1115). They will be repeated exactly as they are, but you will be checking out to this branch instead.
Next, we will have to test a sample course to test for embed videos. And we will also be testing that …
=> feat: YouTube controller design layout for embed videos

base-theme/layouts/partials/video.html, base-theme/layouts/partials/video_embed.html
https://github.com/mitodl/hq/issues/1200
It trims the spaces in youtube ids which were causing the player to not load for some videos
1. Go to the main branch
2. Download this course https://github.mit.edu/ocw-content-rc/6.01sc-spring-2011
3. In ocw-hugo-theme, run `yarn start course 6.01sc-spring-2011`
4. Go to lecture 2 video  (the video should not load)
5. Now checkout to this branch,
6. Repeat step 3, 4 (The video should now be loaded correctly)
=> Video player not loading for Spaced Youtube IDs

base-theme/layouts/shortcodes/image-gallery.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1142
This PR fixes a bug with the use of the `image-gallery.html` shortcode in sites that use the `course-offline` theme. The error is caused by passing the improper context variable to the `resource_url.html` partial. The `.` variable is set on `context`, whereas in shortcodes it should be `.Page`.
- Clone https://github.mit.edu/ocw-content-rc/5.36-spring-2009
- Clone [`ocw-hugo-projects`](https://github.com/mitodl/ocw-hugo-projects)
- In `ocw-hugo-themes` on this branch, run `yarn build /path/to/ocw-content-rc/5.36-spring-2009 /path/to/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`
- Verify that the site builds correctly
If you visit the image gallery in the offline site after rendering, you may notice that it does not …
=> fix course-offline image gallery bug

base-offline/layouts/shortcodes/image-gallery.html, base-theme/assets/webpack/webpack.common.ts, course-offline/assets/course-offline.ts, course-offline/layouts/partials/basejs.html, course-offline/layouts/partials/extrahead.html, course-offline/layouts/partials/resource_url.html, course-v2/layouts/_default/baseof.html, course-v2/layouts/partials/basejs.html, course-v2/layouts/partials/extrajs.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1143
This PR adds a new Webpack entry point called `course_offline` and defines that within the `course-offline` theme. Its main purpose is to import libraries for use in the site without lazy loading them, so the bundles are not split.
In https://github.com/mitodl/ocw-hugo-themes/pull/1089 and https://github.com/mitodl/ocw-hugo-themes/pull/1108, we added functionality that splits out VideoJS and NanoGallery using Webpack bundle splitting, lazy loading the artifacts when they are needed to save on network requests on the live site. This had the effect of breaking both of these libraries in the `course-offline` theme when viewing the sites using the `file://` protocol. We generate relative URLs in our offline sites using the Hugo …
=> disable bundle splitting in offline sites

course-v2/assets/css/course-info.scss, course-v2/assets/css/course-v2.scss, course-v2/layouts/partials/course_banner.html, course-v2/layouts/partials/course_description.html, course-v2/layouts/partials/course_info.html, course-v2/layouts/partials/learning_resource_types.html, course-v2/layouts/partials/topics.html, test-sites/ocw-ci-test-course/content/pages/assignments.md, tests-e2e/ocw-ci-test-course/headings.spec.ts
Closes #1105
This PR replaces `div` tags with semantic heading tags. (eg. `h1`)
It also adds playwright test for the fix. The test checks for "headings" and also ensures they are correct level of headings.
Follow this [OCW Style Guide](https://projects.invisionapp.com/d/#/console/21537330/468374061/comments)
2. `yarn start course 9.40-spring-2018`
3. Inspect element and make sure the headings `h1`, `h2`, `h3`, `h4`, `h5` conform to the OCW Style Guide (that they're using `heading` tags, their `font-size` and `line-height` are correct). Check for both desktop and mobile.
So how it works is, in the Style Guide, `1rem=16px` however in the courses theme, `1rem=14px`, so for instance, if you notice `h2` of this branch, you will see it is 1.6rem for Desktop screens. …
=> replace <div> with semantic heading tags in course theme

course-v2/assets/js/video_download_popup.js, course-v2/assets/js/video_download_popup.ts, test-sites/ocw-ci-test-course/config/_default/menus.yaml, test-sites/ocw-ci-test-course/content/pages/multiple-videos-series-overview.md, tests-e2e/ocw-ci-test-course/video-tabs.spec.ts, tests-e2e/util/VideoElement.ts
Closes https://github.com/mitodl/hq/issues/1518
This video fixes video download popups for multiple instances of videos (sometimes we have multiple embed videos in a single page). Previously the download button was working only for first video if there are multiple in a page.
The issue was reported for the courses:
3.091-fall-2018
cms.611j-fall-2014
20.219-january-iap-2015
For `3.091-fall-2018`:
- Instructor Insights, Goodie Bag Tutorials and Problems
For `cms.611j-fall-2014`:
- on all pages under Student Games Projects
For `20.219-january-iap-2015`:
- on all pages starting with "Day X" and the Student projects
2. `yarn start course X` (where X is the above course IDs)
3. Browse over to the mentioned pages above, and where there are multiple embed videos, make …
=> fix video download popup for multiple instances of videos

package.json, yarn.lock
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1161
Upgrades hugo-bin-extended
In this test we will test:
* the dev server is working correctly
* the local online and offline builds are working correctly 
1. Navigate to your local setup of ocw-hugo-themes.
2. Checkout `hussaintaj/1161-upgrade-hugo`
3. Run `yarn install`
4. Run `yarn start course` and `yarn start www`
5. **Expected Behavior** Both the `course` and `www` themes are functioning correctly for local development.
6. Run `yarn webpack:build:dev`
7. Grab a course (from the content repo), open it in a terminal, and run
```bash
npx hugo-bin-extended@0.112.7 --themesDir path/to/ocw-hugo-themes/  --config path/to/ocw-hugo-projects/ocw-course-v2/config.yaml --baseURL /courses/site-id --destination output-online --buildDrafts …
```
=> enhancement: upgrade hugo-bin-extended

base-theme/layouts/partials/header.html, base-theme/layouts/partials/home_url.html, package.json, www-offline/assets/www-offline.tsx, www-offline/content/_index.md, www-offline/content/search/_index.md, www-offline/layouts/home.html, www-offline/layouts/partials/extraheader.html, www-offline/layouts/partials/home_url.html, www-offline/layouts/partials/include_css.html, www-offline/layouts/search/section.html, yarn.lock
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1174
This PR adds the [Fuse.js](https://fusejs.io/) library to the project and utilizes it to provide offline search functionality in the `www-offline` theme, used as the home page of mirror drives. The search icon is now displayed in the header on pages that aren't the search page, linking to a new `search.html` page at the root. In https://github.com/mitodl/ocw-studio/pull/1705, we set up `ocw-studio` to publish a file under `content/websites` for each website that has been published live at least once inside the root website, `ocw-www`. This content is currently being used to generate a paginated list of sites at the root when using the `www-offline` theme in `index.html`. In `search.html`, we put that same list into an array in …
=> offline search for mirror drives

base-theme/assets/css/variables.scss, www/assets/css/home.scss
https://github.com/mitodl/hq/issues/1388
This is a follow up PR to the original issue for some design modification.
Such that currently for small screens(xs), the news images stay a fixed height and tend to go vertical. But we want them to follow the same fashion for small screens as it was originally, i.e, horizontal. This is to help stay consistent with the image sizes and cropping work.
The overall functionality/layout/design structure has already been tested. For this PR we just want to make sure for smaller screens the view looks correct. Make sure that the changes applied (changed related to numerical values) are actually visible on the page (that they are not overridden by some other properties) and nothing breaks.
For mobile interface (on all sizes where we have one news on …
=> Change OCW News mobile(xs) display to horizontal

www-offline/layouts/search/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1182
This PR simply adjusts the `threshold` value in the FuseJS configuration for offline search in `www-offline` to 0.2 from 0.4. After some testing, this seems to be a good place to set it in order to filter out irrelevant results.
Follow the same instructions as https://github.com/mitodl/ocw-hugo-themes/pull/1175, but pay extra attention to the results and verify that irrelevant results have been minimized
=> adjust fuse threshold in offline search to better filter out irrelevant results

base-offline/layouts/partials/video.html, base-offline/layouts/partials/video_player.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1193
Videos uploaded to GDrive and handled by `ocw-studio` are not uploaded to archive.org and thus have no value on `metadata.video_files.archive_url`. The transcoded archive video is instead uploaded to S3 with the file path stored on the `metadata.file` property. This PR alters the offline video player templates to fall back to using the `file` property to obtain the archive video file name it should look for should `archive_url` not be available.
- Create a site in [`ocw-studio` RC](https://ocw-studio-rc.odl.mit.edu/)
- Browse to the metadata section and fill out the required metadata to save it
- Browse to the Resources section, click the link to open the GDrive folder and upload a sample video into the `videos_final` folder
- …
=> fix offline video player for videos with no archive_url

base-theme/layouts/partials/head.html
Related to #1196 
This PR moves Google Tag Manager script to the top of `<head />`, as [recommended](https://support.google.com/tagmanager/answer/6103696?hl=en): 
> Place the <script> code snippet in the <head> of your web page's HTML output, preferably as close to the opening <head> tag as possible, but below any dataLayer declarations.
**Why?** The goal is to better parallelize network requests, particularly in Chrome. Previously, in Chrome, many requests were being queued after some CSS. Similar queueing seemed to occur in firefox, though to a much lesser extent.
Notes:
- Despite research and trying to reproduce with very minimal examples, I don't have a great understanding of why moving the GTM script above the `<link />` has this effect. But since putting GTM at the top is …
=> Improve request parallelization, particularly on Chrome

base-theme/layouts/partials/resource_body_v2.html, course-v2/layouts/partials/learning_resource_type.html, course-v2/layouts/partials/resource_list_collapsible.html, course-v2/layouts/partials/resource_list_item.html, course-v2/layouts/partials/resources_header.html, course-v2/layouts/partials/see_all.html, course-v2/layouts/partials/topic.html
Closes https://github.com/mitodl/hq/issues/1972
Closes https://github.com/mitodl/hq/issues/1973
This PR fixes accessibility related issues on course pages. It focuses on `aria-hidden` and `aria-expanded`.
Apart from the above mentioned issues (sub-tasks), it also fixes the mentioned 3 problems: https://github.com/mitodl/hq/issues/1918#issuecomment-1645290474
We will be using this course to test changes: `16.885j-fall-2005`
This is not the same course as mentioned in the issues (https://ocw.mit.edu/courses/res-7-005-biology-teaching-assistant-ta-training-fall-2021/download/). We need this course to check for other changes. Also, [the course](https://github.mit.edu/mitocwcontent/RES.7-005-Summer-2020) in` ocw-content-rc` it had some missing content which was needed for testing. (I tried …
=> Course theme accessibility fixes (aria-hidden and aria-expanded)

course-v2/assets/css/course-v2.scss, course-v2/layouts/partials/resources_header.html
closes https://github.com/mitodl/hq/issues/2065
Adds a message to the download course page.
The message only appears on touch devices. I've used the `pointer` property for this purpose. [MSDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer#:~:text=a%20pointing%20device.-,coarse,-The%20primary%20input). This might not be perfect but works in most cases from what I've seen.
* You'll need a markdown of a course. Any course would work. You can pick one from here https://github.mit.edu/ocw-content-rc/. Place this in your local ocw-content folder.
1. Navigate to your local ocw-hugo-themes setup. Checkout branch `hussaintaj/2065`.
2. Run
```
yarn start course course-id
```
3. Navigate to [localhost:3000/download](http://localhost:3000/download)
4. Open devtools, toggle the …
=> feat: add mobile device warning to download course page

course-v2/assets/css/course-info.scss, course-v2/assets/css/course-v2.scss, course-v2/assets/css/drawer.scss, course-v2/assets/js/mobile_course_drawers.ts, course-v2/layouts/_default/baseof.html, course-v2/layouts/partials/course_info.html, course-v2/layouts/partials/desktop_course_info.html, course-v2/layouts/partials/mobile_course_info.html, course-v2/layouts/partials/mobile_course_nav.html, tests-e2e/ocw-ci-test-course/course-info.spec.ts
Closes https://github.com/mitodl/hq/issues/1974
This PR:
- reactors desktop view course info panel.
- The two buttons (open and close) have been merged into one. Allowing the focus to persist.
- programmatically gives focus to side drawers for mobile view.
https://github.com/mitodl/ocw-hugo-themes/assets/71316217/5b31431e-ef2e-4517-9b8c-170c40ff7639
https://github.com/mitodl/ocw-hugo-themes/assets/71316217/462fa244-e496-4a63-aa7c-e001e449716a
1. Grab any course content from [ocw-content-rc](https://github.mit.edu/ocw-content-rc) and place it inside your local content directory.
2. Navigate to your local setup of ocw-hugo-themes and check the branch `hussaintaj/1974-course-info`.
3. Run
```
yarn start course <course-dir-name>
```
4. Visit any page other than the homepage.
5. In desktop …
=> fix: course-info toggle accessibility

base-theme/layouts/partials/video_expandable_tab.html, course-v2/assets/css/video.scss
Closes #1213 
Stops the layout shift on video player when `videojs` has not yet dynamically loaded by adding height and width styling.
We will test for:
1. Regular videos
2. Embed videos
3. Offline videos (youtube player)
4. Offline videos (local video player)
**How to test:**
I tested using `low end mobile` throttling setting in inspect element. And refreshing the page several times, and stopping the loading right after the page opens. Make sure there is no shift in layout (as demonstrated in the video in the issue).
For embed videos and regular videos, let's use this course: `18.06-spring-2010`
1. `yarn start course 18.06-spring-2010`
2.  This is an example of embed video: http://localhost:3000/pages/instructor-insights/
3.  This is an example of regular video: …
=> Stop layout shift on videos

course-v2/layouts/_default/baseof.html
Fixes a side effect of https://github.com/mitodl/ocw-hugo-themes/pull/1228
Fixes a side effect of https://github.com/mitodl/ocw-hugo-themes/pull/1228
Some elements in the main section do not behave well without the main section having a defined width. See screenshots for examples.
Before
After
1. Grab any course content from [ocw-content-rc](https://github.mit.edu/ocw-content-rc) and place it inside your local content directory.
2. Navigate to your local setup of ocw-hugo-themes and check the branch `hussaintaj/fix-main-section-layout`.
3. Run
```
yarn start course <course-dir-name>
```
4. Visit any page other than the homepage.
5. Toggle course info and see if different pages behave correctly i.e. video page, video gallery pages etc.
=> fix: main section layout

base-theme/assets/css/video.scss, base-theme/layouts/partials/video_expandable_tab.html, base-theme/layouts/partials/video_tab_title.html, course-v2/assets/js/video_download_popup.ts, tests-e2e/ocw-ci-test-course/video-tabs.spec.ts, tests-e2e/util/VideoElement.ts
Closes #1219 
Fixes accessibility related issues of video tabs by restructuring the code. This includes the toggleable video tabs and the download button.
You may use a screenreader for testing or check the accessibility using inspect element. Make sure the screen reader would correctly read the text now (and no redundancy/repeats).
In addition to this, we also want to make sure that the UI does not break because there were styling changes. (Check for different screen sizes)
Here are some courses names:
1. 3.091-fall-2018 (Example of multiple video instances in a single page -- Goodie Bag Tutorials from left menu). Contains embed videos + click on 'View video page' for regular video pages.
2. 18.06sc-fall-2011 (Another example of embed videos -- Instructor Insights from left menu)
3. …
=> fix: accessibility of video tabs

www/assets/css/search-filter.scss, www/assets/css/search.scss, www/assets/js/components/Facet.tsx, www/assets/js/components/FacetDisplay.test.tsx, www/assets/js/components/FacetDisplay.tsx, www/assets/js/components/FilterableFacet.tsx, www/assets/js/components/Footer.tsx, www/assets/js/components/SearchFilter.test.tsx, www/assets/js/components/SearchFilter.tsx, www/assets/js/components/SearchFilterDrawer.test.tsx, www/assets/js/components/SearchFilterDrawer.tsx, www/assets/js/components/SearchPage.tsx
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1222
This PR adds aria attributes to interactive elements in the search page.
The most noticeable change is the ability to navigate into the filter section using tabs.
The objective of this PR is to ensure:
- Nothing is unnecessarily repeated during assistive speech
- Nothing unnecessary is spoken during assistive speech
- Decorative icons are not spoken
- And that interactive elements can be navigated by using tabs
There are no visual changes. In the following recording, you can see me using MacOS's VoiceOver assistant on the page.
The recording is in the desktop view, but the accessibility functionality should work in a similar way on the mobile view.
https://github.com/mitodl/ocw-hugo-themes/assets/71316217/c978723d-4432-457f-9b79- …
=> feat: add aria attributes to www search page

course-v2/assets/css/course-nav.scss, course-v2/layouts/_default/baseof.html, course-v2/layouts/partials/nav.html, course-v2/layouts/partials/nav_item.html, course-v2/layouts/partials/topic.html, tests-e2e/ocw-ci-test-course/course-info.spec.ts
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1220
Fixes https://github.com/mitodl/ocw-hugo-themes/issues/1237
This PR improves the accessibility of the sidebars. In general, this PR:
* Converts relevant `<a>` tags to `<button>`s.
* Adds some extra semantic labels for the navbar.
* Makes the HTML more semantic by using `<ul>` for topics in the course info bar.
* Fixes the layout shift issue when topics were toggled.
https://github.com/mitodl/ocw-hugo-themes/assets/71316217/fa9893a5-6d74-4cd3-b644-56c4a8c49144
1. Download content for the course [6.01sc-spring-2011](https://github.mit.edu/ocw-content-rc/6.01sc-spring-2011), and place it inside your local content directory. This step is optional if you have your setup configured to fetch remote content.
2. Navigate your local …
=> feat: improve navbar and topics accessibility

course-v2/assets/css/video.scss, course-v2/layouts/partials/video-gallery-item.html
Closes https://github.com/mitodl/hq/issues/2408
1. Fixes mobile layout responsiveness for video resources (titles going out of `div` boxes if they're bigger in length)
2. It also adds ellipsis -- 2 lines limit for Desktop view, 4 lines limit for Mobile view (`xs` screen only)
3. Also gives `max-width` of `150px` to img thumbnails. Now for larger thumbnails, the `div` container will not grow bigger.
1. Checkout to this branch. 
2. Use any course (just run `yarn start course`). 
4. Go to Video Lectures. 
5. Try to break responsiveness of the video `div` containers eg. try different combination of long names, or very short names, or different size images for thumbnail. Experiment a little, make sure nothing breaks for all screens.  
Also, we've kept the `font-size`, and `line-height` same as …
=> fix mobile layout responsiveness for video resources

course-v2/assets/css/course-resources.scss
Related to https://github.com/mitodl/hq/issues/1681
I noticed that if we have a have a single worded long title, it breaks the `div`.
You can notice this behavior here: https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/download/
If you go under readings, and inspect element to something like 300 width you will see it goes out of the div. So basically if the text is longer than that, then it will be apparent for bigger screens too.
Problem:
Fix:
1. checkout to this branch
2. yarn start course 6.0002-fall-2016
3. go to downloads and inspect element an existing title to add a long, one word title to a resource. It should not break the `div` box.
=> fix long single word resource title going out of div

course-v2/assets/css/course-resources.scss
Closes https://github.com/mitodl/hq/issues/3022
Currently, the words break take places on arbitrary positions of a word. This is because we are currently using `word-break: break-all;`
Eg. 
`This is internationalization` may come off as:
`This is int`
`ernationalization` (Depending on the screen size/space available)
And we do not want this random breaking of words.
This PR allows to break words as whole, and also allows hyphenation.
For example:
`This is internationalization` may become:
`This is international-`
`ization`,
OR it may become:
`This is inter-`
`nationalization`
The exact behavior is dependent on the space available for text, and the algorithm the utilized browser has. Setting `lang="en"` allows us to use this behavior, and we already have that in our HTML pages.
However, …
=> fix: Resource titles breaking in resource lists and resource pages

tests-e2e/util/test_sites.ts
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1289
This PR alters the `siteUrl` function in our Playwright tests to strip out consecutive slashes from URL paths in URLs being requested by Playwright during testing. These consecutive slashes are filtered out both by `hugo server` and the nginx fronted Minio instance run by `ocw-studio`, so the problematic behavior that this causes is not seen locally unless you set `PLAYWRIGHT_BASE_URL` to point at a site that doesn't handle consecutive slashes. Our Fastly fronted AWS S3 buckets are an example of this. The URL is passed through from Fastly to S3 without any modification. S3 interprets double slashes as just another part of the key, as S3 does not have a true directory structure. The URL path (or "key," in AWS terminology) can …
=> Fix redundant backslashes in Playwright test URLs

tests-e2e/ocw-ci-test-course/video-tabs.spec.ts
None; came up while testing #1289 
Adds a comment about fun MacOS behavior.
If you want to test this, run `yarn test:e2e` on MacOS with and without keyboard navigation enabled in System Settings. (`System Settings --> Keyboard --> Keyboard Navigation`)
=> add a macos test comment

www/assets/js/lib/constants.ts
None.
Selecting 'Non-Credit' at  https://ocw.mit.edu/search/ does not work. This fixes the issue
We have parameter validation for the ocw search. Unfortunately, the parameter validation needs to be updated when we update the results from the api. 
Set 
SEARCH_API_URL=https://open.mit.edu/api/v0/search/
Run `yarn start www`
Turn CORS off in your browser
Go to http://localhost:3000/search/
Verify that you can select non-credit
Needing to manually update the possible parameters every time they change isn't great. 
Once ocw is migrated to the new search api and https://github.com/mitodl/mit-open/issues/269 is implemented we can get the possible parameters from the client that will be created by https://github.com/mitodl/mit-open/issues/269
=> fix non-credit filter

base-theme/assets/types/global.d.ts, base-theme/assets/types/mit-open-login-button.d.ts, base-theme/assets/webpack/webpack.common.ts, course-v2/assets/course-v2.ts, package.json, yarn.lock
This PR makes a few small changes to `cg/add-mit-open-login-button`:
- Removes hard-coded MIT Open baseurl
- Installs `mit-open-login-button` from git rather than local.
- Local might still be easier and useful for development, but git is definitely easier for sharing with others.
=> use git package; remove hardcoded baseurl

base-theme/assets/css/video.scss, base-theme/layouts/partials/head.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1314
Removes roboto font.
The screenshot is WITH the change. The pasted in bit is the old version.
View a video page and confirm it looks almost exactly the same as it does on the live site.
=> no roboto font

renovate.json
Part of https://github.com/mitodl/ocw-hugo-themes/issues/1296
This PR updates renovate config to prevent a package's updates from being auto-merged.
You may validate the config locally. Simply clone the repo and run:
```sh
npx --package renovate -c 'renovate-config-validator'
```
Notice the base branch of this PR. From what I've read online, once we merge this PR, renovate should run some checks on it. Source: https://github.com/renovatebot/renovate/issues/13948#issuecomment-1677034852
Once that passes, I'll create another PR merging `renovate/reconfigure` into `main`.
=> config(renovate): exclude hugo-bin-extended from Renovate automerge

renovate.json
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1296
Merges new renovate config (i.e. https://github.com/mitodl/ocw-hugo-themes/pull/1357) into main. 
See the list of checks on this branch/PR. Renovate should have run a validation job against the updates.
=> config(renovate): exclude hugo-bin-extended from auto-merge (#1357)

www/assets/js/components/Facet.tsx, www/assets/js/components/FilterableFacet.tsx
PR: https://github.com/mitodl/ocw-hugo-themes/pull/1347
Ramda Release Notes: https://github.com/ramda/ramda/issues/3218
https://github.com/mitodl/ocw-hugo-themes/pull/1347 auto updates ramda from 0.27 to 0.29. In 0.28, the method `contains` was removed in favor of `includes`.
1. Navigate to your local `ocw-hugo-themes` directory.
2. Checkout the branch `hussaintaj/fix-search-ramda`.
3. Make sure your env has
```env
STATIC_API_BASE_URL=https://live-qa.ocw.mit.edu/
```
4. Run
```sh
yarn start www
```
5. Open [localhost:3000/search](http://localhost:3000/search) with CORS disabled.
> I use an extension called "CORS Everywhere" in firefox.
6. Expect the search to work. Especially the filter facets.
=> fix: search page (broken by ramda upgrade)

course-v2/assets/css/course-resources.scss, course-v2/layouts/lists/single.html
No ticket
Fixes `border-top` styling not being applied to resource lists.
For example:
https://ocw.mit.edu/courses/21a-505j-the-anthropology-of-sound-spring-2022/lists/lecture-slides/
https://draft.ocw.mit.edu/courses/3-020-thermodynamics-of-materials-spring-2021/lists/problem-sets/
It should be like the lists here:
https://ocw.mit.edu/courses/res-18-010-a-2020-vision-of-linear-algebra-spring-2020/download/
2. Run `yarn start course 21A.505J-spring-2022`
3. Go to http://localhost:3000/ and lecture slides from left menu
4. See the top-border is being applied to first element
5. Go to download course from http://localhost:3000/, see the borders are being applied on lists there
Another good example of a course is `18.06sc-fall-2011`. Run it locally, go to Download …
=> Fix resource list top border styling

base-theme/assets/css/modal.scss
Related to https://github.com/mitodl/ocw-hugo-themes/pull/1364
@mbilalmughal suggested a few improvements to the styles of the modal for small screens.
This PR updates modal styles for `xs` screens. It
- reduces the text size
- reduces padding
- aligns title text to the left
iPhone 12 pro vs iPad Mini (for reference)
1. Grab content for [this course](https://github.mit.edu/ocw-content-rc/ht-test-2024).
2. Place the content in your local content directory.
3. Navigate to your local setup of `ocw-hugo-themes`.
4. Checkout branch `hussaintaj/adjust-modal-xs-styles`.
5. Run
```
yarn start course ht-test-2024
```
6. Click a link that opens a modal.
7. Observe the modal in a small device through the device toolbar in the developer panel.
8. Expect the mobile modal to be smaller and more compact …
=> feat: adjust modal styles for `xs` screens

base-offline/layouts/partials/video.html, base-theme/assets/css/main.scss, base-theme/assets/css/variables.scss, base-theme/layouts/partials/video.html, base-theme/layouts/partials/video_embed.html, course-v2/assets/css/instructor-insights.scss, course-v2/assets/css/video.scss, course-v2/layouts/partials/course_content.html, www/layouts/collections/single.html
Closes https://github.com/mitodl/hq/issues/2921
Removes `max-width: 100vh` from video pages styling to allow the content to spread over all of the `div` body.
This means, not only the text, but videos will now take up entire `div` width too.
Refer to https://github.com/mitodl/ocw-hugo-themes/pull/1369#issuecomment-1993747002
Checkout to this branch, check any course that has video lectures (the default course also does -- `yarn start course`). Check embed video pages as well. An example of embed video is in course `18.06sc-fall-2011` in the Instructor Insights page.
For offline course theme, run:
`yarn build ~/path/ocw-content-rc/18.06sc-fall-2011/ ~/path/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`
And then open `index.html` from `dist` directory of the course, and navigate to …
=> Video pages layout width-fix

course-v2/layouts/partials/course_content.html
No ticket
I had removed `content` class from course_content.html in https://github.com/mitodl/ocw-hugo-themes/pull/1369 because I thought it didn't serve any purpose. Moreover, `content pt-3 mt-1` was causing paddings and margins to be inconsistent with other OCW pages (like regular pages, and embed video pages).
But it appears it was keeping the page fixed to a certain width - images were not allowed to be overflowed. Other than that, it was also responsible for giving anchor texts blue color. Example: https://live-qa.ocw.mit.edu/courses/ht-test-site-2024/pages/embeds-and-links/
I think more R&D is required for this, and for the time being it's okay to add back that change.
`yarn start course ht-test-2024`
Go to different links from the left menu, see everything works as expected.
=> Add back content class in course content

course-v2/assets/css/course-v2.scss, course-v2/layouts/partials/quiz_multiple_choice_choice.html
Part of https://github.com/mitodl/hq/issues/3661
Adds `.RenderString` in `quiz_choice` to allow markdown rendering. The CSS changes were added to align everything centrally - the uneven spacing was specifically apparent with `code` blocks in MCQ options.
Lecture 8 and Lecture 9 of `6.0001-fall-2016` have such contents... I'm not sure if they're available in `ocw-content-rc` right now, so you can also use this markdown:
```
1. Which of the below is a getter method for the number of wheels?    
```plaintext
----------------------------------
----------- Given ------------
----------------------------------
class Car(object):
def __init__(self, w, d):
self.wheels = w
self.doors = d
self.color = ""
----------------------------------
(A)     def get_wheels():
return wheels
(B)     def …
=> Markdownify quiz choice

base-theme/layouts/partials/course_list.html, course-v2/layouts/lists/single.html, www/assets/css/course-collection.scss, www/layouts/collections/single.html
Partial solution to https://github.com/mitodl/hq/issues/3855
Renders content (body) instead of description in course list and course collections.
Doing this will allow us to have only plain `description` as page SEO for the contents, and formatted content that is rendered.
This is pertaining to the changes in: https://github.com/mitodl/ocw-hugo-projects/pull/294/
I have also updated `ocw-www` starter configuration, and copied the data from `description` to `body` for `ocw-content-rc`.
This means you can also check the course collection here:
https://ocw-hugo-themes-www-pr-1397--ocw-next.netlify.app/collections/energy/
And inspect element to find `div class="mb-3 collection-content"` that renders the content.
Although a local test may be to get a fresh copy of `ocw-www` by deleting …
=> Render content (body) instead of description

course-v2/layouts/partials/course_banner.html
Closes [https://github.com/mitodl/ocw-studio/issues/1996](https://github.com/mitodl/ocw-studio/issues/1996)
Allows to publish course without visiting metadata section
Steps are mentioned in this Studio [PR](https://github.com/mitodl/ocw-studio/pull/2183)
=> Fix course publishing from studio without metadata (#1274)

course-v2/layouts/partials/course_description.html
closes https://github.com/mitodl/hq/issues/4074
The description includes html tags as well. The cutoff to show expand/collapse button is `320`.  The length of text characters shown in the image below is `243` but the actual length of raw text including the html `<a>` is `351`. Due to this difference the expand/collapse button is shown here.
**Raw text**
`6.00 Intro to CS and Programming has been retired from OCW. You can access the archived course on <a href=\"https://dspace.mit.edu/handle/1721.1/150580\" target=\"_blank\" rel=\"noopener\">DSpace – MIT’s digital repository</a>. Please see the list of&nbsp;<a href=\"https://ocw.mit.edu/collections/introductory-programming/\" target=\"_blank\" rel=\"noopener\">introductory programming courses</a> and other programming courses from recent …
=> added text parsing to omit html tags in length checking

course-v2/layouts/pages/section.html
closes https://github.com/mitodl/hq/issues/4645
This fixes rendering of sections for pages in theme
2. in local Hugo themes repo, switch to `main` branch
3. start course with the following command: `yarn start course 3.a04-fall-2008`. This should pull course from rc
4. Access course on `http://localhost:3000/pages/forging/`
5. Identify that it shows only a few of images and incomplete page after `Anvil` heading.
6. Switch to `umar/4645-broken-image-galleries-in-legacy-courses` branch in themes repo.
7. refresh page in browser. This should complete page rendering and multiple renderings along with images should appear
=> fixed section rendering for the pages

base-theme/assets/css/external-link.scss, base-theme/layouts/partials/head.html
Closes https://github.com/mitodl/hq/issues/4724
Removes external link icon from everywhere except nav-links. This means both course-v2 and www theme, so pages, course links, course collections, etc. 
2. Use external resources in pages. Make sure to test for both cases: tick the external resource warning, and don't tick it.
3. See that external resource icon does not appear in either for pages.
4. Everything should stay same for external resources in left navbar.
5. Functionality for external resource will also stay same within pages.
To test for www theme, you will have to rebase this branch onto `ibrahim/4245/external-resource-rendering-www` and then you can test for external resource icon in pages, course lists, course collections the same way.
=> Remove external link icon from pages

course-v2/assets/course-v2.ts, www/layouts/_default/baseof.html
Task 2: https://github.com/mitodl/hq/issues/4245
Render external resources in www theme by calling the `external_link_modal` partial in `www/layouts/_default/baseof.html`.
Testing instructions given in https://github.com/mitodl/ocw-hugo-projects/pull/296
Test both PRs together.
=> Render external resources in www theme

test-sites/ocw-ci-test-course/data/course.json
https://github.com/mitodl/hq/issues/3132
As we removed the `course_image_thumbnail` field in `ocw-hugo-projects` (https://github.com/mitodl/ocw-hugo-projects/pull/297), this PR cleans up the field from test course.
There isn't any specific way to test this. While it is a part of the test course, there is no test against `course_image_thumbnail`. You can check the logs of the checks passed on the tests in this PR.
=> Chore: Course Image Thumbnail Cleanup

README.md, base-offline/layouts/partials/get_search_url.html, base-theme/layouts/partials/course_carousel_card.html, base-theme/layouts/partials/extraheader.html, base-theme/layouts/partials/get_search_url.html, tests-e2e/ocw-ci-test-course/homepage.spec.ts, www/layouts/educator/section.html, www/layouts/home.html, www/layouts/partials/extra_metadata.html
fixes https://github.com/mitodl/ocw-hugo-themes/issues/1210
Add trailing slash "/" to search and course links.
- Inspect the course link in card at homepage, it should have trailing "/".
=> Updated course card links to have trailing "/"

base-theme/data/departments.json, course-v2/assets/css/course-v2.scss, course-v2/layouts/partials/course_info.html, course-v2/layouts/partials/get_departments.html, course-v2/layouts/partials/title.html
Part of https://github.com/mitodl/hq/issues/4855
This PR removes `RES` from `departments.json` and adds conditional rendering for departments.
2. `yarn start course ibrahims-cat-course`. This course has 3 departments, including `RES`: https://live-qa.ocw.mit.edu/courses/108-ibrahims-cat-course-spring-2023/
3. Go to http://localhost:3000/ .It will show only 2 of them locally.
4. `yarn start course res.14-002-spring-2011` . This course has no department.
5. Go to localhost:3000. `Departments` heading should no longer be there.
6. You should also check for department in OG title. Go to `http://localhost:3000/` and inspect element, find the meta tag that looks like this: `<meta property="og:title" content="ibrahims-cat-course | Civil and Environmental Engineering | …
=> Remove RES from departments.json

course-v2/layouts/index.coursedata.json, test-sites/__fixtures__/courses/ocw-ci-test-course/data.json, www/assets/js/LearningResources.ts, www/assets/js/factories/search.ts
Related to https://github.com/mitodl/hq/issues/5126
Adds `hide_download` to the `data.json` template for courses
- Run `yarn start course res.15-005-spring-2019-2`
- Go to http://localhost:3000/data.json, it should include `"hide_download": true`
- Run `yarn start course res.10-001-spring-2016`
- Go to http://localhost:3000/data.json, it should include `"hide_download": false`
=> Include hide_download in data.json

course-v2/layouts/index.coursedata.json, test-sites/__fixtures__/courses/ocw-ci-test-course/data.json, test-sites/ocw-ci-test-course/data/course.json
Part of https://github.com/mitodl/hq/issues/5223
Adds `mit_learn_topics` field in `data.json` to be ingested by MIT Learn.
This PR will be tested along with https://github.com/mitodl/ocw-hugo-projects/pull/305. Please refer to the testing instructions mentioned there.
=> Add mit_learn_topics field in data.json

course-v2/layouts/partials/nav_item.html, course-v2/layouts/partials/nav_item_has_child.html
Closes  https://github.com/mitodl/hq/issues/5358
Menu items can be links to pages or external resource links. On rendering resources are pulled from DB. If the linked resource has been deleted, the menu item still renders and is broken. On click, it does not show any error but doesn't navigate anywhere either. 
This PR aims to conditionally render menu items if it has a valid URL field. If deleted the related field is empty.
1. Create a test course on `RC`, add an External resource to its Menu, and Publish.
2. In your local themes repo, switch to branch `main`
3. Run command `yarn start course <course-name-on-rc>`, this should pull course from RC
4. Browse the pulled course on `localhost:3000` and validate the menu item is added and navigable
5. After validation, go to the admin panel and …
=> added condition to include nav item only if url is not empty

www/layouts/partials/home_stories.html, www/layouts/stories/list.html, www/layouts/stories/single.html
Part of https://github.com/mitodl/hq/issues/6029
This PR adds featured stories on display for OCW. 
- Homepage & List page: If no featured story is selected (in backend), then it defaults to showing all stories instead.
- Single story page 'More Stories': First 4 featured stories will be shown in sidebar (if they exist). If no featured stories exist, then it defaults to showing 4 stories randomly. However, if less than 4 featured stories exist, then the exact number (less than 4) will be shown.
- Added condition to not show same opened story in sidebar for More Stories. Eg. Sidebar is supposed to show first 4 featured stories, and if one of them is opened currently, then it won't be included in the 4, the next story would then be displayed.
This must be reviewed together with: …
=> Display Featured Stories

base-theme/layouts/partials/get_resource_download_link.html, base-theme/layouts/partials/resource_body_v2.html, course-v2/layouts/partials/resource_list_item.html
closes https://github.com/mitodl/hq/issues/5111
The download button for resources in offline courses compiles a different relative URL than the preview URL. As a result, downloading the resources results in a 404 error. 
The issue lies with the context changes for the partial that compiles the resource URL for the download button.
This PR would be tested properly in RC but following the details reported in https://github.com/mitodl/hq/issues/5111 the change can be viewed as following in the local environment:
1. Go to your local themes repository and switch to the `master` branch
2. Run the following command after adding the path to your local projects repository
`yarn start course 1.012-spring-2002 --config <path-to-ocw-hugo-projects>/ocw-course-v2/config-offline.yaml`
3. Go to …
=> fixed context for the resource_url partial

base-theme/layouts/partials/pdf_viewer.html
Closes https://github.com/mitodl/hq/issues/6408
There is currently an invisible download link bar for PDF resources as a bug. This PR removes it. Please refer to the ticket for screenshot of issue.
`mt-5` is added to keep some space between PDF resource and its viewer.
For online theme:
2. `yarn start course 3.020-spring-2021`
3. Go to a PDF resource, e.g., http://localhost:3000/resources/mit3_020s21_pset01_pdf/
4. Check that the invisible download link is no longer present.
For offline theme:
2. `yarn build ~/path/ocw-content-rc/3.020-spring-2021/ ~/path/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`
3. Go to a PDF resource, e.g., `file:///<path>/ocw-content-rc/3.020-spring-2021/dist/resources/mit3_020s21_l01/index.html`
4. …
=> Remove invisible download link for PDF files

base-theme/layouts/partials/external_resource_link.html, base-theme/layouts/partials/link.html
Closes https://github.com/mitodl/hq/issues/6480
This PR improves the accessibility of external links by modifying the `link.html` partial to include `aria-label` attributes.
If you have Mac, please use its VoiceOver. Otherwise only inspect the aria-label attributes in `anchor` tags.
2. `yarn start course peter-test-2024-02-20`
3. Inspect the external links in the left navbar.
=> Improve accessibility for external links by adding aria-label

course-v2/layouts/partials/resource_list.html, course-v2/layouts/partials/resource_list_item.html
None
We recently changed the way params were handled in the resource list partials for this issue: https://github.com/mitodl/hq/issues/5111
As a side effect, there was an inconsistency in the params passing, due to which `$downloadLink` comes out empty and no download icon appears for resource items in resource list view. There is a case sensitivity: `params` is being passed, but `Params` is being expected.
This PR changes `params` to `Params` making sure it is consistent across different partials.
Before:
After:
1. `yarn start course 18.06sc-fall-2011`
2. Go to http://localhost:3000/download
3. Make sure the download icon appears and works as expected! (in both list view, and individual resource page)
=> Fix: Resource List Download Icon not visible

package.json, tests-e2e/jest/build-failures.test.ts, yarn.lock
None
This PR upgrades `hugo-bin-extended` version from `0.115.4` to `0.119.0`. 
As explained in https://github.com/mitodl/ocw-hugo-themes/pull/1495/, there was a problem with our Jest tests pertaining to `504` status code. Hugo's update in `0.117.0` causes them to retry with exponential backoff - retrying 30 times before finally failing, taking quite a long time.
This PR also modifies those tests to simulate API failures efficiently. Rather than triggering Hugo's full exponential backoff (with 30 retries), the tests now return a transient 504 error on the first request and immediately return a 404 on subsequent requests. This effectively short-circuits the retry mechanism, allowing the tests to fail fast without waiting for the full retry cycle.
Checkout to this branch.
Run `yarn …
=> Upgrade Hugo version from 0.115.4 to 0.119.0

www/assets/css/about.scss
Closes https://github.com/mitodl/hq/issues/6591
Fix milestone links being unclickable due to carousel overlay.
2. `yarn start www`
3. Open mobile view in browser using inspect element
4. Go to OCW Milestones: http://localhost:3000/about/
5. Make sure `The New York Times` link is clickable (refer to screenshot below)
=> Fix milestone links being unclickable due to carousel overlay

base-theme/layouts/partials/external_resource_link.html
Closes https://github.com/mitodl/hq/issues/6480
The voiced text is now consistently `opens in a new tab` irrespective of whether the ER opens the warning dialog or not.
If you have Mac, please use its VoiceOver. Otherwise only inspect the aria-label attributes in `anchor` tags.
2. `yarn start course peter-test-2024-02-20`
3. Inspect the external links in the left navbar.
=>  Improve accessibility for external links

base-theme/layouts/partials/footer-v2.html, course-v2/layouts/_default/baseof.html, course-v2/layouts/home.html, course-v2/layouts/partials/course_v2_js.html
Closes https://github.com/mitodl/hq/issues/6907
This PR fixes the isolation between the online and offline theme's Javascript bundles. Currently, the `course_v2.js` bundle is loaded in both the online and offline theme. The bundle was being loaded directly in `course-v2/layouts/_default/baseof.html`, and appzi was being loaded in `home.html`. This kind of thing is supposed to be loaded from the `basejs.html` and `extrajs.html` partials, otherwise they will be loaded on anything that inherits the `course-v2` theme. The `basejs` and `extrajs` blocks were not being populated with them being placed where they were in `baseof.html`. Once I moved these into `footer-v2.html` they started working again.
- Ensure your environment is configured to run OCW sites locally and exported to your terminal …
=> remove course v2 bundle from the offline theme

base-theme/assets/js/components/UserMenu.tsx
Closes https://github.com/mitodl/hq/issues/6998
This PR adjusts the `logoutUrl` variable in the `UserMenu` component to simply point at `/logout` instead of `/logout/oidc`. Since https://github.com/mitodl/mit-learn/pull/2145 has been merged, the redirect functionality should actually function now.
- Spin up a bare minimum instance of `mit-learn` locally
- Set up the various environment files based on the examples, using default values
- Set the following in your `.env` file at the root of the project:
```
COMPOSE_PROFILES=backend,frontend,apisix,keycloak
CSRF_COOKIE_DOMAIN=.odl.local
ALLOWED_REDIRECT_HOSTS=["localhost:3000", "ocw.odl.local:3000"]
CORS_ALLOWED_ORIGINS=["http://localhost:3000", "http://ocw.odl.local:3000"]
CSRF_TRUSTED_ORIGINS=["http://localhost:3000", …
```
=> adjust logout URL so redirect works

base-theme/assets/js/posthog.ts
https://github.com/mitodl/hq/issues/7017
This PR sets the `opt_out_capturing_by_default` option on `posthog.init` to prevent sending analytics events to Posthog.
- Ensure you have a Posthog project configured in your `.env`
- Run a course with `yarn start course`
- Visit the page and open up the developer console, where you should see "Posthog enabled"
- Click around the page, reload it a few times
- Visit your Posthog dashboard and verify that you do not see any events in the Activity section based on what you've done
=> set opt_out_capturing_by_default to true in Posthog

base-theme/assets/js/components/UserMenu.tsx, base-theme/assets/js/hooks/user/index.ts, package.json, yarn.lock
Closes https://github.com/mitodl/hq/issues/7075
This PR fixes the feature flagged login button functionality that communicates with the MIT Learn API. There was recently a change to the API. Previously, if you were not logged in, the API would return a 403 when you hit `/api/v0/users/me`. Now, the endpoint returns a 200 with a JSON response indicating that you are not authenticated with `is_authenticated` being `false`. This PR adjusts the hooks here in OCW to account for this change.
- Spin up a bare minimum instance of `mit-learn` locally
- Set up the various environment files based on the examples, using default values
- Set the following in your `.env` file at the root of the project:
```
COMPOSE_PROFILES=backend,frontend,apisix,keycloak
CSRF_COOKIE_DOMAIN=.odl.local …
```
=> fix login button

README.md, base-theme/assets/js/components/BookmarkButton.tsx
Closes https://github.com/mitodl/hq/issues/7305
This PR fixes a race condition bug with the bookmark button on the course homepage. We added the button in https://github.com/mitodl/ocw-hugo-themes/pull/1572, and as part of that it was set up to not render unless the `LearningResource` had been returned from the Learn API. The readable ID of the resource is set on a div with the class `bookmark-button-container` while Hugo is rendering the site. These containers are fetched and iterated as part of the initial site load, with `BookmarkButton` elements being initialized for each one inside the container. The button component needs to load the `LearningResource` to check the memberships and change the style of the button if you have bookmarked it. Meanwhile, the `AddToUserList` dialog …
=> disable the bookmark button when loading instead of not rendering it

www/content/staff/brett-paci.md, www/content/staff/cheryl-siegel.md
Follow-up to https://github.com/mitodl/hq/issues/7445 and https://github.com/mitodl/hq/issues/7497.
This PR updates Brett Paci's and Cheryl Siegel's titles on the OCW Team page; the `OCW` is redundant since they are both OCW Team members.
Run `yarn start www`, and then navigate to http://localhost:3000/about. Verify that the titles have been updated properly, removing the `OCW`.
=> OCW Team page updates

www/layouts/about/section.html
https://github.com/mitodl/hq/issues/6943
This PR adds a YouTube player for Chalk Radio, replacing the Simplecast player on the `About Us` page on the OCW home.
1. Switch to this branch and run the homepage with: `yarn start www`
2. Go to `http://localhost:3000/about/` and scroll half way down to verify that it has YouTube player for Chalk radio as shown in the screenshot above
3. Play the video to verify that it works
=> chore: added youtube player for chalk radio on `about us` page

course-v2/layouts/partials/learning_resource_type.html, www/assets/js/lib/constants.ts
Part of https://github.com/mitodl/hq/issues/7297.
This PR removes special formatting for `Course Introduction` learning resource types, since it is no longer an option, and also removes it from search/filtering.
This should be tested together with https://github.com/mitodl/ocw-hugo-projects/pull/342. Make sure that search is configured appropriately in OCW Studio, and verify that `Course Introduction` no longer appears as an option to filter or search by.
=> Remove Course Introduction learning resource type

base-offline/layouts/partials/resource_url.html, base-theme/layouts/partials/image_resource.html, base-theme/layouts/shortcodes/resource.html
https://github.com/mitodl/hq/issues/8214
This PR fixes the calculation of relative links for image urls in the offline build.
Currently, the process for calculation of image urls is as follows :-
1. [Find](https://github.com/mitodl/ocw-hugo-themes/blob/main/base-theme/layouts/shortcodes/resource.html#L11-L14) the associated resource page and pass forward its context to the `image_resource` partial. The important thing to note here is that the context is of the resource page, and not of the page being built.
2. The `image_resource` partial calls the `resource_url` partial with the same context (that of the resource page and not of the page being built) to calculate a relative url.
3. The `resource_url` partial uses the relative link of the context page, which is essentially the resource …
=> fix: broken images in offline build for nested pages (pages/pageA/pageB)
