package.json, yarn.lock
None
This PR is the result of running a `yarn upgrade` to update to the latest version of `ocw-to-hugo`
- Install dependencies with `yarn install --pure-lockfile`
- Enter the `ocw-to-hugo` directory with `cd node_modules/@mitodl/ocw-to-hugo`
- Sync a parsed OCW JSON bucket locally to your computer, such as `open-learning-course-data-rc`
- Run ocw-to-hugo against the entire folder with a command like node . -i /path/to/open-learning-course-data -o private/output --rm
- Run `echo $?` and ensure that the exit code is `0`
=> ocw-to-hugo 1.19.0

.github/pull_request_template.md
=> remove autotag in PR template

course/assets/css/tables.scss, course/assets/js/responsive_tables.js
Fixes https://github.com/mitodl/ocw-course-hugo-theme/issues/75
Fixes https://github.com/mitodl/ocw-course-hugo-theme/issues/86
This PR is the code from https://github.com/mitodl/ocw-course-hugo-theme/pull/87 ported over to `ocw-hugo-themes`.  The PR in question was reviewed and approved in `ocw-course-hugo-theme`, but we cut over to `ocw-hugo-themes` before it was released.  See the description in the PR linked above for more information.
See https://github.com/mitodl/ocw-course-hugo-theme/pull/87 for testing instructions.  The only difference is that you should follow the readme here in `ocw-hugo-themes` for spinning up a single course site locally.
=> force mobile style if table width exceeds main content area

base-theme/layouts/partials/header.html, www/layouts/home.html, www/layouts/partials/newsletter_signup.html
Part of https://github.com/mitodl/ocw-www/issues/103
Adds alt text to some images
Inspect the images and verify that the alt text makes sense for the image
=> Add alt text

www/assets/css/home.scss, www/layouts/home.html, www/layouts/partials/home_course_cards.html
Part of https://github.com/mitodl/ocw-www/issues/103
Changes some header tags to divs to workaround searchlight warnings
Page should look identical to what it looks like on main
=> Update some headers to remove accessibility warning

www/assets/css/notification.scss
Fixes https://github.com/mitodl/ocw-www/issues/104
Adjusts the color of the notification banner and the link text
Open the home page in incognito mode
=> Adjust color of notification banner and link text

.github/workflows/ci.yml, .github/workflows/deploy.yml, build_scripts/build.sh
Fixes #10
Updates github deploy script for changes to our project structure
View the [lighthouse page link](https://ocw-hugo-themes-pr-77--ocw-next.netlify.app/). You should see the home page with some missing content around the course card and an error message where OCW News would be. The search page should load but you won't be able to make searches since there will be a CORS error because the domain doesn't match up.
=> Fix netlify deploy

www/assets/css/home.scss, www/layouts/home.html
None
Removes some HTML which was there for a dialog which isn't displayed anywhere. 
Nothing should appear different
=> Remove unused dialog

base-theme/assets/index.js, course/assets/course.js, course/assets/css/course.scss, course/assets/css/videojs_player.scss, course/layouts/course/video.html, course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html, package.json, yarn.lock
Fix #30
Adding video.js to play video with our customized video controls.
As of 2018 you cannot remove the the Youtube watch later and share links.
There is a plugin required for the quality selector, but you still need to provide the various quality source files which does not work with youtube.
The things I don't think are working for us:
1) using videojs controls:
- Youtube captions don't move up and down when the control bar appears and disappears ( I spoke to Peter, we are not going to use YT's captions)
- the youtube links , like 'share' and 'watch later' on the top of the video, and the YouTube logo on the bottom right corner are still visible.
- cannot use the gear menu
2) Using Youtube controls: 
- Works great, can set which controls appear in the control bar. But it looks no …
=> Video.js player for customized video controls

www/assets/js/components/SearchPage.js, www/assets/js/components/SearchPage.test.js
closes #114
This fixes the infinite scroll issue we were seeing by applying two fixes:
- ensuring that the state update for new search result data is always applied as an update to the most up-to-date data
- fixing the logic for the `loaded` prop passed to `useCourseSearch` so that only one request may be made at a time
This ensures that we display all the search results and that they are displayed in the right order. It also ensures we're not putting unnecessary, bursty load on the backend by firing off like 15 search requests at the same time 😃 
It seems the easiest way to test this if you don't have a fully set-up open discussions index locally is to point your ocw-hugo-themes repo at the RC search.
You can do that by setting:
```
SEARCH_API_URL=$DISCUSSIONS_RC/api/v0/search/
```
Then …
=> fix infinite scroll issue

base-theme/assets/index.js, course/assets/course.js, course/assets/css/course.scss, course/assets/css/videojs_player.scss, course/layouts/course/video.html, course/layouts/partials/youtube_player.html, course/layouts/shortcodes/youtube.html, package.json, yarn.lock
Fix #100, Fix #101
Adds a videojs player that streams youtube video and adds a provides captions.
set up a test course in .env `OCW_TEST_COURSE=18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013`
Run a course by running `npm run start:course` and navigate to the video lectures in your browser http://localhost:3000/sections/video-lectures/lecture-1-introduction-financial-terms-and-concepts/
=> Video.js player for custom video controls

www/assets/js/components/SearchPage.js, www/assets/js/lib/constants.js, www/assets/js/lib/search.js, www/assets/js/lib/search.test.js
https://github.com/mitodl/open-discussions/issues/3453
RFC https://docs.google.com/document/d/1zEXSDFAJlOvtZmilUjKkwD-4P8d3fk1mIHQLcgMhFew/edit
This pr displays and sorts by the course number from the selected department when there is a department filter.
See instructions at
https://github.com/mitodl/open-discussions/pull/3457
This PR should not be merged until https://github.com/mitodl/open-discussions/pull/3457 is released
=> department course number sort

course/layouts/partials/topics.html
Related to #196 
Checks that topics is present before rendering topics information, to prevent the build from crashing
Test on course `iit-jee`
=> Handle empty topics

.github/workflows/deploy.yml
Closes https://github.com/mitodl/ocw-hugo-themes/issues/293
This PR implements a suggestion made by the devs working on `foo-software/lighthouse-check-action` to support some changes they made to support the latest version of Github Actions used in the latest version of their action.  It fixes the output path of the lighthouse check and allows the check to run.
No manual testing required, but the lighthouse checks should pass on this branch.
=> fix lighthouse checks

course/assets/course.js, course/assets/css/course.scss, course/assets/js/div_toggle.js, course/assets/js/quiz_multiple_choice.js, course/layouts/partials/quiz_multiple_choice_choice.html, course/layouts/partials/quiz_multiple_choice_solution.html, course/layouts/shortcodes/quiz_choice.html, course/layouts/shortcodes/quiz_choices.html, course/layouts/shortcodes/quiz_multiple_choice.html, course/layouts/shortcodes/quiz_solution.html, package-lock.json, package.json, yarn.lock
closes https://github.com/mitodl/ocw-hugo-themes/issues/215
This PR fixes multiple choice questions for legacy courses
Select the branch from https://github.com/mitodl/ocw-to-hugo/pull/418 in ocw-to-hugo
Set example_courses.json in ocw-to-hugo to
```
{
"courses": [
"6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016",
"14-01sc-principles-of-microeconomics-fall-2011",
]
}
```
Run
```
node . -i private/input -o private/output -c course_json_examples/example_courses.json --download
```
in ocw-to-hugo.
In ocw-hugo-themes,
Set your .env to
```
OCW_TEST_COURSE=6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016
COURSE_CONTENT_PATH=/ocw-to-hugo/private/output
DOWNLOAD=0
```
Run
```
npm run start:course
```
Go to a page with multiple choice …
=> multiple choice

base-theme/layouts/partials/header.html
Closes #373 
Updates link to of `help & faq` to https://mitocw.zendesk.com/hc/en-us
- Verify `Help & FAQ` links to correct zendesk in desktop header in ocw-www and ocw-course
- Verify `Help & FAQ` links to correct zendesk in mobile header in ocw-www and ocw-course
=> Updates zendesk link in header

package.json, www/assets/js/LearningResources.ts, www/assets/js/components/Facet.tsx, www/assets/js/components/FacetDisplay.tsx, www/assets/js/components/FilterableFacet.tsx, www/assets/js/components/SearchFacetItem.tsx, www/assets/js/components/SearchFilterDrawer.test.tsx, www/assets/js/components/SearchFilterDrawer.tsx, www/assets/js/components/SearchPage.test.tsx, www/assets/js/components/SearchPage.tsx, www/assets/js/components/SearchResult.test.tsx, www/assets/js/components/SearchResult.tsx, www/assets/js/factories/search.ts, www/assets/js/lib/constants.ts, www/assets/js/lib/search.test.tsx, www/assets/js/lib/search.ts, yarn.lock
none
Upgrades `@mitodl/course-search-utils` to the latest version and then fixes the type errors associated with that. I also remove `ts-nocheck` from a few files and fixed all the errors that resulted from that.
Everything about the search app should work just as it did before.
=> fix some more type issues, upgrade course-search-utils

course/layouts/pages/section.html
(Required)
Closes #393, closes #406, closes #405, closes #394
- Adds a section layout for course theme
Verify all pages have a title on top
(Optional)
=> added section to course theme

www/assets/css/about.scss, www/layouts/about/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/414
- Go to www about page.
- Verify all the above-mentioned points.
=> accessibility: about page

base-theme/assets/css/variables.scss, www/assets/css/course-collection.scss, www/assets/css/www.scss, www/layouts/home.html, www/layouts/partials/course_collection_tab.html, www/layouts/partials/home_course_collections.html
Closes #409 
This PR accomplishes the following
- Creates a partial for course_collection
- Adds necessary styling
- Adds partial the home page
Verify the following 
- The course_collection renders all course collections
- Verify they link to the correct pages
- Verify the section is responsive
=> Add course collection partial

course/assets/js/course_info_toggle.js, course/layouts/_default/baseof.html
Closes #415 
For the `Hide course info` button
- Replaces div with button to add it to the tab order and accessibility tree.
- Updates the code for handling click events.
- Verify you `hide course info` is added to tab order
- Verify both click and enter work
=> added course info button to tab order

course/assets/css/instructor-insights.scss, course/layouts/partials/course_content.html
Closes #436 
Fixes style leaking issue in instructor insights.
Verify, images outside the instructor insights  main section are not scaled up.
=> scoped css to prevent side-effects

www/assets/js/mailchimp.js
Closes #437 
Fixes Home Page scroll on page load
Go to home page and verify it doesn't scroll down to subscription sections
=> removed focus causing the page to scroll down

www/layouts/pages/single.html
Closes #459 
Adds footer to `pages` template for ocw-www
Go to the `TERMS  AND CONDITION` page and verify the footer is rendered.
=> Added footer to Pages Template

www/layouts/about/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/375
- Updates few button links (redirections) in `about` page
- Changes duplicate id of an html element
- Go to www about us page.
- Verify the button links (redirections) mentioned in issue/ticket 
- Verify that there are no duplications in IDs of html elements
=> fix: about page button links updated

course/layouts/resources/single.coursedata.json
https://github.com/mitodl/open-discussions/issues/3513
This PR adds the video thumbnail file to the data.json file for videos
Run ocw-hugo-themes for a course with videos
Go to a video resource.
Append data.json to the url to see the data.json file. It should have "thumbnail_file" as a key
=> add video thumbnail

course/layouts/partials/video.html
Closes #499 
Fixed typo
Verify typo is fixed
=> fixed typo

base-theme/assets/css/variables.scss, course/assets/css/instructor-insights.scss, www/assets/css/course-collection.scss, www/assets/js/components/CourseCollection.test.tsx, www/assets/js/components/CourseCollection.tsx, www/assets/js/components/CourseCollectionRow.test.tsx, www/assets/js/components/CourseCollectionRow.tsx, www/assets/js/components/CoverImage.tsx, www/assets/js/components/SearchResult.tsx, www/assets/js/hooks/hugo_data.test.ts, www/assets/js/hooks/hugo_data.ts, www/assets/js/lib/search.test.tsx, www/assets/js/lib/search.ts, www/assets/js/test_setup.ts, www/assets/www.tsx, www/layouts/course_collections/single.html, www/layouts/partials/course_collection.html
none rn
This implements a new design for the course collection which was put together as part of the 'course collection gallery' work. See https://projects.invisionapp.com/d/main#/console/21537330/464971999/inspect.
Get a course collection set up locally and just check out the display. It should have a nice design which is a bit more compact than what we have now on `master`.
=> update design for course collection list

package.json, www/assets/js/components/FacetDisplay.test.tsx, www/assets/js/components/SearchFilter.test.tsx, yarn.lock
part of #548
Just remove `@ts-nocheck` and fix all the type issues on two files.
Just tests, so they should pass and whatnot.
=> remove @ts-nocheck on two test files

course/layouts/partials/video_embed.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/536
- Fixes the download of embedded video
- Checkout to this branch
- Build any courses locally which has embedded video(s)
- Try downloading the video(s) and verify that videos are downloaded/played successfully.
=> fix: embedded video download

base-theme/assets/css/main.scss
Closes #592
Reverts the changes position override for appzi button.
Verify appzi form works perfectly in mobile.
=> Removed custom override for appzi button positioning 

base-theme/assets/css/footer.scss, www/layouts/collections/single.html, www/layouts/course-lists/single.html, www/layouts/newsletter/section.html, www/layouts/resource_collections/single.html, www/layouts/testimonials/list.html, www/layouts/testimonials/single.html
Closes #573 
Adds footer to the following pages
- course_collection page
- course_list page
- testimonials page
- testimonials list page
- resource list page
Verify the footer renders properly and is responsive
- course_collection page
- course_list page
- testimonials page
- testimonials list page
- resource list page
- home page
- course pages
=> Added footer to missing pages and updated styles

www/layouts/collections/single.html
N/A
Fixes position of previous/next buttons for featured courses carousel on collection pages
- Go to a collection page with featured courses and verify that it looks good in mobile and desktop view.
=> Fix mobile style for featured carousel

www/layouts/home.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/604
- Updates giving section text to: `[Learn more](https://ocw.mit.edu/pages/why-give/) about how you can help MIT OpenCourseWare share knowledge with the world.` 
- Go to www homepage.
- Verify that text is updated and accurate without any mistakes (including grammatical)
=> Giving Section text updated

www/layouts/partials/course_carousel_card.html, www/layouts/partials/featured_course_cards.html, www/layouts/partials/new_course_cards.html
https://github.com/mitodl/ocw-hugo-themes/issues/599
This PR changes the new course cards to get data from the static api
run npm run start:www
Go to http://localhost:3000/
Verify that the new courses and featured courses carousels look the same in this branch and in the main branch
=> use static api for new courses

www/layouts/contact/section.html, www/layouts/newsletter/section.html
closes #620 
fixed spacing issue in contact and newsletter page
Verify there is appropriate margin in mobile screen for the following pages
- Contact
- Newsletter
=> Fixed newsletter and contact

www/layouts/home.html, www/layouts/partials/home_stories.html, www/layouts/partials/stories_card.html
Part of  #614 
First Part of issue #614. It updates testimonials name to stories
Verify testimonials theme as been renamed
=> updated theme name

www/assets/css/pages.scss, www/layouts/pages/single.html
Closes #617 
Updates pages theme to be more inline with contact page.
Verify ocw-www pages is inline with contact page and is responsive for tablets and mobile.
=> Fixed pages theme

www/assets/js/lib/search.ts
closes https://github.com/mitodl/ocw-hugo-themes/issues/625
Updates the priority of resource titles and descriptions
search for 'LECTURE 1: INTRODUCTION AND SUPPLY & DEMAND' in the resource search
https://ocw.mit.edu/courses/14-01-principles-of-microeconomics-fall-2018/resources/lec1-intro/ should be the first result
=> increase resource title priority

www/assets/js/components/SearchPage.tsx, www/assets/js/lib/api.ts, www/assets/js/lib/constants.ts, www/assets/js/lib/util.ts
Closes https://github.com/mitodl/ocw-hugo-themes/issues/646
- Adds a util to check whether any API was successful or failed by checking it's `status`
- Checks whether the search API was successful or not.
- If search API failed, then an error message is shown to the user with contact us link.
- Execute the search API.
- Test and verify that everything is working as expected.
- Now we want the API to fail, this can be done by any method  (give an invalid URL, let the code break from any other method etc)
- Verify that now an error msg is shown to the user with contact us link which takes the user to the contact page.
- Any use-case which needs to be tested.
=> feat: error handling in search API

.github/workflows/deploy.yml
Closes https://github.com/mitodl/ocw-hugo-themes/issues/683
This PR simply updates the version of Node used when running Lighthouse.  An older version was being used which caused the check not to work correctly
The lighthouse check on this PR should pass, and you should be able to visit the Netlify deploy and see the site, although some images and search will not work.
=> fix lighthouse

www/layouts/404.html
Closes #608 
This PR accomplishes the following
- removes header and footer
- moves page css into the html page itself
Verify the 404 page is asper requirements
(Optional)
=> removed header and added required css to style tag

www/assets/css/pages.scss, www/layouts/pages/single.html
Closes #718 
Makes images responsive 
- Verify mobile view for why-give page is responsive
=> fixed images for ocw-www pages

www/layouts/404.html
Part of #608
- Moves all the code for the external css to the 404 page itself
- Verify 404 page does not depend on any external css.
=> updated 404 page

www/assets/js/components/CourseListRow.tsx
Closes #724 
- removed alt text from CourseListRow
- Verify thumbnails of course lists in  collections have an empty alt tag.
=> Removes alt text

.github/workflows/deploy.yml
Closes #764 
- Adds configuration to deploy course preview
- Verify on a new PR with course preview
=> added deploy configurations for testing

.github/workflows/deploy.yml
No tickets
Fixes url for lighthouse
verify lighthouse stats are shown
=> fixed issue with lighthouse

.github/workflows/deploy.yml
- None
- For github workflow:
- Creates a separate build for course v2
- Deploy it to netlify so now we have both course versions deployed on netlify.
- sets `overwrites-pull-request-comment` to `true` so there's only 1 netlify comment instead of comment on every pushed commit(s). 
- Verify that course v2 is also deployed along with course v1
- Verify that the changes made in this PR has no side-effect/impact on anything.
=> build and deploy course v2 on netlify

www/content/staff/elizabeth-derienzo.md
Related to #810 
Removes the unneeded "OCW" from a staff member's title. 
build ocw-www 
@Wassaf-Shahzad can you merge this into your PR branch for #819
=> remove "OCW" from title

course-v2/assets/css/course-nav.scss, course-v2/layouts/partials/nav_item.html
Closes #825 
Fixes the following
- Makes sub-menues the same font size as parents
- Makes space between title and arrow clickable
- Start ocw-course
- On the left nav verify clicking empty space between nav item and arrow behaves similar to either the nav-item or arrow depending on distance.
- Verify sub-menu font size is similar to parent
=> fixed nav items

.github/workflows/deploy.yml
Closes #831 
- Adds command to continue-on-step failure
- Verify checks dont fail on branch
=> Addeded command to continue on failure

.github/workflows/deploy.yml
Part of #831 
- Adds command to continue on failure to other create-or-update action commands since the if block does not work on failures.
- Deleting all netlify comments and then running lighthouse job should be good enough
=> Added check to other create-or-update action commands 

course-v2/assets/js/responsive_tables.js
Part of #835
- Fixes the table render in course-v2 when tables width with greater than the main content.
- Run ocw-course using the course RES.3-006_Sp21
- Open page pages/application-evaluation-rubric/
- Verify table rendered correctly.
=> Fixed responsiveness of tables in course-v2

www/layouts/about/section.html
closes https://github.com/mitodl/ocw-hugo-themes/issues/913
- Updates faculty committee 
- Build www and go to about page
- OR open the netlify deployed www, and go to about page.
- Verify that the faculty committee has been correctly updated as per the details provided in issue ticket.
=> style: faculty committee udpated

package.json, yarn.lock
https://github.com/mitodl/ol-infrastructure/pull/1133
Updates hugo bin to match version in docker container, which was updated in https://github.com/mitodl/ol-infrastructure/pull/1133
1. Check that `yarn run start:course` still works
2. Check that `yarn run start:www` still works
=> Update local hugo to match docker hugo

course-v2/layouts/partials/resources_header.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/945.
Updates the link to point to a relevant help page about course downloads.
Verify that the FAQ link goes to the appropriate help page about course downloads.
=> Updating link to download help page

base-theme/layouts/partials/footer-v2.html
None
Saw this appzi feedback from someone:
- Fixes a typo in footer 
- Verify this fixed typo
- Go through the footer content and verify that there aren't any other typos etc.
Before: 
After:
=> fix: typo in footer

www/layouts/about/section.html
Closes https://github.com/mitodl/ocw-hugo-themes/issues/987 and closes https://github.com/mitodl/ocw-hugo-themes/issues/988.
Updates the members of the OCW Faculty Advisory Committee and the video under `The Next Generation of OCW`.
Run `yarn start www`, and then navigate to `http://localhost:3000/about`. Verify that:
- The video under the heading `The Next Generation of OCW` has been updated.
- The list of members of the `OCW Faculty Advisory Committee` has been updated.
=> Updating About OCW page

.github/workflows/ci.yml, .gitignore, jest.config.ts, package.json, package_scripts/util.ts, playwright.config.ts, tests-e2e/LocalOcw.ts, tests-e2e/global-setup.ts, tests-e2e/jest/build-failures.test.ts, yarn.lock
https://github.com/mitodl/ocw-hugo-themes/issues/1018
Adds some tests along the lines of "In scenario X, our build fails with particular error". In particular, for missing instructors. These tests go with the functionality from #1010 
Tests should pass.
Start tests-e2e/jest/build-failures.test.ts
=> Test build failures

www/layouts/collections/single.html
Closes #829 
Updated error message as per [discussion](https://github.com/mitodl/ocw-hugo-themes/issues/829#issuecomment-1240616619)
- Open featured courses on local
- Verify error message is correct
=> Updated error message

base-theme/assets/js/sentry.ts, env.ts
Closes #1022 
Adds and environment variable to tag sentry errors
(Required)
=> Set sentry environment tag by SENTRY_ENV env variable

base-theme/layouts/partials/image_resource.html
Fixes https://github.com/mitodl/ocw-hugo-themes/issues/1169
The partial `resourse_url` uses `.context.RelPermalink` to create a relative URL for offline builds.
Before this fix, `.context.RelPermalink` was always `''` because the `image_resource` partial forwarded its own context to the `resource_url` partial. Now we use the page's context instead.
> Image 1
> Image 2
1. Clone https://github.mit.edu/ocw-content-rc/6.041sc-fall-2013 and save it to where you keep your OCW content locally. Name the cloned directory `6.041sc-fall-2013` for consistency with the steps that follow.
2. Download https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/6.041sc-fall-2013.zip, we'll be needing the `static_resources` directory from within.
3. Open your local …
=> fix: broken offline course images

base-theme/layouts/partials/external_resource_link.html, tests-e2e/ocw-ci-test-course/external-resources.spec.ts
Reverts mitodl/ocw-hugo-themes#1407
=> Revert "Presenting page links in navigation menu that are on the `ocw.mit.edu` domain"

package.json, yarn.lock
Reverts mitodl/ocw-hugo-themes#1466
=> Revert "Update dependency copy-webpack-plugin to v12"

www/content/staff/cheryl-siegel.md
Closes https://github.com/mitodl/hq/issues/7497.
This PR updates Cheryl Siegel's title on the OCW Team page.
Run `yarn start www`, and then navigate to http://localhost:3000/about. Verify that Cheryl Siegel's title has been updated properly, as described in the linked issue.
=> OCW Team page update - Cheryl Siegel

www/content/staff/cathleen-nalezyty.md
Closes https://github.com/mitodl/hq/issues/7819.
This PR updates Cathleen Nalezyty's title on the OCW Team page.
Run `yarn start www`, and then navigate to http://localhost:3000/about. Verify that Cathleen Nalezyty's title has been updated properly, as described in the linked issue.
=> Update Cathleen Nalezyty's title
